{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"packed\",\"dHora\",\"Parâmetro1\",\"Transformar o Arquivo de Exemplo\",\"Arquivo de Amostra\",\"Arquivo de Amostra (2)\",\"Transformar Arquivo (2)\",\"Transformar Arquivo\",\"Medidas\",\"entrada\",\"Arquivo de Amostra (3)\",\"Parâmetro2\",\"Transformar o Arquivo de Exemplo (2)\",\"Transformar Arquivo (3)\",\"carteira\",\"Transformar Arquivo (4)\",\"Arquivo de Amostra (4)\",\"Arquivo de Amostra (5)\",\"Parâmetro3\",\"Transformar o Arquivo de Exemplo (3)\",\"Transformar Arquivo (5)\",\"Arquivo de Amostra (6)\",\"Parâmetro4\",\"Transformar o Arquivo de Exemplo (4)\",\"Transformar Arquivo (6)\",\"status oLPN\",\"Transformar Arquivo (7)\",\"Arquivo de Amostra (7)\",\"Arquivo de Amostra (8)\",\"Parâmetro5\",\"Transformar o Arquivo de Exemplo (5)\",\"Transformar Arquivo (8)\",\"tTempo\",\"dTabela\",\"tDin_carteira\",\"tDesmarcados\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.138.1203.0 (24.11)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "pt-BR",
    "cultures": [
      {
        "name": "pt-BR",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "Parâmetro1",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "expression": "#\"Arquivo de Amostra\" meta [IsParameterQuery=true, BinaryIdentifier=#\"Arquivo de Amostra\", Type=\"Binary\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "124ab9b8-fbfa-45aa-b8f0-f9cd7e462435",
        "queryGroup": "Transformar Arquivo de Consulta1\\Consultas Auxiliares"
      },
      {
        "name": "Transformar o Arquivo de Exemplo",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Fonte = Excel.Workbook(Parâmetro1, null, true),",
          "    page_Sheet = Fonte{[Item=\"page\",Kind=\"Sheet\"]}[Data],",
          "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(page_Sheet, [PromoteAllScalars=true])",
          "in",
          "    #\"Cabeçalhos Promovidos\""
        ],
        "kind": "m",
        "lineageTag": "15827598-69a4-4580-bdb2-43d566dc5dce",
        "queryGroup": "Transformar Arquivo de Consulta1"
      },
      {
        "name": "Arquivo de Amostra",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": [
          "let",
          "    Fonte = SharePoint.Contents(\"https://viavarejo.sharepoint.com/sites/grupo_de_dados_wave\", [ApiVersion = 15]),",
          "    #\"Atualizaes de Relatrios Gerais\" = Fonte{[Name=\"Atualizaes de Relatrios Gerais\"]}[Content],",
          "    #\"Relatórios dinâmicos - ADMs - Vinicius & Almeida\" = #\"Atualizaes de Relatrios Gerais\"{[Name=\"Relatórios dinâmicos - ADMs - Vinicius & Almeida\"]}[Content],",
          "    #\"Relatórios rotativos\" = #\"Relatórios dinâmicos - ADMs - Vinicius & Almeida\"{[Name=\"Relatórios rotativos\"]}[Content],",
          "    #\"Painel Online - ADMs - Vinicius & Almeida\" = #\"Relatórios rotativos\"{[Name=\"Painel Online - ADMs - Vinicius & Almeida\"]}[Content],",
          "    #\"Packed - ADMs - Vinicius & Almeida\" = #\"Painel Online - ADMs - Vinicius & Almeida\"{[Name=\"Packed - ADMs - Vinicius & Almeida\"]}[Content],",
          "    Navegação1 = #\"Packed - ADMs - Vinicius & Almeida\"{0}[Content]",
          "in",
          "    Navegação1"
        ],
        "kind": "m",
        "lineageTag": "2c25d927-aa14-40aa-9885-d20a204ec14e",
        "queryGroup": "Transformar Arquivo de Consulta1\\Consultas Auxiliares"
      },
      {
        "name": "Transformar Arquivo",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let",
          "    Fonte = (Parâmetro1 as binary) => let",
          "    Fonte = Excel.Workbook(Parâmetro1, null, true),",
          "    page_Sheet = Fonte{[Item=\"page\",Kind=\"Sheet\"]}[Data],",
          "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(page_Sheet, [PromoteAllScalars=true])",
          "in",
          "    #\"Cabeçalhos Promovidos\"",
          "in",
          "    Fonte"
        ],
        "kind": "m",
        "lineageTag": "f77ea6bd-d99d-4942-82af-aecb1ee9c9fc",
        "queryGroup": "Transformar Arquivo de Consulta1\\Consultas Auxiliares"
      },
      {
        "name": "Arquivo de Amostra (2)",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Fonte = SharePoint.Contents(\"https://viavarejo.sharepoint.com/sites/grupo_de_dados_wave\", [ApiVersion = 15]),",
          "    #\"Atualizaes de Relatrios Gerais\" = Fonte{[Name=\"Atualizaes de Relatrios Gerais\"]}[Content],",
          "    #\"Relatórios dinâmicos - ADMs - Vinicius & Almeida\" = #\"Atualizaes de Relatrios Gerais\"{[Name=\"Relatórios dinâmicos - ADMs - Vinicius & Almeida\"]}[Content],",
          "    #\"Relatórios rotativos\" = #\"Relatórios dinâmicos - ADMs - Vinicius & Almeida\"{[Name=\"Relatórios rotativos\"]}[Content],",
          "    #\"Painel Online - ADMs - Vinicius & Almeida\" = #\"Relatórios rotativos\"{[Name=\"Painel Online - ADMs - Vinicius & Almeida\"]}[Content],",
          "    #\"Packed - ADMs - Vinicius & Almeida\" = #\"Painel Online - ADMs - Vinicius & Almeida\"{[Name=\"Packed - ADMs - Vinicius & Almeida\"]}[Content],",
          "    Navegação1 = #\"Packed - ADMs - Vinicius & Almeida\"{0}[Content],",
          "    #\"Pasta de Trabalho Importada do Excel\" = Excel.Workbook(Navegação1),",
          "    Page2_1_Sheet = #\"Pasta de Trabalho Importada do Excel\"{[Item=\"Page2_1\",Kind=\"Sheet\"]}[Data]",
          "in",
          "    Page2_1_Sheet"
        ],
        "kind": "m",
        "lineageTag": "0cd632a1-ff33-476e-a512-98d13f5a7376",
        "queryGroup": "Transformar Arquivo de Consulta1\\Consultas Auxiliares"
      },
      {
        "name": "Transformar Arquivo (2)",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let",
          "    Fonte = (Parâmetro1) => let",
          "        Fonte = Excel.Workbook(Parâmetro1, null, true),",
          "        page_Sheet = Fonte{[Item=\"page\",Kind=\"Sheet\"]}[Data],",
          "        #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(page_Sheet, [PromoteAllScalars=true])",
          "    in",
          "        #\"Cabeçalhos Promovidos\"",
          "in",
          "    Fonte"
        ],
        "kind": "m",
        "lineageTag": "c1edae16-d66a-4462-856d-72de74559ea6",
        "queryGroup": "Transformar Arquivo de Consulta1\\Consultas Auxiliares"
      },
      {
        "name": "Arquivo de Amostra (3)",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": [
          "let",
          "    Fonte = SharePoint.Contents(\"https://viavarejo.sharepoint.com/sites/grupo_de_dados_wave\", [ApiVersion = 15]),",
          "    #\"Atualizaes de Relatrios Gerais\" = Fonte{[Name=\"Atualizaes de Relatrios Gerais\"]}[Content],",
          "    #\"Relatórios dinâmicos - ADMs - Vinicius & Almeida\" = #\"Atualizaes de Relatrios Gerais\"{[Name=\"Relatórios dinâmicos - ADMs - Vinicius & Almeida\"]}[Content],",
          "    #\"Relatórios rotativos\" = #\"Relatórios dinâmicos - ADMs - Vinicius & Almeida\"{[Name=\"Relatórios rotativos\"]}[Content],",
          "    #\"Painel Online - ADMs - Vinicius & Almeida\" = #\"Relatórios rotativos\"{[Name=\"Painel Online - ADMs - Vinicius & Almeida\"]}[Content],",
          "    #\"Entrada - ADMs - Vinicius & Almeida\" = #\"Painel Online - ADMs - Vinicius & Almeida\"{[Name=\"Entrada - ADMs - Vinicius & Almeida\"]}[Content],",
          "    Navegação1 = #\"Entrada - ADMs - Vinicius & Almeida\"{0}[Content]",
          "in",
          "    Navegação1"
        ],
        "kind": "m",
        "lineageTag": "48367655-0cdd-4933-8c73-5cc6daa8e6d8",
        "queryGroup": "Transformar Arquivo de Consulta1\\Transformar Arquivo de entrada\\Consultas Auxiliares"
      },
      {
        "name": "Parâmetro2",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "expression": "#\"Arquivo de Amostra (3)\" meta [IsParameterQuery=true, BinaryIdentifier=#\"Arquivo de Amostra (3)\", Type=\"Binary\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "9624e95f-c12e-41ac-bfcd-1e33bcda6978",
        "queryGroup": "Transformar Arquivo de Consulta1\\Transformar Arquivo de entrada\\Consultas Auxiliares"
      },
      {
        "name": "Transformar o Arquivo de Exemplo (2)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Fonte = Csv.Document(Parâmetro2,[Delimiter=\";\", Columns=20, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
          "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true])",
          "in",
          "    #\"Cabeçalhos Promovidos\""
        ],
        "kind": "m",
        "lineageTag": "287e3b27-2357-4822-b838-e5b93d528956",
        "queryGroup": "Transformar Arquivo de Consulta1\\Transformar Arquivo de entrada"
      },
      {
        "name": "Transformar Arquivo (3)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let",
          "    Fonte = (Parâmetro2 as binary) => let",
          "    Fonte = Csv.Document(Parâmetro2,[Delimiter=\";\", Columns=20, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
          "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true])",
          "in",
          "    #\"Cabeçalhos Promovidos\"",
          "in",
          "    Fonte"
        ],
        "kind": "m",
        "lineageTag": "686047ba-127b-4ef0-9043-dcc5651f452f",
        "queryGroup": "Transformar Arquivo de Consulta1\\Transformar Arquivo de entrada\\Consultas Auxiliares"
      },
      {
        "name": "Transformar Arquivo (4)",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let",
          "    Fonte = (Parâmetro2) => let",
          "        Fonte = Csv.Document(Parâmetro2,[Delimiter=\";\", Columns=20, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
          "        #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true])",
          "    in",
          "        #\"Cabeçalhos Promovidos\"",
          "in",
          "    Fonte"
        ],
        "kind": "m",
        "lineageTag": "2fbaac26-a1b8-431a-90bf-625324c6162f",
        "queryGroup": "Transformar Arquivo de Consulta1"
      },
      {
        "name": "Arquivo de Amostra (4)",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": [
          "let",
          "    Fonte = SharePoint.Contents(\"https://viavarejo.sharepoint.com/sites/grupo_de_dados_wave\", [ApiVersion = 15]),",
          "    #\"Atualizaes de Relatrios Gerais\" = Fonte{[Name=\"Atualizaes de Relatrios Gerais\"]}[Content],",
          "    #\"Relatórios dinâmicos - ADMs - Vinicius & Almeida\" = #\"Atualizaes de Relatrios Gerais\"{[Name=\"Relatórios dinâmicos - ADMs - Vinicius & Almeida\"]}[Content],",
          "    #\"Relatórios rotativos\" = #\"Relatórios dinâmicos - ADMs - Vinicius & Almeida\"{[Name=\"Relatórios rotativos\"]}[Content],",
          "    #\"Painel Online - ADMs - Vinicius & Almeida\" = #\"Relatórios rotativos\"{[Name=\"Painel Online - ADMs - Vinicius & Almeida\"]}[Content],",
          "    #\"Entrada - ADMs - Vinicius & Almeida\" = #\"Painel Online - ADMs - Vinicius & Almeida\"{[Name=\"Entrada - ADMs - Vinicius & Almeida\"]}[Content],",
          "    Navegação1 = #\"Entrada - ADMs - Vinicius & Almeida\"{0}[Content]",
          "in",
          "    Navegação1"
        ],
        "kind": "m",
        "lineageTag": "c0dba87e-0526-4736-a5ef-bc3a7d42c4b5",
        "queryGroup": "Transformar Arquivo de Consulta1"
      },
      {
        "name": "Arquivo de Amostra (5)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": [
          "let",
          "    Fonte = SharePoint.Contents(\"https://viavarejo.sharepoint.com/sites/grupo_de_dados_wave\", [ApiVersion = 15]),",
          "    #\"Atualizaes de Relatrios Gerais\" = Fonte{[Name=\"Atualizaes de Relatrios Gerais\"]}[Content],",
          "    #\"Relatórios dinâmicos - ADMs - Vinicius & Almeida\" = #\"Atualizaes de Relatrios Gerais\"{[Name=\"Relatórios dinâmicos - ADMs - Vinicius & Almeida\"]}[Content],",
          "    #\"Relatórios rotativos\" = #\"Relatórios dinâmicos - ADMs - Vinicius & Almeida\"{[Name=\"Relatórios rotativos\"]}[Content],",
          "    #\"Painel Online - ADMs - Vinicius & Almeida\" = #\"Relatórios rotativos\"{[Name=\"Painel Online - ADMs - Vinicius & Almeida\"]}[Content],",
          "    #\"Carteira - ADMs - Vinicius & Almeida\" = #\"Painel Online - ADMs - Vinicius & Almeida\"{[Name=\"Carteira - ADMs - Vinicius & Almeida\"]}[Content],",
          "    Navegação1 = #\"Carteira - ADMs - Vinicius & Almeida\"{0}[Content]",
          "in",
          "    Navegação1"
        ],
        "kind": "m",
        "lineageTag": "fc68030c-15f2-4252-b4dd-51a54d5bb0fc",
        "queryGroup": "Transformar Arquivo de Consulta1\\Transformar Arquivo de carteira\\Consultas Auxiliares"
      },
      {
        "name": "Parâmetro3",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "expression": "#\"Arquivo de Amostra (5)\" meta [IsParameterQuery=true, BinaryIdentifier=#\"Arquivo de Amostra (5)\", Type=\"Binary\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "4650c6af-1e3c-424a-8aac-0bce151c9770",
        "queryGroup": "Transformar Arquivo de Consulta1\\Transformar Arquivo de carteira\\Consultas Auxiliares"
      },
      {
        "name": "Transformar o Arquivo de Exemplo (3)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Fonte = Csv.Document(Parâmetro3,[Delimiter=\":\", Encoding=1252])",
          "in",
          "    Fonte"
        ],
        "kind": "m",
        "lineageTag": "9a40d010-e508-43bf-b21b-a5515c6ab00c",
        "queryGroup": "Transformar Arquivo de Consulta1\\Transformar Arquivo de carteira"
      },
      {
        "name": "Transformar Arquivo (5)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let",
          "    Fonte = (Parâmetro3 as binary) => let",
          "    Fonte = Csv.Document(Parâmetro3,[Delimiter=\":\", Encoding=1252])",
          "in",
          "    Fonte",
          "in",
          "    Fonte"
        ],
        "kind": "m",
        "lineageTag": "b9c51708-c97a-477a-9fa7-52716757205d",
        "queryGroup": "Transformar Arquivo de Consulta1\\Transformar Arquivo de carteira\\Consultas Auxiliares"
      },
      {
        "name": "Arquivo de Amostra (6)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": [
          "let",
          "    Fonte = SharePoint.Contents(\"https://viavarejo.sharepoint.com/sites/grupo_de_dados_wave\", [ApiVersion = 15]),",
          "    #\"Atualizaes de Relatrios Gerais\" = Fonte{[Name=\"Atualizaes de Relatrios Gerais\"]}[Content],",
          "    #\"Relatórios dinâmicos - ADMs - Vinicius & Almeida\" = #\"Atualizaes de Relatrios Gerais\"{[Name=\"Relatórios dinâmicos - ADMs - Vinicius & Almeida\"]}[Content],",
          "    #\"Relatórios rotativos\" = #\"Relatórios dinâmicos - ADMs - Vinicius & Almeida\"{[Name=\"Relatórios rotativos\"]}[Content],",
          "    #\"Painel Online - ADMs - Vinicius & Almeida\" = #\"Relatórios rotativos\"{[Name=\"Painel Online - ADMs - Vinicius & Almeida\"]}[Content],",
          "    #\"Carteira - ADMs - Vinicius & Almeida\" = #\"Painel Online - ADMs - Vinicius & Almeida\"{[Name=\"Carteira - ADMs - Vinicius & Almeida\"]}[Content],",
          "    #\"Arquivos Ocultos Filtrados1\" = Table.SelectRows(#\"Carteira - ADMs - Vinicius & Almeida\", each [Attributes]?[Hidden]? <> true),",
          "    Navegação1 = #\"Arquivos Ocultos Filtrados1\"{0}[Content]",
          "in",
          "    Navegação1"
        ],
        "kind": "m",
        "lineageTag": "e3eecc63-ca85-4efc-9df6-906b267d17ab",
        "queryGroup": "Transformar Arquivo de Consulta1\\Transformar Arquivo de carteira (2)\\Consultas Auxiliares"
      },
      {
        "name": "Parâmetro4",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "expression": "#\"Arquivo de Amostra (6)\" meta [IsParameterQuery=true, BinaryIdentifier=#\"Arquivo de Amostra (6)\", Type=\"Binary\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "2a7592ae-c3b0-42f2-8f88-deb003c7cf38",
        "queryGroup": "Transformar Arquivo de Consulta1\\Transformar Arquivo de carteira (2)\\Consultas Auxiliares"
      },
      {
        "name": "Transformar o Arquivo de Exemplo (4)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Fonte = Csv.Document(Parâmetro4,[Delimiter=\";\", Columns=54, Encoding=1252]),",
          "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true])",
          "in",
          "    #\"Cabeçalhos Promovidos\""
        ],
        "kind": "m",
        "lineageTag": "b0d1c28b-a608-49d1-a6f4-1319b71352b9",
        "queryGroup": "Transformar Arquivo de Consulta1\\Transformar Arquivo de carteira (2)"
      },
      {
        "name": "Transformar Arquivo (6)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let",
          "    Fonte = (Parâmetro4 as binary) => let",
          "    Fonte = Csv.Document(Parâmetro4,[Delimiter=\";\", Columns=54, Encoding=1252]),",
          "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true])",
          "in",
          "    #\"Cabeçalhos Promovidos\"",
          "in",
          "    Fonte"
        ],
        "kind": "m",
        "lineageTag": "5703a078-a688-4f26-957e-cfa858471e61",
        "queryGroup": "Transformar Arquivo de Consulta1\\Transformar Arquivo de carteira (2)\\Consultas Auxiliares"
      },
      {
        "name": "Transformar Arquivo (7)",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let",
          "    Fonte = (Parâmetro1) => let",
          "        Fonte = Excel.Workbook(Parâmetro1, null, true),",
          "        page_Sheet = Fonte{[Item=\"page\",Kind=\"Sheet\"]}[Data],",
          "        #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(page_Sheet, [PromoteAllScalars=true])",
          "    in",
          "        #\"Cabeçalhos Promovidos\"",
          "in",
          "    Fonte"
        ],
        "kind": "m",
        "lineageTag": "f3ee5f8b-354d-46b7-aec6-fa892fc6b13e",
        "queryGroup": "Transformar Arquivo de Consulta1"
      },
      {
        "name": "Arquivo de Amostra (7)",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": [
          "let",
          "    Fonte = SharePoint.Contents(\"https://viavarejo.sharepoint.com/sites/grupo_de_dados_wave\", [ApiVersion = 15]),",
          "    #\"Atualizaes de Relatrios Gerais\" = Fonte{[Name=\"Atualizaes de Relatrios Gerais\"]}[Content],",
          "    #\"Relatórios dinâmicos - ADMs - Vinicius & Almeida\" = #\"Atualizaes de Relatrios Gerais\"{[Name=\"Relatórios dinâmicos - ADMs - Vinicius & Almeida\"]}[Content],",
          "    #\"Relatórios rotativos\" = #\"Relatórios dinâmicos - ADMs - Vinicius & Almeida\"{[Name=\"Relatórios rotativos\"]}[Content],",
          "    #\"Painel Online - ADMs - Vinicius & Almeida\" = #\"Relatórios rotativos\"{[Name=\"Painel Online - ADMs - Vinicius & Almeida\"]}[Content],",
          "    #\"Packed - ADMs - Vinicius & Almeida\" = #\"Painel Online - ADMs - Vinicius & Almeida\"{[Name=\"Packed - ADMs - Vinicius & Almeida\"]}[Content],",
          "    Navegação1 = #\"Packed - ADMs - Vinicius & Almeida\"{0}[Content]",
          "in",
          "    Navegação1"
        ],
        "kind": "m",
        "lineageTag": "90fca528-b07c-4562-821c-8dedbb7d100b",
        "queryGroup": "Transformar Arquivo de Consulta1"
      },
      {
        "name": "Arquivo de Amostra (8)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": [
          "let",
          "    Fonte = SharePoint.Contents(\"https://viavarejo.sharepoint.com/sites/grupo_de_dados_wave\", [ApiVersion = 15]),",
          "    #\"Atualizaes de Relatrios Gerais\" = Fonte{[Name=\"Atualizaes de Relatrios Gerais\"]}[Content],",
          "    #\"Relatórios dinâmicos - ADMs - Vinicius & Almeida\" = #\"Atualizaes de Relatrios Gerais\"{[Name=\"Relatórios dinâmicos - ADMs - Vinicius & Almeida\"]}[Content],",
          "    #\"Relatórios rotativos\" = #\"Relatórios dinâmicos - ADMs - Vinicius & Almeida\"{[Name=\"Relatórios rotativos\"]}[Content],",
          "    #\"Painel Online - ADMs - Vinicius & Almeida\" = #\"Relatórios rotativos\"{[Name=\"Painel Online - ADMs - Vinicius & Almeida\"]}[Content],",
          "    #\"Status oLPN - ADMs - Vinicius & Almeida\" = #\"Painel Online - ADMs - Vinicius & Almeida\"{[Name=\"Status oLPN - ADMs - Vinicius & Almeida\"]}[Content],",
          "    Navegação1 = #\"Status oLPN - ADMs - Vinicius & Almeida\"{0}[Content]",
          "in",
          "    Navegação1"
        ],
        "kind": "m",
        "lineageTag": "bd83a205-5d9f-4aea-9f02-9fa228ce3a20",
        "queryGroup": "Transformar Arquivo de Consulta1\\Transformar Arquivo de status oLPN\\Consultas Auxiliares"
      },
      {
        "name": "Parâmetro5",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "expression": "#\"Arquivo de Amostra (8)\" meta [IsParameterQuery=true, BinaryIdentifier=#\"Arquivo de Amostra (8)\", Type=\"Binary\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "8f7c389f-3699-4d72-8a51-de76ca911ff3",
        "queryGroup": "Transformar Arquivo de Consulta1\\Transformar Arquivo de status oLPN\\Consultas Auxiliares"
      },
      {
        "name": "Transformar o Arquivo de Exemplo (5)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Fonte = Csv.Document(Parâmetro5,[Delimiter=\"\t\", Columns=31, Encoding=1200, QuoteStyle=QuoteStyle.None]),",
          "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true])",
          "in",
          "    #\"Cabeçalhos Promovidos\""
        ],
        "kind": "m",
        "lineageTag": "ef51e042-806d-418d-80f2-3a0201ee024e",
        "queryGroup": "Transformar Arquivo de Consulta1\\Transformar Arquivo de status oLPN"
      },
      {
        "name": "Transformar Arquivo (8)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let",
          "    Fonte = (Parâmetro5 as binary) => let",
          "    Fonte = Csv.Document(Parâmetro5,[Delimiter=\"\t\", Columns=31, Encoding=1200, QuoteStyle=QuoteStyle.None]),",
          "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true])",
          "in",
          "    #\"Cabeçalhos Promovidos\"",
          "in",
          "    Fonte"
        ],
        "kind": "m",
        "lineageTag": "4a123f69-a26d-4755-96af-dfe6f1bbfc21",
        "queryGroup": "Transformar Arquivo de Consulta1\\Transformar Arquivo de status oLPN\\Consultas Auxiliares"
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Transformar Arquivo de Consulta1"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Transformar Arquivo de Consulta1\\Consultas Auxiliares"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ],
        "folder": "Transformar Arquivo de Consulta1\\Transformar Arquivo de entrada"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Transformar Arquivo de Consulta1\\Transformar Arquivo de entrada\\Consultas Auxiliares"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "3"
          }
        ],
        "folder": "Transformar Arquivo de Consulta1\\Transformar Arquivo de carteira"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Transformar Arquivo de Consulta1\\Transformar Arquivo de carteira\\Consultas Auxiliares"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "2"
          }
        ],
        "folder": "Transformar Arquivo de Consulta1\\Transformar Arquivo de carteira (2)"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Transformar Arquivo de Consulta1\\Transformar Arquivo de carteira (2)\\Consultas Auxiliares"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "4"
          }
        ],
        "folder": "Transformar Arquivo de Consulta1\\Transformar Arquivo de status oLPN"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Transformar Arquivo de Consulta1\\Transformar Arquivo de status oLPN\\Consultas Auxiliares"
      }
    ],
    "relationships": [
      {
        "name": "8e99b4ba-9e58-4c16-b8c1-e8b2e4238c67",
        "fromColumn": "Data Pedido",
        "fromTable": "packed",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_9be0a899-3426-4790-8ef4-cca42e3f6bbe"
      },
      {
        "name": "42dd7184-ab81-49b0-a70f-98b11103cf77",
        "fromColumn": "Data Packed",
        "fromTable": "packed",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_ef256f4d-b9f4-4cbb-b60d-e252a689018b"
      },
      {
        "name": "de13782f-1128-47db-b698-cd1344f1c715",
        "fromColumn": " DT_EMI_CARGA",
        "fromTable": "carteira",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_c4d33cb2-a1aa-4080-9242-482afcb197a5"
      },
      {
        "name": "ab608b55-4c93-47e8-bb38-042dbe21d708",
        "fromColumn": "DT_PREV_CARGA",
        "fromTable": "carteira",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_7d8dcf04-db06-423d-bd1c-964028d29b65"
      },
      {
        "name": "9995fbdf-a891-46ac-91e7-69f7a9e6b26e",
        "fromColumn": "DT_LIMITE  ",
        "fromTable": "carteira",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_651663f4-1ba0-4bf3-af74-833f6eb94270"
      },
      {
        "name": "018d1f04-ee4d-46ee-a38d-82184818cff9",
        "fromColumn": "DATA PVE/MIG ",
        "fromTable": "carteira",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_ed27a44c-4c3c-4b63-94ef-30d85b1de634"
      },
      {
        "name": "ebdb5d42-94c2-443d-bf47-2f4cd8b9c0d9",
        "fromColumn": " DATA_PROMETIDA ",
        "fromTable": "carteira",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_5d585d2d-fdca-4b22-ab1b-b15d208473a7"
      },
      {
        "name": "e6a7c465-86c8-4510-ad37-5e72bcd171c5",
        "fromColumn": "DATA_MARCADA ",
        "fromTable": "carteira",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_a1e482f1-8307-44d3-9932-440eaad15ef6"
      },
      {
        "name": "d2213630-53aa-4edc-861e-59b571fe29c2",
        "fromColumn": "Data do Pedido",
        "fromTable": "status oLPN",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_d1bb81b4-3c99-41ee-abbe-7fc1bfedfb22"
      },
      {
        "name": "03547ef9-133e-4075-ad78-af121ac65606",
        "fromColumn": "Data locação pedido",
        "fromTable": "status oLPN",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_c63d3909-04ff-4e99-855a-2f8fa1504e6f"
      },
      {
        "name": "d36c33b1-04e0-4f25-8514-0c12b2e7b7ed",
        "fromColumn": "Último Update oLPN",
        "fromTable": "status oLPN",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_26ede0fe-5b25-41aa-a9c9-3632ca32ab7e"
      },
      {
        "name": "b794c020-44b5-4fcd-bd82-5654f0d17fb3",
        "fromColumn": "Data Prevista Entrega",
        "fromTable": "status oLPN",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_7cccec5d-27f3-406a-8bc5-57140bba9558"
      },
      {
        "name": "693142ac-d89d-ef7c-7b46-bfc17bb3c3ba",
        "fromColumn": "hora_da_integração",
        "fromTable": "entrada",
        "toColumn": "Hora",
        "toTable": "dHora"
      },
      {
        "name": "67d64053-a3e7-9c31-8a2c-e3868a498000",
        "fromColumn": " HORA_VENDA",
        "fromTable": "carteira",
        "toColumn": "Hora",
        "toTable": "dHora"
      },
      {
        "name": "97d3f873-4915-48ec-bb70-412e8fe10bb9",
        "fromColumn": "DATA DE LIMITE",
        "fromTable": "entrada",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_dd0d8641-6c07-4ce1-a5cc-5c9d44d4aa0d"
      },
      {
        "name": "64212890-231e-4166-a857-aa7872a394e9",
        "fromColumn": "DATA DA INTEGRACAO",
        "fromTable": "entrada",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_222bf26e-cc17-4215-bf94-0aa98a5433de"
      },
      {
        "name": "139683a1-414f-4c5c-ede4-741a6f35a600",
        "fromColumn": "hora_packed",
        "fromTable": "packed",
        "toColumn": "Hora",
        "toTable": "dHora"
      },
      {
        "name": "09dc630a-cb70-476f-a50e-d668e9aca4be",
        "fromColumn": "data_atual",
        "fromTable": "tTempo",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_bb704698-fda9-40bc-afa2-c582658f15c5"
      },
      {
        "name": "baabe591-c8d7-4567-b3e0-9bccae454288",
        "fromColumn": "data limite",
        "fromTable": "carteira",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_a6bf9114-e982-44b9-a50c-2f6304f840bf"
      },
      {
        "name": "AutoDetected_120b10c7-2edf-4335-b427-79ebd557734f",
        "fromColumn": "TIPO DE ENTREGA",
        "fromTable": "carteira",
        "toColumn": "TIPO DE ENTREGA",
        "toTable": "tDin_carteira"
      },
      {
        "name": "24bdac68-10c2-47e6-b86f-fa978fe8f936",
        "fromColumn": "data limite2",
        "fromTable": "carteira",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_3926822b-92bc-4a54-a29e-0e2ec41e514a"
      },
      {
        "name": "71752ec7-72a9-4414-82f3-c0f161ceee34",
        "fromColumn": "data para a data",
        "fromTable": "status oLPN",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_70ce231e-4aa2-4a70-9ace-ea66fc5068c6"
      },
      {
        "name": "00bd9f8f-72d6-4cc0-b530-4032899845f3",
        "fromColumn": "Data Limite Expedição",
        "fromTable": "status oLPN",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_ac232e2a-83b0-4b47-81e3-e9456bc653d8"
      }
    ],
    "sourceQueryCulture": "pt-BR",
    "tables": [
      {
        "name": "packed",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "Filial",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "49b3318f-c34d-45fe-9d3b-120869befe07",
            "sourceColumn": "Filial",
            "summarizeBy": "sum"
          },
          {
            "name": "OLPN",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ed4107c9-c320-4b99-a6b2-06f01a8242d2",
            "sourceColumn": "OLPN",
            "summarizeBy": "sum"
          },
          {
            "name": "Pedido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d0b137f4-d465-40b3-8c40-010771f13412",
            "sourceColumn": "Pedido",
            "summarizeBy": "sum"
          },
          {
            "name": "Pallet",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "381a3e56-69d6-4d8b-a489-cc1c948761e4",
            "sourceColumn": "Pallet",
            "summarizeBy": "sum"
          },
          {
            "name": "Inventory Type ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "07f0e51a-1e6d-4c61-8ff1-470239bd4eaf",
            "sourceColumn": "Inventory Type ID",
            "summarizeBy": "count"
          },
          {
            "name": "Item",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "81c0b37a-9a1f-43f7-964b-365544b185e2",
            "sourceColumn": "Item",
            "summarizeBy": "sum"
          },
          {
            "name": "Descrição item",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e499f22d-814d-41a6-b9f6-30f763eba5d0",
            "sourceColumn": "Descrição item",
            "summarizeBy": "none"
          },
          {
            "name": "Setor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9547946b-4cd2-481c-ba98-b976893880e1",
            "sourceColumn": "Setor",
            "summarizeBy": "none"
          },
          {
            "name": "Tipo Pedido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bceff250-85bb-4e58-ba65-2216ebab2fdd",
            "sourceColumn": "Tipo Pedido",
            "summarizeBy": "none"
          },
          {
            "name": "Usuário",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4c487526-af12-458a-9191-79a8bd9587ed",
            "sourceColumn": "Usuário",
            "summarizeBy": "none"
          },
          {
            "name": "Nome do Usuário",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e6be4087-443c-4d10-9ec1-46b537731b52",
            "sourceColumn": "Nome do Usuário",
            "summarizeBy": "none"
          },
          {
            "name": "Shipment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "aba3914b-0e7a-4f8a-bd15-86cb53ac7998",
            "sourceColumn": "Shipment",
            "summarizeBy": "sum"
          },
          {
            "name": "Quantidade",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7aee7b4a-f21e-4c07-9917-35a0652187aa",
            "sourceColumn": "Quantidade",
            "summarizeBy": "sum"
          },
          {
            "name": "Pedido venda",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a8b46c03-e722-4c01-a745-6668196f9eff",
            "sourceColumn": "Pedido venda",
            "summarizeBy": "sum"
          },
          {
            "name": "Nota Fiscal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2649a970-7af1-43d4-b9b2-ebeb52df3ebd",
            "sourceColumn": "Nota Fiscal",
            "summarizeBy": "sum"
          },
          {
            "name": "BOX",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3e20f250-adc1-4183-8bec-42192d9fd126",
            "sourceColumn": "BOX",
            "summarizeBy": "sum"
          },
          {
            "name": "Embala",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "557595e1-31a7-4d67-b068-3faf3de55f52",
            "sourceColumn": "Embala",
            "summarizeBy": "none"
          },
          {
            "name": "Data Pedido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "be6196ab-f422-448f-a244-ccaa2a2f42a6",
            "sourceColumn": "Data Pedido",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_9be0a899-3426-4790-8ef4-cca42e3f6bbe"
                },
                "isDefault": true,
                "relationship": "8e99b4ba-9e58-4c16-b8c1-e8b2e4238c67"
              }
            ]
          },
          {
            "name": "Data Packed",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "f16c5e65-ab17-486d-89e0-224669e024ec",
            "sourceColumn": "Data Packed",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_ef256f4d-b9f4-4cbb-b60d-e252a689018b"
                },
                "isDefault": true,
                "relationship": "42dd7184-ab81-49b0-a70f-98b11103cf77"
              }
            ]
          },
          {
            "name": "hora_packed",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "7b80851b-a73e-47d7-9f6b-eecd5223b902",
            "sourceColumn": "hora_packed",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "90624690-4c0a-4216-b6de-534f5b91cf63",
        "partitions": [
          {
            "name": "packed",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = SharePoint.Contents(\"https://viavarejo.sharepoint.com/sites/grupo_de_dados_wave\", [ApiVersion = 15]),",
                "    #\"Atualizaes de Relatrios Gerais\" = Fonte{[Name=\"Atualizaes de Relatrios Gerais\"]}[Content],",
                "    #\"Relatórios dinâmicos - ADMs - Vinicius & Almeida\" = #\"Atualizaes de Relatrios Gerais\"{[Name=\"Relatórios dinâmicos - ADMs - Vinicius & Almeida\"]}[Content],",
                "    #\"Relatórios rotativos\" = #\"Relatórios dinâmicos - ADMs - Vinicius & Almeida\"{[Name=\"Relatórios rotativos\"]}[Content],",
                "    #\"Painel Online - ADMs - Vinicius & Almeida\" = #\"Relatórios rotativos\"{[Name=\"Painel Online - ADMs - Vinicius & Almeida\"]}[Content],",
                "    #\"Packed - ADMs - Vinicius & Almeida\" = #\"Painel Online - ADMs - Vinicius & Almeida\"{[Name=\"Packed - ADMs - Vinicius & Almeida\"]}[Content],",
                "    #\"Arquivos Ocultos Filtrados1\" = Table.SelectRows(#\"Packed - ADMs - Vinicius & Almeida\", each [Attributes]?[Hidden]? <> true),",
                "    #\"Invocar Função Personalizada1\" = Table.AddColumn(#\"Arquivos Ocultos Filtrados1\", \"Transformar Arquivo\", each #\"Transformar Arquivo\"([Content])),",
                "    #\"Colunas Renomeadas1\" = Table.RenameColumns(#\"Invocar Função Personalizada1\", {\"Name\", \"Nome da Origem\"}),",
                "    #\"Outras Colunas Removidas1\" = Table.SelectColumns(#\"Colunas Renomeadas1\", {\"Nome da Origem\", \"Transformar Arquivo\"}),",
                "    #\"Coluna de Tabela Expandida1\" = Table.ExpandTableColumn(#\"Outras Colunas Removidas1\", \"Transformar Arquivo\", Table.ColumnNames(#\"Transformar Arquivo\"(#\"Arquivo de Amostra\"))),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Coluna de Tabela Expandida1\",{{\"Nome da Origem\", type text}, {\"Filial\", Int64.Type}, {\"Inventory Type ID\", Int64.Type}, {\"OLPN\", Int64.Type}, {\"Pedido\", Int64.Type}, {\"Pallet\", Int64.Type}, {\"Item\", Int64.Type}, {\"Descrição item\", type text}, {\"Setor\", type text}, {\"Tipo Pedido\", type text}, {\"Data Pedido\", type datetime}, {\"Data Packed\", type datetime}, {\"Usuário\", type text}, {\"Nome do Usuário\", type text}, {\"Shipment\", Int64.Type}, {\"Quantidade\", Int64.Type}, {\"Pedido venda\", Int64.Type}, {\"Nota Fiscal\", Int64.Type}, {\"BOX\", Int64.Type}, {\"Embala\", type text}}),",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(#\"Tipo Alterado\",{\"Nome da Origem\"}),",
                "    #\"Colunas Reordenadas\" = Table.ReorderColumns(#\"Colunas Removidas\",{\"Filial\", \"OLPN\", \"Pedido\", \"Pallet\", \"Inventory Type ID\", \"Item\", \"Descrição item\", \"Setor\", \"Tipo Pedido\", \"Usuário\", \"Nome do Usuário\", \"Shipment\", \"Quantidade\", \"Pedido venda\", \"Nota Fiscal\", \"BOX\", \"Embala\", \"Data Pedido\", \"Data Packed\"}),",
                "    #\"Início da Hora Inserido\" = Table.AddColumn(#\"Colunas Reordenadas\", \"Início da Hora\", each Time.StartOfHour([Data Pedido]), type datetime),",
                "    #\"Horário Extraído\" = Table.TransformColumns(#\"Início da Hora Inserido\",{{\"Início da Hora\", DateTime.Time, type time}}),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Horário Extraído\",{{\"Início da Hora\", \"hora_pedido\"}}),",
                "    #\"Colunas Reordenadas1\" = Table.ReorderColumns(#\"Colunas Renomeadas\",{\"Filial\", \"OLPN\", \"Pedido\", \"Pallet\", \"Inventory Type ID\", \"Item\", \"Descrição item\", \"Setor\", \"Tipo Pedido\", \"Usuário\", \"Nome do Usuário\", \"Shipment\", \"Quantidade\", \"Pedido venda\", \"Nota Fiscal\", \"BOX\", \"Embala\", \"Data Pedido\", \"hora_pedido\", \"Data Packed\"}),",
                "    #\"Data Extraída\" = Table.TransformColumns(#\"Colunas Reordenadas1\",{{\"Data Pedido\", DateTime.Date, type date}}),",
                "    #\"Início da Hora Inserido1\" = Table.AddColumn(#\"Data Extraída\", \"Início da Hora\", each Time.StartOfHour([Data Packed]), type datetime),",
                "    #\"Horário Extraído1\" = Table.TransformColumns(#\"Início da Hora Inserido1\",{{\"Início da Hora\", DateTime.Time, type time}}),",
                "    #\"Colunas Renomeadas2\" = Table.RenameColumns(#\"Horário Extraído1\",{{\"Início da Hora\", \"hora_packed\"}}),",
                "    #\"Data Extraída1\" = Table.TransformColumns(#\"Colunas Renomeadas2\",{{\"Data Packed\", DateTime.Date, type date}}),",
                "    #\"Colunas Removidas1\" = Table.RemoveColumns(#\"Data Extraída1\",{\"hora_pedido\"})",
                "in",
                "    #\"Colunas Removidas1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_ce8f41d5-9aa3-4ad9-b002-6991e95a2932",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "bfd16caf-a664-42da-80f1-d1b2861968b0",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "95f8b2c9-5082-4b7b-af27-cbdc8f70f192",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "011025ee-1e67-4326-953e-8ce386f936c3",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "e6c3ba2a-bca6-41c6-8f0a-4545c0ed4011",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "511a6f0c-ae96-4812-b471-0639e1a11343",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "7b13cfe8-7fa4-476c-bcb0-742f2aa7fcaa",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "905baa55-01d8-4559-ac9e-c29fc9e05a19",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "6eef7442-b6e6-4841-876d-b9d534777545",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "fa106333-ae65-42bc-ad9a-5c1a979e5ad2",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "1b79ea20-d45f-45a3-b538-c39807f5d3ae",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "8b96d9f7-d584-48df-8d5a-f01ee9c32674",
                "ordinal": 3
              }
            ],
            "lineageTag": "c142388e-404a-491e-a53d-ea7ca344589a"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "bf67d756-60d2-445c-acbf-104ff65399fc",
        "partitions": [
          {
            "name": "DateTableTemplate_ce8f41d5-9aa3-4ad9-b002-6991e95a2932",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_9be0a899-3426-4790-8ef4-cca42e3f6bbe",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "f5cac862-c4d1-4574-a912-c4ee0be74556",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "74dbe60a-4a24-4b30-801f-de41d87bb204",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "9d8ebf43-2b30-4543-b939-cdc86db6b354",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "94e10431-ec4c-456e-9444-81935cb77ff7",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "22d77fce-5d41-40bc-a08c-a32f76af7121",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "1eba0a95-f0d2-4313-bd6f-45f29a3e4675",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "3e352578-68e2-4c29-a740-83c6b609010e",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "222fe88e-9453-485f-82c5-b1ec35bf0136",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "7c0ed30b-4d39-4ed3-a1f1-4dbe680c3a0b",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "e8d13f2e-8599-4563-bb4e-cc2b96276111",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "30cd56c0-dca3-4416-a888-cfbd35596ae1",
                "ordinal": 3
              }
            ],
            "lineageTag": "8031de0b-2afe-41cd-b946-8f1cb9282a35"
          }
        ],
        "isHidden": true,
        "lineageTag": "821b72f2-27fc-4e6f-a837-695bb99e4ab1",
        "partitions": [
          {
            "name": "LocalDateTable_9be0a899-3426-4790-8ef4-cca42e3f6bbe",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('packed'[Data Pedido])), 1, 1), Date(Year(MAX('packed'[Data Pedido])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_ef256f4d-b9f4-4cbb-b60d-e252a689018b",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "c408a935-0dc4-4ddf-a8b5-cbd7e26ce9d1",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "7f233901-49e3-4988-bd68-b6c887d785c1",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "4508e449-668c-4b98-a05d-33eccf34e2e1",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "dc4b57ba-488a-4838-8338-81f5c83cdb45",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "7fab7e4f-ad68-4d81-9003-479d95a47251",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "ab5db909-6c4f-4e55-a7a4-aff3a7135dfb",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "c0234c97-c1a0-4087-a4a5-42f3deaed45e",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "b0ad1d7f-fe1a-4b95-a59d-79a7e284f863",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "ec67f317-1c96-498c-a5b4-f168f5fdc374",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "e894e018-d1da-4706-995e-3c55a72665f3",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "77c97644-8f56-498c-9700-2e9763909630",
                "ordinal": 3
              }
            ],
            "lineageTag": "1d124d15-81c6-454e-8e2c-154dc39dff47"
          }
        ],
        "isHidden": true,
        "lineageTag": "87b331c5-db6a-4942-8ef0-7a3cf8a8513b",
        "partitions": [
          {
            "name": "LocalDateTable_ef256f4d-b9f4-4cbb-b60d-e252a689018b",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('packed'[Data Packed])), 1, 1), Date(Year(MAX('packed'[Data Packed])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Medidas",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Coluna 1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "2f11d801-5bdc-4d67-965c-53cb87b8348c",
            "sourceColumn": "Coluna 1",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "757ab484-96ce-4fc0-8191-dc728c52f7e0",
        "measures": [
          {
            "name": "qtd_de_pedidos_packed",
            "displayFolder": "Quantidade de pedidos",
            "expression": "DISTINCTCOUNT(packed[Pedido venda])",
            "formatString": "0",
            "lineageTag": "5498f8f7-5a42-4c7f-bd9b-70599c33c4fd"
          },
          {
            "name": "qt_pedidos_entrada",
            "displayFolder": "Quantidade de pedidos",
            "expression": [
              "DISTINCTCOUNT(entrada[NUMERO DO PEDIDO])",
              ""
            ],
            "formatString": "0",
            "lineageTag": "d64fa1cf-d19c-4796-97eb-a7d5cf1bfcb9"
          },
          {
            "name": "qt_pedidos_carteira",
            "displayFolder": "Quantidade de pedidos",
            "expression": "DISTINCTCOUNT(carteira[  PEDIDOS   ])",
            "formatString": "0",
            "lineageTag": "49843f2f-07a3-4953-bad6-f510b0e2e05c"
          },
          {
            "name": "qt_pedidos_olpn",
            "displayFolder": "Quantidade de pedidos",
            "expression": "DISTINCTCOUNT('status oLPN'[Pedido de Venda])",
            "formatString": "#,0",
            "lineageTag": "706b7c7a-b8b5-4626-90b7-25da31556c20"
          },
          {
            "name": "qt_pedidos_entrada_filter_semana_passada",
            "displayFolder": "Quantidade de pedidos filtrados",
            "expression": [
              "",
              "CALCULATE(",
              "    [qt_pedidos_entrada],",
              "    entrada[DATA DA INTEGRACAO] = TODAY()-7)"
            ],
            "formatString": "#,0",
            "lineageTag": "2bb8c601-80c8-461d-ac8c-a0dc4a81ddee"
          },
          {
            "name": "qt_pedidos_entrada_filter_ontem",
            "displayFolder": "Quantidade de pedidos filtrados",
            "expression": [
              "",
              "CALCULATE(",
              "    [qt_pedidos_entrada],",
              "    entrada[DATA DA INTEGRACAO] = TODAY()-1)"
            ],
            "formatString": "#,0",
            "lineageTag": "f7c3e3c7-ccad-4164-b18d-726459c6a52b"
          },
          {
            "name": "qt_pedidos_packed_filter_semana_passada",
            "displayFolder": "Quantidade de pedidos filtrados",
            "expression": [
              "",
              "CALCULATE(",
              "    [qtd_de_pedidos_packed],",
              "    packed[Data Packed] = TODAY()-7)"
            ],
            "formatString": "#,0",
            "lineageTag": "5a295cba-edaf-4c21-934a-0674c82ca095"
          },
          {
            "name": "qt_pedidos_entrada_filter_hoje",
            "displayFolder": "Quantidade de pedidos filtrados",
            "expression": [
              "",
              "CALCULATE(",
              "    [qt_pedidos_entrada],",
              "    entrada[DATA DA INTEGRACAO] = TODAY())"
            ],
            "formatString": "#,0",
            "lineageTag": "653b767e-bcf9-41c3-a00d-7e5296b533d1"
          },
          {
            "name": "qt_pedidos_packed_filter_ontem",
            "displayFolder": "Quantidade de pedidos filtrados",
            "expression": [
              "",
              "CALCULATE(",
              "    [qtd_de_pedidos_packed],",
              "    packed[Data Packed] = TODAY()-1)"
            ],
            "formatString": "#,0",
            "lineageTag": "e8afb938-ed6a-436c-8d56-b37da33454ae"
          },
          {
            "name": "qt_pedidos_packed_filter_hoje",
            "displayFolder": "Quantidade de pedidos filtrados",
            "expression": [
              "",
              "CALCULATE(",
              "    [qtd_de_pedidos_packed],",
              "    packed[Data Packed] = TODAY())"
            ],
            "formatString": "#,0",
            "lineageTag": "58379a43-bf43-416b-a629-a56f0e3e09c4"
          },
          {
            "name": "med_faturamento_de_ped_hoje",
            "displayFolder": "Médias",
            "expression": [
              "",
              "",
              "VAR hora = ",
              "CALCULATE(",
              "    DISTINCTCOUNT(packed[hora_packed]),",
              "    packed[Data Packed] = TODAY())",
              "",
              "RETURN",
              "",
              "DIVIDE([qt_pedidos_packed_filter_hoje],hora)"
            ],
            "formatString": "#,0",
            "lineageTag": "6e3920f6-5988-4ce1-a21c-5259b455aea5"
          },
          {
            "name": "med_faturamento_de_ped_ontem",
            "displayFolder": "Médias",
            "expression": [
              "",
              "",
              "VAR hora = ",
              "CALCULATE(",
              "    DISTINCTCOUNT(packed[hora_packed]),",
              "    packed[Data Packed] = TODAY()-1)",
              "",
              "VAR logica = DIVIDE([qt_pedidos_packed_filter_ontem],hora)",
              "",
              "RETURN",
              "logica",
              ""
            ],
            "formatString": "#,0",
            "lineageTag": "850fe905-bd9e-479d-aaa3-d92646b35abf"
          },
          {
            "name": "med_faturamento_de_ped_semana_passada",
            "displayFolder": "Médias",
            "expression": [
              "",
              "",
              "VAR hora = ",
              "CALCULATE(",
              "    DISTINCTCOUNT(packed[hora_packed]),",
              "    packed[Data Packed] = TODAY()-7)",
              "",
              "VAR logica = DIVIDE([qt_pedidos_packed_filter_semana_passada],hora)",
              "",
              "RETURN",
              "logica",
              ""
            ],
            "formatString": "#,0",
            "lineageTag": "05bf6c43-61b4-44e0-bc90-b34dec75f5ce"
          },
          {
            "name": "med_entrada_de_ped_hoje",
            "displayFolder": "Médias",
            "expression": [
              "",
              "",
              "VAR hora = ",
              "CALCULATE(",
              "    DISTINCTCOUNT(entrada[hora_da_integração]),",
              "    entrada[DATA DA INTEGRACAO] = TODAY())",
              "",
              "RETURN",
              "",
              "DIVIDE([qt_pedidos_entrada_filter_hoje],hora)"
            ],
            "formatString": "#,0",
            "lineageTag": "dd4fd9f7-02f4-4311-8c4f-8b5ecac60a92"
          },
          {
            "name": "med_entrada_de_ped_ontem",
            "displayFolder": "Médias",
            "expression": [
              "",
              "",
              "VAR hora = ",
              "CALCULATE(",
              "    DISTINCTCOUNT(entrada[hora_da_integração]),",
              "    entrada[DATA DA INTEGRACAO] = TODAY()-1)",
              "",
              "RETURN",
              "",
              "DIVIDE([qt_pedidos_entrada_filter_ontem],hora)"
            ],
            "formatString": "#,0",
            "lineageTag": "0681d902-796d-41a8-a577-84bc8eb7abcb"
          },
          {
            "name": "med_entrada_de_ped_semana_passada",
            "displayFolder": "Médias",
            "expression": [
              "",
              "",
              "VAR hora = ",
              "CALCULATE(",
              "    DISTINCTCOUNT(entrada[hora_da_integração]),",
              "    entrada[DATA DA INTEGRACAO] = TODAY()-7)",
              "",
              "RETURN",
              "",
              "DIVIDE([qt_pedidos_entrada_filter_semana_passada],hora)"
            ],
            "formatString": "#,0",
            "lineageTag": "b7ce397b-0c78-4f55-ae40-b56dcb5cd34b"
          },
          {
            "name": "qt_pecas_entrada",
            "displayFolder": "Quantidade de peças",
            "expression": [
              "SUM(entrada[QUANTIDADE DA MERCADORIA])",
              ""
            ],
            "formatString": "0",
            "lineageTag": "23a46d78-a345-4172-b3b5-01a2d4360da9"
          },
          {
            "name": "qt_pecas_faturamento",
            "displayFolder": "Quantidade de peças",
            "expression": "SUM(packed[Quantidade])",
            "formatString": "0",
            "lineageTag": "1467092b-e273-47d7-9a24-96ae38d7f52c"
          },
          {
            "name": "qt_pecas_entrada_filter_semana_passada",
            "displayFolder": "Quantidade de peças filtradas",
            "expression": [
              "",
              "CALCULATE(",
              "    [qt_pecas_entrada],",
              "    entrada[DATA DA INTEGRACAO] = TODAY()-7)"
            ],
            "formatString": "0",
            "lineageTag": "3d7ca587-fea6-487d-a86f-2cfcd2ae1474"
          },
          {
            "name": "qt_pecas_entrada_filter_ontem",
            "displayFolder": "Quantidade de peças filtradas",
            "expression": [
              "",
              "CALCULATE(",
              "    [qt_pecas_entrada],",
              "    entrada[DATA DA INTEGRACAO] = TODAY()-1)"
            ],
            "formatString": "0",
            "lineageTag": "2279046d-8285-4698-baca-143c2ddb9265"
          },
          {
            "name": "qt_pecas_entrada_filter_hoje",
            "displayFolder": "Quantidade de peças filtradas",
            "expression": [
              "",
              "CALCULATE(",
              "    [qt_pecas_entrada],",
              "    entrada[DATA DA INTEGRACAO] = TODAY())"
            ],
            "formatString": "0",
            "lineageTag": "37971dfb-bf9e-494c-b29b-567c1211c23b"
          },
          {
            "name": "qt_pecas_packed_filter_hoje",
            "displayFolder": "Quantidade de peças filtradas",
            "expression": [
              "",
              "CALCULATE(",
              "    [qt_pecas_faturamento],",
              "    packed[Data Packed] = TODAY())"
            ],
            "formatString": "0",
            "lineageTag": "d46343f2-7441-47b8-a8e1-048250f93acb"
          },
          {
            "name": "qt_pecas_packed_filter_ontem",
            "displayFolder": "Quantidade de peças filtradas",
            "expression": [
              "",
              "CALCULATE(",
              "    [qt_pecas_faturamento],",
              "    packed[Data Packed] = TODAY()-1)"
            ],
            "formatString": "0",
            "lineageTag": "5a5b2aa0-4ea6-43d3-a1a1-68603bb630bd"
          },
          {
            "name": "qt_pecas_packed_filter_semana_passada",
            "displayFolder": "Quantidade de peças filtradas",
            "expression": [
              "",
              "CALCULATE(",
              "    [qt_pecas_faturamento],",
              "    packed[Data Packed] = TODAY()-7)"
            ],
            "formatString": "0",
            "lineageTag": "96807f23-b72a-4821-b82b-0d8c5e8a0b98"
          },
          {
            "name": "p/p_semana_passada_entrada",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Pedidos / Peças",
            "expression": [
              "",
              "DIVIDE([qt_pecas_entrada_filter_semana_passada],[qt_pedidos_entrada_filter_semana_passada])"
            ],
            "lineageTag": "5e8ef704-e564-47f3-b26e-aa29b99af56b"
          },
          {
            "name": "p/p_ontem_entrada",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Pedidos / Peças",
            "expression": [
              "",
              "DIVIDE([qt_pecas_entrada_filter_ontem],[qt_pedidos_entrada_filter_ontem])"
            ],
            "lineageTag": "5ae1eb33-3042-4959-8db0-a64c01a43970"
          },
          {
            "name": "p/p_hoje_entrada",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Pedidos / Peças",
            "expression": [
              "",
              "DIVIDE([qt_pecas_entrada_filter_hoje],[qt_pedidos_entrada_filter_hoje])"
            ],
            "lineageTag": "a989f01f-b04a-46da-bc99-dcce1ada5cbb"
          },
          {
            "name": "p/p_semana_passada_fatura",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Pedidos / Peças",
            "expression": [
              "",
              "DIVIDE([qt_pecas_packed_filter_semana_passada],[qt_pedidos_packed_filter_semana_passada])"
            ],
            "lineageTag": "f8776a18-ba65-4103-97ef-50ed85f1a299"
          },
          {
            "name": "p/p_ontem_fatura",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Pedidos / Peças",
            "expression": [
              "",
              "DIVIDE([qt_pecas_packed_filter_ontem],[qt_pedidos_packed_filter_ontem])"
            ],
            "lineageTag": "f54f9f26-e986-424d-b6e2-4fa9c392a2f2"
          },
          {
            "name": "p/p_hoje_fatura",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Pedidos / Peças",
            "expression": [
              "",
              "DIVIDE([qt_pecas_packed_filter_hoje],[qt_pedidos_packed_filter_hoje])"
            ],
            "lineageTag": "2f799b71-e3a9-444b-9d74-c16338874496"
          },
          {
            "name": "igual_a_ultima_hora_d-7_ent_ped",
            "displayFolder": "Quantidade de pedidos filtragem de horas",
            "expression": [
              "",
              "CALCULATE([qt_pedidos_entrada_filter_semana_passada],",
              "    dHora[Hora Num] <= HOUR(NOW()))"
            ],
            "formatString": "#,0",
            "lineageTag": "657dcc44-5417-4aa7-9485-47c469bf3f85"
          },
          {
            "name": "igual_a_ultima_hora_ontem_ent_ped",
            "displayFolder": "Quantidade de pedidos filtragem de horas",
            "expression": [
              "",
              "CALCULATE([qt_pedidos_entrada_filter_ontem],",
              "    dHora[Hora Num] <= HOUR(NOW()))"
            ],
            "formatString": "#,0",
            "lineageTag": "8a1de2ce-3ffa-46a6-a6c9-67696f99e8b9"
          },
          {
            "name": "igual_a_ultima_hora_hoje_ent_ped",
            "displayFolder": "Quantidade de pedidos filtragem de horas",
            "expression": [
              "",
              "CALCULATE([qt_pedidos_entrada_filter_hoje],",
              "    dHora[Hora Num] <= HOUR(NOW()))"
            ],
            "formatString": "#,0",
            "lineageTag": "76cfeeae-d242-4dba-b33f-d8f10f324770"
          },
          {
            "name": "igual_a_ultima_hora_d-7_ent_fat",
            "displayFolder": "Quantidade de pedidos filtragem de horas",
            "expression": [
              "",
              "CALCULATE([qt_pedidos_packed_filter_semana_passada],",
              "    dHora[Hora Num] <= HOUR(NOW()))"
            ],
            "formatString": "#,0",
            "lineageTag": "dac544a4-5307-4e11-aa15-b4152a08315e"
          },
          {
            "name": "igual_a_ultima_hora_ontem_ent_fat",
            "displayFolder": "Quantidade de pedidos filtragem de horas",
            "expression": [
              "",
              "",
              "CALCULATE([qt_pedidos_packed_filter_ontem],",
              "    dHora[Hora Num] <= HOUR(NOW()))",
              ""
            ],
            "formatString": "#,0",
            "lineageTag": "5729493c-b3b2-4fe7-9404-5d99b237cc8c"
          },
          {
            "name": "igual_a_ultima_hora_hoje_ent_fat",
            "displayFolder": "Quantidade de pedidos filtragem de horas",
            "expression": [
              "",
              "CALCULATE([qt_pedidos_packed_filter_hoje],",
              "    dHora[Hora Num] <= HOUR(NOW()))"
            ],
            "formatString": "#,0",
            "lineageTag": "ff82c54a-68c4-4241-b745-dbffb3342d37"
          },
          {
            "name": "qtd_pedidos_carteira_vencidos_br",
            "displayFolder": "CARTEIRA\\BR",
            "expression": [
              "",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[status] = \"vencidos\",",
              "carteira[TRANSP]=\"BR\",",
              "carteira[ROTA] <> \"SP1976\")",
              "",
              "VAR formata = ",
              "",
              "IF(ISBLANK(logica),\"0\",logica)",
              "RETURN",
              "",
              "formata",
              ""
            ],
            "formatString": "0",
            "lineageTag": "46e7a75f-a909-4c49-841b-b9a509ad6172"
          },
          {
            "name": "qtd_pedidos_carteira_vence_hoje_br",
            "displayFolder": "CARTEIRA\\BR",
            "expression": [
              "",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[status] = \"Vence Hoje\" || carteira[status] = \"Vence Segunda\",",
              "carteira[TRANSP]=\"BR\",",
              "carteira[ROTA] <> \"SP1976\")",
              "",
              "VAR formata = ",
              "",
              "IF(ISBLANK(logica),\"0\",logica)",
              "RETURN",
              "",
              "formata"
            ],
            "formatString": "#,0",
            "lineageTag": "b9855daa-217c-4613-b62e-f04daf542342"
          },
          {
            "name": "qtd_pedidos_carteira_d+1_br",
            "displayFolder": "CARTEIRA\\BR",
            "expression": [
              "",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[status] = \"D+1\",",
              "carteira[TRANSP] = \"BR\",",
              "carteira[ROTA] <> \"SP1976\")",
              "",
              "VAR formata = ",
              "",
              "IF(ISBLANK(logica),\"0\",logica)",
              "RETURN",
              "",
              "formata"
            ],
            "formatString": "#,0",
            "lineageTag": "3c9c65d8-bdd8-448b-a0f2-e310ffda6219"
          },
          {
            "name": "qtd_pedidos_carteira_d+2_br",
            "displayFolder": "CARTEIRA\\BR",
            "expression": [
              "",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[status] = \" >D+2\" || carteira[status] = \"D+2\",",
              "carteira[TRANSP]=\"BR\",",
              "carteira[ROTA] <> \"SP1976\")",
              "",
              "VAR formata = ",
              "",
              "IF(ISBLANK(logica),\"0\",logica)",
              "RETURN",
              "",
              "formata"
            ],
            "formatString": "#,0",
            "lineageTag": "136516bd-2032-455f-9ae3-138f762d2726"
          },
          {
            "name": "qtd_pedidos_carteira_all_br",
            "displayFolder": "CARTEIRA\\BR",
            "expression": [
              "",
              "",
              "[qtd_pedidos_carteira_d+1_br]+[qtd_pedidos_carteira_d+2_br]+[qtd_pedidos_carteira_vence_hoje_br]+[qtd_pedidos_carteira_vencidos_br]"
            ],
            "formatString": "#,0",
            "lineageTag": "5f0672d9-10a4-4f60-999c-3e0aa6cba8db"
          },
          {
            "name": "qtd_pedidos_carteira_all_vvlog",
            "displayFolder": "CARTEIRA\\VVLOG",
            "expression": [
              "",
              "",
              "[qtd_pedidos_carteira_d+1_vvlog]+[qtd_pedidos_carteira_d+2_vvlog]+[qtd_pedidos_carteira_vence_hoje_vvlog]+[qtd_pedidos_carteira_vencidos_br]"
            ],
            "formatString": "#,0",
            "lineageTag": "b52e437f-829d-461e-ad72-fa1bba417d86"
          },
          {
            "name": "qtd_pedidos_carteira_vencidos_vvlog",
            "displayFolder": "CARTEIRA\\VVLOG",
            "expression": [
              "",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[status] = \"vencidos\",",
              "carteira[TRANSP]=\"VVLOG\",",
              "carteira[ROTA] <> \"SP1976\")",
              "",
              "VAR formata = ",
              "",
              "IF(ISBLANK(logica),\"0\",logica)",
              "RETURN",
              "",
              "formata"
            ],
            "formatString": "#,0",
            "lineageTag": "e0ed36f5-8b7b-443b-9f57-9daeb7519360"
          },
          {
            "name": "qtd_pedidos_carteira_vence_hoje_vvlog",
            "displayFolder": "CARTEIRA\\VVLOG",
            "expression": [
              "",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[status] = \"Vence Hoje\" || carteira[status] = \"Vence Segunda\",",
              "carteira[TRANSP]=\"VVLOG\",",
              "carteira[ROTA] <> \"SP1976\")",
              "",
              "VAR formata = ",
              "",
              "IF(ISBLANK(logica),\"0\",logica)",
              "RETURN",
              "",
              "formata"
            ],
            "formatString": "#,0",
            "lineageTag": "ac51e1dc-722c-4c31-8f4d-cf788edc0795"
          },
          {
            "name": "qtd_pedidos_carteira_d+1_vvlog",
            "displayFolder": "CARTEIRA\\VVLOG",
            "expression": [
              "",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[status] = \"D+1\",",
              "carteira[TRANSP] = \"VVLOG\",",
              "carteira[ROTA] <> \"SP1976\")",
              "",
              "VAR formata = ",
              "",
              "IF(ISBLANK(logica),\"0\",logica)",
              "RETURN",
              "",
              "formata"
            ],
            "formatString": "#,0",
            "lineageTag": "15ce7d42-6f7c-46c5-b9eb-f0512e621baa"
          },
          {
            "name": "qtd_pedidos_carteira_d+2_vvlog",
            "displayFolder": "CARTEIRA\\VVLOG",
            "expression": [
              "",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[status] = \"D+2\" || carteira[status] = \" >D+2\",",
              "carteira[TRANSP]=\"VVLOG\",",
              "carteira[ROTA] <> \"SP1976\")",
              "",
              "VAR formata = ",
              "",
              "IF(ISBLANK(logica),\"0\",logica)",
              "RETURN",
              "",
              "formata"
            ],
            "formatString": "#,0",
            "lineageTag": "3ff1ad8d-a72b-4297-89fc-0d0f1dd3037d"
          },
          {
            "name": "created_em_separacao_<>_vvlog_vencidos",
            "displayFolder": "Campo de Tabela\\Campo BR\\Vencidos",
            "expression": [
              "",
              "",
              "VAR logica = ",
              "CALCULATE(",
              "    [qt_pedidos_olpn],",
              "    'status oLPN'[Rota] <> \"VVLOG\",",
              "    'status oLPN'[Etapa] = \"Created - Em Separação\",",
              "    'status oLPN'[status] = \"Vencidos\",",
              "    'status oLPN'[descricao_atividade] <> \"06_Fim de Separação\")",
              "",
              "RETURN",
              "IF(ISBLANK(logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "87b32574-df75-4fb2-a1c1-3a8068863230"
          },
          {
            "name": "created_fim_de_separacao_<>_vvlog_vencidos",
            "displayFolder": "Campo de Tabela\\Campo BR\\Vencidos",
            "expression": [
              "",
              "",
              "VAR logica = ",
              "CALCULATE(",
              "    [qt_pedidos_olpn],",
              "    'status oLPN'[Rota] <> \"VVLOG\",",
              "    'status oLPN'[status] = \"Vencidos\",",
              "    'status oLPN'[descricao_atividade] = \"06_Fim de Separação\")",
              "",
              "RETURN",
              "IF(ISBLANK(logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "d889af9e-dd3a-4d77-a2bd-62d81f510a91"
          },
          {
            "name": "packed_s_gaiola_em_faturamento_<>_vvlog_vencidos",
            "displayFolder": "Campo de Tabela\\Campo BR\\Vencidos",
            "expression": [
              "",
              "",
              "VAR logica = ",
              "CALCULATE(",
              "    [qt_pedidos_olpn],",
              "    'status oLPN'[Rota] <> \"VVLOG\",",
              "    'status oLPN'[Etapa] = \"Packed S. Gaiola - Em Faturamento\",",
              "    'status oLPN'[status] = \"Vencidos\",",
              "    'status oLPN'[descricao_atividade] <> \"06_Fim de Separação\")",
              "",
              "RETURN",
              "IF(ISBLANK(logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "4683cfe6-8228-4cc9-832d-8834de3f5316"
          },
          {
            "name": "created_em_separacao_<>_vvlog_vence_hoje",
            "displayFolder": "Campo de Tabela\\Campo BR\\Vence Hoje",
            "expression": [
              "",
              "",
              "VAR logica = ",
              "CALCULATE(",
              "    [qt_pedidos_olpn],",
              "    'status oLPN'[Rota] = \"BR\",",
              "    'status oLPN'[Etapa] = \"Created - Em Separação\",",
              "    'status oLPN'[status] = \"Vence Hoje\" || 'status oLPN'[status] = \"Vence Segunda\",",
              "    'status oLPN'[descricao_atividade] <> \"06_Fim de Separação\")",
              "",
              "RETURN",
              "IF(ISBLANK(logica),\"0\",logica)"
            ],
            "formatString": "0",
            "lineageTag": "824a2e4e-fc50-44ba-8a8d-3a572045387a"
          },
          {
            "name": "created_fim_de_separacao_<>_vvlog_vence_hoje",
            "displayFolder": "Campo de Tabela\\Campo BR\\Vence Hoje",
            "expression": [
              "",
              "",
              "VAR logica = ",
              "CALCULATE(",
              "    [qt_pedidos_olpn],",
              "    'status oLPN'[Rota] = \"BR\",",
              "    'status oLPN'[status] = \"Vence Hoje\" || 'status oLPN'[status] = \"Vence Segunda\",",
              "    'status oLPN'[descricao_atividade] = \"06_Fim de Separação\")",
              "",
              "RETURN",
              "IF(ISBLANK(logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "83b69ba0-56e1-4e9b-b32b-438adc516f71"
          },
          {
            "name": "packed_s_gaiola_em_faturamento_<>_vvlog_vence_hoje",
            "displayFolder": "Campo de Tabela\\Campo BR\\Vence Hoje",
            "expression": [
              "",
              "",
              "VAR logica = ",
              "CALCULATE(",
              "    [qt_pedidos_olpn],",
              "    'status oLPN'[Rota] = \"BR\",",
              "    'status oLPN'[Etapa] = \"Packed S. Gaiola - Em Faturamento\",",
              "    'status oLPN'[status] = \"Vence Hoje\" || 'status oLPN'[status] = \"Vence Segunda\")",
              "",
              "RETURN",
              "IF(ISBLANK(logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "3d38e344-412f-4ede-bc85-aae386eb2f2c"
          },
          {
            "name": "created_em_separacao_<>_vvlog_d+1",
            "displayFolder": "Campo de Tabela\\Campo BR\\D+1",
            "expression": [
              "",
              "",
              "VAR logica = ",
              "CALCULATE(",
              "    [qt_pedidos_olpn],",
              "    'status oLPN'[Rota] <> \"VVLOG\",",
              "    'status oLPN'[Etapa] = \"Created - Em Separação\",",
              "    'status oLPN'[status] = \"D+1\",",
              "    'status oLPN'[descricao_atividade] <> \"06_Fim de Separação\")",
              "",
              "RETURN",
              "IF(ISBLANK(logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "3849804c-55d6-459d-b933-8122a8131f21"
          },
          {
            "name": "created_fim_de_separacao_<>_vvlog_d+1",
            "displayFolder": "Campo de Tabela\\Campo BR\\D+1",
            "expression": [
              "",
              "",
              "VAR logica = ",
              "CALCULATE(",
              "    [qt_pedidos_olpn],",
              "    'status oLPN'[Rota] <> \"VVLOG\",",
              "",
              "    'status oLPN'[status] = \"D+1\",",
              "    'status oLPN'[descricao_atividade] = \"06_Fim de Separação\")",
              "",
              "RETURN",
              "IF(ISBLANK(logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "a68cd2e0-11a3-44bc-8dd3-e7dedfb159bc"
          },
          {
            "name": "packed_s_gaiola_em_faturamento_<>_d+1_<>_vvlog",
            "displayFolder": "Campo de Tabela\\Campo BR\\D+1",
            "expression": [
              "",
              "",
              "VAR logica = ",
              "CALCULATE(",
              "    [qt_pedidos_olpn],",
              "    'status oLPN'[Rota] <> \"VVLOG\",",
              "    'status oLPN'[Etapa] = \"Packed S. Gaiola - Em Faturamento\",",
              "    'status oLPN'[status] = \"D+1\",",
              "    'status oLPN'[descricao_atividade] <> \"06_Fim de Separação\")",
              "",
              "RETURN",
              "IF(ISBLANK(logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "cad7adae-838c-4b7b-af25-777b4c631d21"
          },
          {
            "name": "created_em_separacao_<>_vvlog_d+2",
            "displayFolder": "Campo de Tabela\\Campo BR\\D+2",
            "expression": [
              "",
              "",
              "VAR logica = ",
              "CALCULATE(",
              "    [qt_pedidos_olpn],",
              "    'status oLPN'[Rota] <> \"VVLOG\",",
              "    'status oLPN'[Etapa] = \"Created - Em Separação\",",
              "    'status oLPN'[status] = \"D+2\" || 'status oLPN'[status] = \" >D+2\",",
              "    'status oLPN'[descricao_atividade] <> \"06_Fim de Separação\")",
              "",
              "RETURN",
              "IF(ISBLANK(logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "b0d5db07-299f-4823-95d9-26497f660827"
          },
          {
            "name": "created_fim_de_separacao_<>_vvlog_d+2",
            "displayFolder": "Campo de Tabela\\Campo BR\\D+2",
            "expression": [
              "",
              "",
              "VAR logica = ",
              "CALCULATE(",
              "    [qt_pedidos_olpn],",
              "    'status oLPN'[Rota] <> \"VVLOG\",",
              "    'status oLPN'[status] = \" >D+2\" || 'status oLPN'[status] = \"D+2\",",
              "    'status oLPN'[descricao_atividade] = \"06_Fim de Separação\")",
              "",
              "RETURN",
              "IF(ISBLANK(logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "98ceba7c-77f3-4e1e-892c-f4398785cabc"
          },
          {
            "name": "packed_s_gaiola_em_faturamento_<>_d+2_<>_vvlog",
            "displayFolder": "Campo de Tabela\\Campo BR\\D+2",
            "expression": [
              "",
              "",
              "VAR logica = ",
              "CALCULATE(",
              "    [qt_pedidos_olpn],",
              "    'status oLPN'[Rota] <> \"VVLOG\",",
              "    'status oLPN'[Etapa] = \"Packed S. Gaiola - Em Faturamento\",",
              "    'status oLPN'[status] = \" >D+2\" || 'status oLPN'[status] = \"D+2\",",
              "    'status oLPN'[descricao_atividade] <> \"06_Fim de Separação\")",
              "",
              "RETURN",
              "IF(ISBLANK(logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "c7012177-adef-4c11-9459-0cc2cd75182f"
          },
          {
            "name": "saldo_created_em_separacao_br",
            "displayFolder": "Campo de Tabela\\Campo BR\\Saldo",
            "expression": [
              "",
              "[created_em_separacao_<>_vvlog_d+1]+[created_em_separacao_<>_vvlog_d+2]+[created_em_separacao_<>_vvlog_vence_hoje]+[created_em_separacao_<>_vvlog_vencidos]"
            ],
            "formatString": "#,0",
            "lineageTag": "d6c138f6-dc3e-4e9c-b243-7388d6a93ca9"
          },
          {
            "name": "saldo_created_fim_de_separacao_br",
            "displayFolder": "Campo de Tabela\\Campo BR\\Saldo",
            "expression": [
              "",
              "[created_fim_de_separacao_<>_vvlog_d+1]+[created_fim_de_separacao_<>_vvlog_d+2]+[created_fim_de_separacao_<>_vvlog_vence_hoje]+[created_fim_de_separacao_<>_vvlog_vencidos]"
            ],
            "formatString": "#,0",
            "lineageTag": "f4c6e31e-98f4-4f68-9427-39d646dfeaed"
          },
          {
            "name": "saldo_packed_s_gaiola_em_faturamento_br",
            "displayFolder": "Campo de Tabela\\Campo BR\\Saldo",
            "expression": [
              "",
              "[packed_s_gaiola_em_faturamento_<>_d+1_<>_vvlog]+[packed_s_gaiola_em_faturamento_<>_d+2_<>_vvlog]+[packed_s_gaiola_em_faturamento_<>_vvlog_vence_hoje]+[packed_s_gaiola_em_faturamento_<>_vvlog_vencidos]"
            ],
            "formatString": "#,0",
            "lineageTag": "a909bb47-b4f4-496e-8d9f-c04c96ba0bfd"
          },
          {
            "name": "created_em_separacao_<>_br_vencidos",
            "displayFolder": "Campo de Tabela\\Campo VVLOG\\Vencidos",
            "expression": [
              "",
              "",
              "VAR logica = ",
              "CALCULATE(",
              "    [qt_pedidos_olpn],",
              "    'status oLPN'[Rota] <> \"BR\",",
              "    'status oLPN'[Etapa] = \"Created - Em Separação\",",
              "    'status oLPN'[status] = \"Vencidos\",",
              "    'status oLPN'[descricao_atividade] <> \"06_Fim de Separação\")",
              "",
              "RETURN",
              "IF(ISBLANK(logica),\"0\",logica)"
            ],
            "formatString": "0",
            "lineageTag": "1a488819-cfae-4ab7-9758-42d2004a5de7"
          },
          {
            "name": "created_fim_de_separacao_<>_br_vencidos",
            "displayFolder": "Campo de Tabela\\Campo VVLOG\\Vencidos",
            "expression": [
              "",
              "",
              "VAR logica = ",
              "CALCULATE(",
              "    [qt_pedidos_olpn],",
              "    'status oLPN'[Rota] <> \"BR\",",
              "    'status oLPN'[status] = \"Vencidos\",",
              "    'status oLPN'[descricao_atividade] = \"06_Fim de Separação\")",
              "",
              "RETURN",
              "IF(ISBLANK(logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "cd8e4913-8f9b-46cc-918c-cb1ee298f9fe"
          },
          {
            "name": "packed_s_gaiola_em_faturamento_<>_br_vencidos",
            "displayFolder": "Campo de Tabela\\Campo VVLOG\\Vencidos",
            "expression": [
              "",
              "",
              "VAR logica = ",
              "CALCULATE(",
              "    [qt_pedidos_olpn],",
              "    'status oLPN'[Rota] <> \"BR\",",
              "    'status oLPN'[Etapa] = \"Packed S. Gaiola - Em Faturamento\",",
              "    'status oLPN'[status] = \"Vencidos\",",
              "    'status oLPN'[descricao_atividade] <> \"06_Fim de Separação\")",
              "",
              "RETURN",
              "IF(ISBLANK(logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "8d423089-78e8-4095-8b14-fe08da62b7f3"
          },
          {
            "name": "created_em_separacao_<>_br_vence_hoje",
            "displayFolder": "Campo de Tabela\\Campo VVLOG\\Vence Hoje",
            "expression": [
              "",
              "",
              "VAR logica = ",
              "CALCULATE(",
              "    [qt_pedidos_olpn],",
              "    'status oLPN'[Rota] <> \"BR\",",
              "    'status oLPN'[Etapa] = \"Created - Em Separação\",",
              "    'status oLPN'[status] = \"Vence Hoje\" || 'status oLPN'[status] = \"Vence Segunda\" ,",
              "    'status oLPN'[descricao_atividade] <> \"06_Fim de Separação\")",
              "",
              "RETURN",
              "IF(ISBLANK(logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "b4fff71b-f942-4139-a119-8665a102a2a2"
          },
          {
            "name": "created_fim_de_separacao_<>_br_vence_hoje",
            "displayFolder": "Campo de Tabela\\Campo VVLOG\\Vence Hoje",
            "expression": [
              "",
              "",
              "VAR logica = ",
              "CALCULATE(",
              "    [qt_pedidos_olpn],",
              "    'status oLPN'[Rota] <> \"BR\",",
              "    'status oLPN'[status] = \"Vence Hoje\" || 'status oLPN'[status] = \"Vence Segunda\" ,",
              "    'status oLPN'[descricao_atividade] = \"06_Fim de Separação\")",
              "",
              "RETURN",
              "IF(ISBLANK(logica),\"0\",logica)"
            ],
            "formatString": "0",
            "lineageTag": "db7b001f-cf8e-43a1-852f-a539da33d4e5"
          },
          {
            "name": "packed_s_gaiola_em_faturamento_<>_br_vence_hoje",
            "displayFolder": "Campo de Tabela\\Campo VVLOG\\Vence Hoje",
            "expression": [
              "",
              "",
              "VAR logica = ",
              "CALCULATE(",
              "    [qt_pedidos_olpn],",
              "    'status oLPN'[Rota] <> \"BR\",",
              "    'status oLPN'[Etapa] = \"Packed S. Gaiola - Em Faturamento\",",
              "    'status oLPN'[status] = \"Vence Hoje\" || 'status oLPN'[status] = \"Vence Segunda\",",
              "    'status oLPN'[descricao_atividade] <> \"06_Fim de Separação\")",
              "",
              "RETURN",
              "IF(ISBLANK(logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "451306ce-95ae-44f6-ada9-a3407d75af49"
          },
          {
            "name": "created_em_separacao_<>_br_d+1",
            "displayFolder": "Campo de Tabela\\Campo VVLOG\\D+1",
            "expression": [
              "",
              "",
              "VAR logica = ",
              "CALCULATE(",
              "    [qt_pedidos_olpn],",
              "    'status oLPN'[Rota] <> \"BR\",",
              "    'status oLPN'[Etapa] = \"Created - Em Separação\",",
              "    'status oLPN'[status] = \"D+1\",",
              "    'status oLPN'[descricao_atividade] <> \"06_Fim de Separação\")",
              "",
              "RETURN",
              "IF(ISBLANK(logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "c141725e-310f-4004-87ce-cb937ecd9a47"
          },
          {
            "name": "created_fim_de_separacao_<>_br_d+1",
            "displayFolder": "Campo de Tabela\\Campo VVLOG\\D+1",
            "expression": [
              "",
              "",
              "VAR logica = ",
              "CALCULATE(",
              "    [qt_pedidos_olpn],",
              "    'status oLPN'[Rota] <> \"BR\",",
              "    'status oLPN'[status] = \"D+1\",",
              "    'status oLPN'[descricao_atividade] = \"06_Fim de Separação\")",
              "",
              "RETURN",
              "IF(ISBLANK(logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "c9af5dc2-cc93-49e3-9703-ced3163f5dd5"
          },
          {
            "name": "packed_s_gaiola_em_faturamento_<>_d+1_<>_br",
            "displayFolder": "Campo de Tabela\\Campo VVLOG\\D+1",
            "expression": [
              "",
              "",
              "VAR logica = ",
              "CALCULATE(",
              "    [qt_pedidos_olpn],",
              "    'status oLPN'[Rota] <> \"BR\",",
              "    'status oLPN'[Etapa] = \"Packed S. Gaiola - Em Faturamento\",",
              "    'status oLPN'[status] = \"D+1\",",
              "    'status oLPN'[descricao_atividade] <> \"06_Fim de Separação\")",
              "",
              "RETURN",
              "IF(ISBLANK(logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "286c910a-f1b2-4607-9f3b-bc3019f87a46"
          },
          {
            "name": "created_em_separacao_<>_br_d+2",
            "displayFolder": "Campo de Tabela\\Campo VVLOG\\D+2",
            "expression": [
              "",
              "",
              "VAR logica = ",
              "CALCULATE(",
              "    [qt_pedidos_olpn],",
              "    'status oLPN'[Rota] <> \"BR\",",
              "    'status oLPN'[Etapa] = \"Created - Em Separação\",",
              "    'status oLPN'[status] = \" >D+2\" || 'status oLPN'[status] = \"D+2\" ,",
              "    'status oLPN'[descricao_atividade] <> \"06_Fim de Separação\")",
              "",
              "RETURN",
              "IF(ISBLANK(logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "7c8ee33f-2c47-46f4-9539-dcd01a813349"
          },
          {
            "name": "created_fim_de_separacao_<>_br_d+2",
            "displayFolder": "Campo de Tabela\\Campo VVLOG\\D+2",
            "expression": [
              "",
              "",
              "VAR logica = ",
              "CALCULATE(",
              "    [qt_pedidos_olpn],",
              "    'status oLPN'[Rota] <> \"BR\",",
              "    'status oLPN'[status] = \" >D+2\" || 'status oLPN'[status] = \"D+2\",",
              "    'status oLPN'[descricao_atividade] = \"06_Fim de Separação\")",
              "",
              "RETURN",
              "IF(ISBLANK(logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "f19def6c-fa8d-40f3-94df-ad36ae46457c"
          },
          {
            "name": "packed_s_gaiola_em_faturamento_<>_d+2_<>_br",
            "displayFolder": "Campo de Tabela\\Campo VVLOG\\D+2",
            "expression": [
              "",
              "",
              "VAR logica = ",
              "CALCULATE(",
              "    [qt_pedidos_olpn],",
              "    'status oLPN'[Rota] <> \"BR\",",
              "    'status oLPN'[Etapa] = \"Packed S. Gaiola - Em Faturamento\",",
              "    'status oLPN'[status] = \" >D+2\" || 'status oLPN'[status] = \"D+2\",",
              "    'status oLPN'[descricao_atividade] <> \"06_Fim de Separação\")",
              "",
              "RETURN",
              "IF(ISBLANK(logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "34871de8-e61b-465f-9776-11c6e3d4c65a"
          },
          {
            "name": "saldo_created_em_separacao_vvlog",
            "displayFolder": "Campo de Tabela\\Campo VVLOG\\Saldo",
            "expression": [
              "",
              "[created_em_separacao_<>_br_d+1]+[created_em_separacao_<>_br_d+2]+[created_em_separacao_<>_br_vence_hoje]+[created_em_separacao_<>_br_vencidos]"
            ],
            "formatString": "#,0",
            "lineageTag": "541f8be5-53c1-4e3d-a6c2-fd086ee13ce3"
          },
          {
            "name": "saldo_created_fim_de_separacao_vvlog",
            "displayFolder": "Campo de Tabela\\Campo VVLOG\\Saldo",
            "expression": [
              "",
              "[created_fim_de_separacao_<>_br_d+1]+[created_fim_de_separacao_<>_br_d+2]+[created_fim_de_separacao_<>_br_vence_hoje]+[created_fim_de_separacao_<>_br_vencidos]"
            ],
            "formatString": "#,0",
            "lineageTag": "a639e92e-f491-4de2-ab4b-2e2119fcc23d"
          },
          {
            "name": "saldo_packed_s_gaiola_em_faturamento_vvlog",
            "displayFolder": "Campo de Tabela\\Campo VVLOG\\Saldo",
            "expression": [
              "",
              "[packed_s_gaiola_em_faturamento_<>_d+1_<>_br]+[packed_s_gaiola_em_faturamento_<>_d+2_<>_br]+[packed_s_gaiola_em_faturamento_<>_br_vence_hoje]+[packed_s_gaiola_em_faturamento_<>_br_vencidos]"
            ],
            "formatString": "0",
            "lineageTag": "44f88537-9bbe-4a52-bca5-3e5aa2be6d77"
          },
          {
            "name": "all_vencidos_br",
            "displayFolder": "Colunas verticais",
            "expression": [
              "",
              "",
              "[created_em_separacao_<>_vvlog_vencidos]+",
              "[created_fim_de_separacao_<>_vvlog_vencidos]+",
              "[packed_s_gaiola_em_faturamento_<>_vvlog_vencidos]+",
              "[qtd_pedidos_carteira_vencidos_br]+",
              "[released_vencidos<>vvlog]",
              ""
            ],
            "formatString": "#,0",
            "lineageTag": "3fa07d24-9c22-4049-afff-a5e2e1cb3634"
          },
          {
            "name": "all_vencidos_vvlog",
            "displayFolder": "Colunas verticais",
            "expression": [
              "",
              "",
              "[created_em_separacao_<>_br_vencidos]+",
              "[created_fim_de_separacao_<>_br_vencidos]+",
              "[packed_s_gaiola_em_faturamento_<>_br_vencidos]+",
              "[qtd_pedidos_carteira_vencidos_vvlog]+",
              "[released_vencidos_<>br]"
            ],
            "formatString": "#,0",
            "lineageTag": "c2fe86c9-d37a-45ec-acce-9f30b39d8db0"
          },
          {
            "name": "all_vence_hoje_br",
            "displayFolder": "Colunas verticais",
            "expression": [
              "",
              "[created_em_separacao_<>_vvlog_vence_hoje]+",
              "[created_fim_de_separacao_<>_vvlog_vence_hoje]+",
              "[packed_s_gaiola_em_faturamento_<>_vvlog_vence_hoje]+",
              "[released_vence_hoje<>vvlog]+",
              "[qtd_pedidos_carteira_vence_hoje_br]"
            ],
            "formatString": "0",
            "lineageTag": "a8bd880e-62fe-4be0-a679-be743011b09e"
          },
          {
            "name": "all_vence_hoje_vvlog",
            "displayFolder": "Colunas verticais",
            "expression": [
              "",
              "[created_em_separacao_<>_br_vence_hoje]+",
              "[created_fim_de_separacao_<>_br_vence_hoje]+",
              "[packed_s_gaiola_em_faturamento_<>_br_vence_hoje]+",
              "[released_vence_hoje_<>br]+",
              "[qtd_pedidos_carteira_vence_hoje_vvlog]"
            ],
            "formatString": "0",
            "lineageTag": "438a1e00-0fa6-4ff4-b50d-0c88c2105d88"
          },
          {
            "name": "all_d+1_br",
            "displayFolder": "Colunas verticais",
            "expression": [
              "",
              "[created_em_separacao_<>_vvlog_d+1]+",
              "[created_fim_de_separacao_<>_vvlog_d+1]+",
              "[packed_s_gaiola_em_faturamento_<>_d+1_<>_vvlog]+",
              "[qtd_pedidos_carteira_d+1_br]+",
              "[released_d+1_<>vvlog]"
            ],
            "formatString": "0",
            "lineageTag": "b2aa2dd0-9a16-46c1-9f72-5a227908f43c"
          },
          {
            "name": "all_d+1_vvlog",
            "displayFolder": "Colunas verticais",
            "expression": [
              "",
              "[created_em_separacao_<>_br_d+1]+",
              "[created_fim_de_separacao_<>_br_d+1]+",
              "",
              "[packed_s_gaiola_em_faturamento_<>_d+1_<>_br]+",
              "[qtd_pedidos_carteira_d+1_vvlog]+",
              "[released_d+1_<>br]"
            ],
            "formatString": "#,0",
            "lineageTag": "c30560d0-31fa-4711-9ced-50797e0c0756"
          },
          {
            "name": "all_d+2_br",
            "displayFolder": "Colunas verticais",
            "expression": [
              "",
              "[created_em_separacao_<>_vvlog_d+2]+",
              "[created_fim_de_separacao_<>_vvlog_d+2]+",
              "[packed_s_gaiola_em_faturamento_<>_d+2_<>_vvlog]+",
              "[qtd_pedidos_carteira_d+2_br]+",
              "[released_d+2_<>vvlog]"
            ],
            "formatString": "#,0",
            "lineageTag": "44b8f858-eaca-4cf9-875f-305c0c4fd489"
          },
          {
            "name": "all_d+2_vvlog",
            "displayFolder": "Colunas verticais",
            "expression": [
              "",
              "[created_em_separacao_<>_br_d+2]+",
              "[created_fim_de_separacao_<>_br_d+2]+",
              "[packed_s_gaiola_em_faturamento_<>_d+2_<>_br]+",
              "[qtd_pedidos_carteira_d+2_vvlog]+",
              "[released_d+2_<>br]"
            ],
            "formatString": "0",
            "lineageTag": "ffa49b67-63e5-4f78-b8c3-9d5d6ead3d9c"
          },
          {
            "name": "total_fracionado_br",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Colunas verticais",
            "expression": [
              "",
              "[all_d+1_br]+",
              "[all_d+2_br]+",
              "[all_vence_hoje_br]+",
              "[all_vencidos_br]"
            ],
            "formatString": "0",
            "lineageTag": "bbc540d0-0172-42b8-a805-87699b1e1901"
          },
          {
            "name": "total_fracionado_vvlog",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Colunas verticais",
            "expression": [
              "",
              "[all_d+1_vvlog]+",
              "[all_d+2_vvlog]+",
              "[all_vence_hoje_vvlog]+",
              "[all_vencidos_vvlog]"
            ],
            "formatString": "0",
            "lineageTag": "f6875bb5-117c-47bb-a2bc-f7211761350d"
          },
          {
            "name": "total_all",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Colunas verticais\\Totais gerais",
            "expression": [
              "",
              "[total_fracionado_br]+",
              "[total_fracionado_vvlog]"
            ],
            "formatString": "#,0",
            "lineageTag": "6a2ab6cb-6fcd-433d-813c-a184fbff27c6"
          },
          {
            "name": "all_vencidos",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Colunas verticais\\Totais gerais",
            "expression": [
              "",
              "[all_vencidos_br]+",
              "[all_vencidos_vvlog]"
            ],
            "formatString": "#,0",
            "lineageTag": "75f5ea7b-7fdc-4f76-8999-802df1e7b492"
          },
          {
            "name": "all_vence_hoje",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Colunas verticais\\Totais gerais",
            "expression": [
              "",
              "[all_vence_hoje_br]+",
              "[all_vence_hoje_vvlog]"
            ],
            "formatString": "#,0",
            "lineageTag": "70540944-89bb-4cea-9043-d1ce23c1abba"
          },
          {
            "name": "all_d+1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Colunas verticais\\Totais gerais",
            "expression": [
              "",
              "[all_d+1_br]+",
              "[all_d+1_vvlog]"
            ],
            "formatString": "#,0",
            "lineageTag": "c8419d17-7706-42c1-a879-134f026b0803"
          },
          {
            "name": "all_d+2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Colunas verticais\\Totais gerais",
            "expression": [
              "",
              "[all_d+2_br]+",
              "[all_d+2_vvlog]"
            ],
            "formatString": "#,0",
            "lineageTag": "afe9f0cf-663f-4b5f-9965-01fd11a01f0f"
          },
          {
            "name": "percente_fracionado",
            "displayFolder": "Coluna Vertical - Porcentagem",
            "expression": [
              "",
              "DIVIDE([total_fracionado_br],[total_all])"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "5f9a5f38-433b-4811-a3e9-d5cec1c95404"
          },
          {
            "name": "percente_vvlog",
            "displayFolder": "Coluna Vertical - Porcentagem",
            "expression": [
              "",
              "DIVIDE([total_fracionado_vvlog],[total_all])"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "bb809fc5-c3ed-4f5e-a437-d57e2664cdd6"
          },
          {
            "name": "percentual_entrada_ontem",
            "displayFolder": "Coluna Vertical - Porcentagem",
            "expression": [
              "",
              "DIVIDE([qt_pedidos_entrada_filter_hoje],[qt_pedidos_entrada_filter_ontem])"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "af073f63-ef64-4015-bd5f-d05bcbd09a95"
          },
          {
            "name": "percentual_entrada_semana_passada",
            "displayFolder": "Coluna Vertical - Porcentagem",
            "expression": [
              "",
              "DIVIDE([qt_pedidos_entrada_filter_hoje],[qt_pedidos_entrada_filter_semana_passada])"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "85800dc5-d02b-4bc1-b4e2-04d033158cb3"
          },
          {
            "name": "percentual_saida_ontem",
            "displayFolder": "Coluna Vertical - Porcentagem",
            "expression": "DIVIDE([qt_pedidos_packed_filter_hoje],[qt_pedidos_packed_filter_ontem])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "a81d1fca-8f55-4171-b5fb-39d92e42b6c5"
          },
          {
            "name": "percentual_saida_semana_passada",
            "displayFolder": "Coluna Vertical - Porcentagem",
            "expression": [
              "",
              "DIVIDE([qt_pedidos_packed_filter_hoje],[qt_pedidos_packed_filter_semana_passada])"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "35a9e225-5eb2-4aa6-8c81-8fa06c0f045c"
          },
          {
            "name": "p/p_%_ontem",
            "displayFolder": "Coluna Vertical - Porcentagem",
            "expression": [
              "",
              "DIVIDE([p/p_hoje_entrada],[p/p_ontem_entrada])"
            ],
            "formatString": "0",
            "lineageTag": "9d4fa55d-ddb3-4549-8664-56e91264333c"
          },
          {
            "name": "p/p_%_semana_passada",
            "displayFolder": "Coluna Vertical - Porcentagem",
            "expression": "DIVIDE([p/p_hoje_entrada],[p/p_semana_passada_entrada])",
            "formatString": "0",
            "lineageTag": "877a12d1-8fab-4465-b9d9-2315b97de0b3"
          },
          {
            "name": "data1",
            "displayFolder": "Coluna Vertical - Carteira",
            "expression": "\"<= \" & VALUES(tTempo[data_atual]) - 1",
            "lineageTag": "62e61416-2915-4931-9be6-51161822e736"
          },
          {
            "name": "data2",
            "displayFolder": "Coluna Vertical - Carteira",
            "expression": "FORMAT(NOW(),\"dd/mm/yyyy\")",
            "lineageTag": "402e5530-393f-4897-b00b-6b0604d6b72c"
          },
          {
            "name": "data3",
            "displayFolder": "Coluna Vertical - Carteira",
            "expression": [
              "",
              "",
              "FORMAT(IF(",
              "    WEEKDAY(TODAY(), 1) = 6, ",
              "    TODAY() + 3, ",
              "    IF(",
              "        WEEKDAY(TODAY(), 1) = 7, ",
              "        TODAY() + 2, ",
              "        TODAY() + 1",
              "    )",
              "),\"dd/mm/yyyy\")",
              ""
            ],
            "lineageTag": "dbf17255-5538-48f6-ac25-dc80cba20a33"
          },
          {
            "name": "data4",
            "displayFolder": "Coluna Vertical - Carteira",
            "expression": [
              "",
              "FORMAT(IF(",
              "    WEEKDAY([data3], 1) = 6, ",
              "    [data3] + 3, ",
              "    IF(",
              "        WEEKDAY([data3], 1) = 7, ",
              "        [data3] + 2, ",
              "        [data3] + 1",
              "    )",
              "),\"dd/mm/yyyy\")",
              ""
            ],
            "lineageTag": "575a0ac2-3e41-4ec1-aa84-0dd02e0b6315"
          },
          {
            "name": "data5",
            "displayFolder": "Coluna Vertical - Carteira",
            "expression": [
              "",
              "FORMAT(",
              "IF(",
              "    WEEKDAY([data4], 1) = 6, ",
              "    [data4] + 3, ",
              "    IF(",
              "        WEEKDAY([data4], 1) = 7, ",
              "        [data4] + 2, ",
              "        [data4] + 1",
              "    )",
              "),\"dd/mm/yyyy\")"
            ],
            "lineageTag": "0d22f522-d0d2-4c51-ae1c-0f39cfb0e3af"
          },
          {
            "name": "data6",
            "displayFolder": "Coluna Vertical - Carteira",
            "expression": [
              "",
              "FORMAT(",
              "IF(",
              "    WEEKDAY([data5], 1) = 6, ",
              "    [data5] + 3, ",
              "    IF(",
              "        WEEKDAY([data5], 1) = 7, ",
              "        [data5] + 2, ",
              "        [data5] + 1",
              "    )",
              "),\"dd/mm/yyyy\")",
              ""
            ],
            "lineageTag": "e54f9e0b-a414-4574-b13a-6e2bb1d32b8b"
          },
          {
            "name": "data7",
            "displayFolder": "Coluna Vertical - Carteira",
            "expression": [
              "FORMAT(",
              "IF(",
              "    WEEKDAY([data6], 1) = 6, ",
              "    [data6] + 3, ",
              "    IF(",
              "        WEEKDAY([data6], 1) = 7, ",
              "        [data6] + 2, ",
              "        [data6] + 1",
              "    )",
              "),\"dd/mm/yyyy\")",
              ""
            ],
            "lineageTag": "cfa5d2f6-73da-4f68-aa5d-5519b1694ca6"
          },
          {
            "name": "data8",
            "displayFolder": "Coluna Vertical - Carteira",
            "expression": [
              "",
              "",
              "\">=\" & FORMAT(",
              "    IF(",
              "        WEEKDAY([data7], 1) = 6, ",
              "        [data7] + 3, ",
              "        IF(",
              "            WEEKDAY([data7], 1) = 7, ",
              "            [data7] + 2, ",
              "            [data7] + 1",
              "        )",
              "    ),",
              "    \"dd/mm/yyyy\"",
              ")",
              ""
            ],
            "lineageTag": "3c758f95-7871-4fd4-aff5-ab7541444077"
          },
          {
            "name": "v_cel_c1_l1",
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "TODAY() - 1",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP1989\",",
              "carteira[status] = \"Vencidos\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "d58f4bf7-7f18-4ae9-bbc3-ba51fe3169e3"
          },
          {
            "name": "v_cel_c1_l18",
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "TODAY() - 1",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2938\",",
              "carteira[status] = \"Vencidos\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "fc84c312-3afc-479e-8fba-f92418c7b447"
          },
          {
            "name": "v_cel_c1_l2",
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "TODAY() - 1",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2023\",",
              "carteira[status] = \"Vencidos\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "d4b3c213-bbea-48fe-9350-c668ae1c9c86"
          },
          {
            "name": "v_cel_c1_l3",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "TODAY() - 1",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2027\",",
              "carteira[status] = \"Vencidos\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "2c071ba0-b8f6-4b85-8f00-5f5fafe3fd3a"
          },
          {
            "name": "v_cel_c1_l4",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "TODAY() - 1",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2869\",",
              "carteira[status] = \"Vencidos\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "bfd5fbc4-f3f5-4fd3-8a07-529178ee462c"
          },
          {
            "name": "v_cel_c1_l5",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "TODAY() - 1",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2870\",",
              "carteira[status] = \"Vencidos\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "04118e4a-012e-495b-b891-7135cc958e48"
          },
          {
            "name": "v_cel_c1_l6",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "TODAY() - 1",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2871\",",
              "carteira[status] = \"Vencidos\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "686bd9fa-d4ab-4790-8776-6f2fce7224b4"
          },
          {
            "name": "v_cel_c1_l7",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "TODAY() - 1",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2872\",",
              "carteira[status] = \"Vencidos\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "344af945-bdc9-4880-88f6-d9d51aeeb2ab"
          },
          {
            "name": "v_cel_c1_l8",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "TODAY() - 1",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2873\",",
              "carteira[status] = \"Vencidos\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "12bfa2e7-834f-458c-b39b-e7c704c657e2"
          },
          {
            "name": "v_cel_c1_l9",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "TODAY() - 1",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2874\",",
              "carteira[status] = \"Vencidos\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "0a46fa44-c189-4d53-9494-e053d0494c19"
          },
          {
            "name": "v_cel_c1_l10",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "TODAY() - 1",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2875\",",
              "carteira[status] = \"Vencidos\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "8003e5ae-a526-4852-8718-8c7902e7d404"
          },
          {
            "name": "v_cel_c1_l11",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "TODAY() - 1",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2894\",",
              "carteira[status] = \"Vencidos\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "2bec1dd8-2061-46d1-bcca-e8bcc33f1016"
          },
          {
            "name": "v_cel_c1_l12",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "TODAY() - 1",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2895\",",
              "carteira[status] = \"Vencidos\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "6832645d-83b4-4ca7-8fac-135f3839b3ea"
          },
          {
            "name": "v_cel_c1_l13",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "TODAY() - 1",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2896\",",
              "carteira[status] = \"Vencidos\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "77b3dd15-7722-46b5-86ae-aa4cba8f716d"
          },
          {
            "name": "v_cel_c1_l14",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "TODAY() - 1",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2922\",",
              "carteira[status] = \"Vencidos\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "9a44ef92-76db-44c9-bd27-37f95cdf2941"
          },
          {
            "name": "v_cel_c1_l15",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "TODAY() - 1",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2923\",",
              "carteira[status] = \"Vencidos\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "a9a6a961-da84-4eba-a075-dc6489e7c231"
          },
          {
            "name": "v_cel_c1_l16",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "TODAY() - 1",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2925\",",
              "carteira[status] = \"Vencidos\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "dd4cc48f-acc4-4385-a915-a71d932bca04"
          },
          {
            "name": "v_cel_c1_l17",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "TODAY() - 1",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2937\",",
              "carteira[status] = \"Vencidos\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "f07f09dd-f047-49ae-98ab-d86b85c5c852"
          },
          {
            "name": "v_cel_c2_l1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "TODAY()",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP1989\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "95c01112-8885-4d3d-a792-eeabd66a286b"
          },
          {
            "name": "v_cel_c2_l2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "TODAY()",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2023\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "3bdc9d10-b8be-406d-847e-84faad0252eb"
          },
          {
            "name": "v_cel_c2_l3",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "TODAY()",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2027\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "b34f8823-1033-4ef2-b933-b8f725eb11c1"
          },
          {
            "name": "v_cel_c2_l4",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "TODAY()",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2869\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "009e1ee8-0a02-4560-aba5-8fc3761173b4"
          },
          {
            "name": "v_cel_c2_l5",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "TODAY()",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2870\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "0ea2aa91-231f-4bb9-91cc-884c94886a12"
          },
          {
            "name": "v_cel_c2_l6",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "TODAY()",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2871\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "d536ce49-1d61-439a-9770-814591ff09ef"
          },
          {
            "name": "v_cel_c2_l7",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "TODAY()",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2872\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "ba9af9ca-b716-44b8-a61b-dd7026834107"
          },
          {
            "name": "v_cel_c2_l8",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "TODAY()",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2873\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "eb4f2cf2-f8c7-455e-9be3-2f017c639b90"
          },
          {
            "name": "v_cel_c2_l9",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "TODAY()",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2874\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "a35cc1b9-6228-4f10-9f71-d441ca00dc62"
          },
          {
            "name": "v_cel_c2_l10",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "TODAY()",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2875\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "4305e094-be07-4434-a87d-2a0dd84a93f9"
          },
          {
            "name": "v_cel_c2_l11",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "TODAY()",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2894\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "bda3adb0-0a70-4997-a4ca-01a56afb9727"
          },
          {
            "name": "v_cel_c2_l12",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "TODAY()",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2895\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "04c547ab-d148-4c13-8a54-4331f1752961"
          },
          {
            "name": "v_cel_c2_l13",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "TODAY()",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2896\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "9715c159-835d-4b9a-828e-c070c2f8add0"
          },
          {
            "name": "v_cel_c2_l14",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "TODAY()",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2922\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "d7f427d8-7fd5-4134-a32a-211ee39f8f98"
          },
          {
            "name": "v_cel_c2_l15",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "TODAY()",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2923\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "09a24606-92f8-46ea-975c-cac4873a78db"
          },
          {
            "name": "v_cel_c2_l16",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "TODAY()",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2925\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "820a06fb-86f3-40cd-9bc3-90dbece1cd60"
          },
          {
            "name": "v_cel_c2_l17",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "TODAY()",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2937\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "dc86d1ba-ffec-4ad7-ba83-5b5a2a493651"
          },
          {
            "name": "v_cel_c2_l18",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "TODAY()",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2938\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "a971f8ee-11d9-4abc-986b-6523df2ae103"
          },
          {
            "name": "v_cel_c3_l1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY(TODAY(), 1) = 6, ",
              "    TODAY() + 3, ",
              "    IF(",
              "        WEEKDAY(TODAY(), 1) = 7, ",
              "        TODAY() + 2, ",
              "        TODAY() + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP1989\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "9feb7f28-6a0f-48fc-856e-602efb28bbb1"
          },
          {
            "name": "v_cel_c3_l2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY(TODAY(), 1) = 6, ",
              "    TODAY() + 3, ",
              "    IF(",
              "        WEEKDAY(TODAY(), 1) = 7, ",
              "        TODAY() + 2, ",
              "        TODAY() + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2023\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "d3bee331-8e1b-4732-8b3b-db52da5c4e2f"
          },
          {
            "name": "v_cel_c3_l3",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY(TODAY(), 1) = 6, ",
              "    TODAY() + 3, ",
              "    IF(",
              "        WEEKDAY(TODAY(), 1) = 7, ",
              "        TODAY() + 2, ",
              "        TODAY() + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2027\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "dedace6b-c66f-4f13-a8f7-997fd193dd42"
          },
          {
            "name": "v_cel_c3_l4",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY(TODAY(), 1) = 6, ",
              "    TODAY() + 3, ",
              "    IF(",
              "        WEEKDAY(TODAY(), 1) = 7, ",
              "        TODAY() + 2, ",
              "        TODAY() + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2869\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "3e7f72d5-ffd1-4550-9b8d-ca8ffd41e862"
          },
          {
            "name": "v_cel_c3_l5",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY(TODAY(), 1) = 6, ",
              "    TODAY() + 3, ",
              "    IF(",
              "        WEEKDAY(TODAY(), 1) = 7, ",
              "        TODAY() + 2, ",
              "        TODAY() + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2870\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "0bed334a-4ea6-442d-b51b-868a95a981d0"
          },
          {
            "name": "v_cel_c3_l6",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY(TODAY(), 1) = 6, ",
              "    TODAY() + 3, ",
              "    IF(",
              "        WEEKDAY(TODAY(), 1) = 7, ",
              "        TODAY() + 2, ",
              "        TODAY() + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2871\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "7097d1ab-2fff-4194-85cb-76ac9a314ba4"
          },
          {
            "name": "v_cel_c3_l7",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY(TODAY(), 1) = 6, ",
              "    TODAY() + 3, ",
              "    IF(",
              "        WEEKDAY(TODAY(), 1) = 7, ",
              "        TODAY() + 2, ",
              "        TODAY() + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2872\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "3713aa74-20a7-45f7-b12e-135df4e4cab8"
          },
          {
            "name": "v_cel_c3_l8",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY(TODAY(), 1) = 6, ",
              "    TODAY() + 3, ",
              "    IF(",
              "        WEEKDAY(TODAY(), 1) = 7, ",
              "        TODAY() + 2, ",
              "        TODAY() + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2873\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "c3d9c325-9ad3-4a90-9579-c07ab2a3aa45"
          },
          {
            "name": "v_cel_c3_l9",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY(TODAY(), 1) = 6, ",
              "    TODAY() + 3, ",
              "    IF(",
              "        WEEKDAY(TODAY(), 1) = 7, ",
              "        TODAY() + 2, ",
              "        TODAY() + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2874\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "dfe46f9e-c7df-45ef-bd46-a38d00cfbef9"
          },
          {
            "name": "v_cel_c3_l10",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY(TODAY(), 1) = 6, ",
              "    TODAY() + 3, ",
              "    IF(",
              "        WEEKDAY(TODAY(), 1) = 7, ",
              "        TODAY() + 2, ",
              "        TODAY() + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2875\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "d9215fea-5c0f-4b6b-85b8-5461cbcf68e7"
          },
          {
            "name": "v_cel_c3_l11",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY(TODAY(), 1) = 6, ",
              "    TODAY() + 3, ",
              "    IF(",
              "        WEEKDAY(TODAY(), 1) = 7, ",
              "        TODAY() + 2, ",
              "        TODAY() + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2894\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "80b9c119-7395-4293-af61-0a68129b3e3a"
          },
          {
            "name": "v_cel_c3_l12",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY(TODAY(), 1) = 6, ",
              "    TODAY() + 3, ",
              "    IF(",
              "        WEEKDAY(TODAY(), 1) = 7, ",
              "        TODAY() + 2, ",
              "        TODAY() + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2895\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "b30ad64c-fb01-413d-80f0-517425292e02"
          },
          {
            "name": "v_cel_c3_l13",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY(TODAY(), 1) = 6, ",
              "    TODAY() + 3, ",
              "    IF(",
              "        WEEKDAY(TODAY(), 1) = 7, ",
              "        TODAY() + 2, ",
              "        TODAY() + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2896\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "90407fb2-b40c-4ce8-8eb8-29640c08a8dc"
          },
          {
            "name": "v_cel_c3_l14",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY(TODAY(), 1) = 6, ",
              "    TODAY() + 3, ",
              "    IF(",
              "        WEEKDAY(TODAY(), 1) = 7, ",
              "        TODAY() + 2, ",
              "        TODAY() + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2922\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "b330afbb-b64c-4ae2-bca4-ce663e8b950e"
          },
          {
            "name": "v_cel_c3_l15",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY(TODAY(), 1) = 6, ",
              "    TODAY() + 3, ",
              "    IF(",
              "        WEEKDAY(TODAY(), 1) = 7, ",
              "        TODAY() + 2, ",
              "        TODAY() + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2923\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "ea8f0efa-3eab-4722-82c6-524fabc52dd4"
          },
          {
            "name": "v_cel_c3_l16",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY(TODAY(), 1) = 6, ",
              "    TODAY() + 3, ",
              "    IF(",
              "        WEEKDAY(TODAY(), 1) = 7, ",
              "        TODAY() + 2, ",
              "        TODAY() + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2925\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "a48f4600-b563-4fee-ab4a-a35aabf72b5b"
          },
          {
            "name": "v_cel_c3_l17",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY(TODAY(), 1) = 6, ",
              "    TODAY() + 3, ",
              "    IF(",
              "        WEEKDAY(TODAY(), 1) = 7, ",
              "        TODAY() + 2, ",
              "        TODAY() + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2937\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "36ede266-1364-47b3-9bd0-a016dedcd70d"
          },
          {
            "name": "v_cel_c3_l18",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY(TODAY(), 1) = 6, ",
              "    TODAY() + 3, ",
              "    IF(",
              "        WEEKDAY(TODAY(), 1) = 7, ",
              "        TODAY() + 2, ",
              "        TODAY() + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2938\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "2b2e68c0-9ac9-410b-95bb-478426049290"
          },
          {
            "name": "v_cel_c4_l1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data3], 1) = 6, ",
              "    [data3] + 3, ",
              "    IF(",
              "        WEEKDAY([data3], 1) = 7, ",
              "        [data3] + 2, ",
              "        [data3] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP1989\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "d5ff24c5-1c62-42e7-a2d8-6d13d77fedbc"
          },
          {
            "name": "v_cel_c4_l2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data3], 1) = 6, ",
              "    [data3] + 3, ",
              "    IF(",
              "        WEEKDAY([data3], 1) = 7, ",
              "        [data3] + 2, ",
              "        [data3] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2023\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "b820c2ea-f068-4e8c-aa99-49f9fa915bd6"
          },
          {
            "name": "v_cel_c4_l3",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data3], 1) = 6, ",
              "    [data3] + 3, ",
              "    IF(",
              "        WEEKDAY([data3], 1) = 7, ",
              "        [data3] + 2, ",
              "        [data3] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2027\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "9614a0bd-f7a6-49c1-a121-9941f94194e8"
          },
          {
            "name": "v_cel_c4_l4",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data3], 1) = 6, ",
              "    [data3] + 3, ",
              "    IF(",
              "        WEEKDAY([data3], 1) = 7, ",
              "        [data3] + 2, ",
              "        [data3] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2869\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "a89ba395-73a8-4c08-b0e3-52764ec89874"
          },
          {
            "name": "v_cel_c4_l5",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data3], 1) = 6, ",
              "    [data3] + 3, ",
              "    IF(",
              "        WEEKDAY([data3], 1) = 7, ",
              "        [data3] + 2, ",
              "        [data3] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2870\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "06fa4f5d-60c2-48a4-a596-c7a9576eba14"
          },
          {
            "name": "v_cel_c4_l6",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data3], 1) = 6, ",
              "    [data3] + 3, ",
              "    IF(",
              "        WEEKDAY([data3], 1) = 7, ",
              "        [data3] + 2, ",
              "        [data3] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2871\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "dc5e79fe-2494-4464-8874-148d26a93898"
          },
          {
            "name": "v_cel_c4_l7",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data3], 1) = 6, ",
              "    [data3] + 3, ",
              "    IF(",
              "        WEEKDAY([data3], 1) = 7, ",
              "        [data3] + 2, ",
              "        [data3] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2872\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "14a08877-2ac2-4d7d-ab95-06a96e0385c5"
          },
          {
            "name": "v_cel_c4_l8",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data3], 1) = 6, ",
              "    [data3] + 3, ",
              "    IF(",
              "        WEEKDAY([data3], 1) = 7, ",
              "        [data3] + 2, ",
              "        [data3] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2873\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "0cac3aae-ef6e-4f0d-9ea3-9c02f66b2158"
          },
          {
            "name": "v_cel_c4_l9",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data3], 1) = 6, ",
              "    [data3] + 3, ",
              "    IF(",
              "        WEEKDAY([data3], 1) = 7, ",
              "        [data3] + 2, ",
              "        [data3] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2874\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "1f5e1b96-0154-4cde-aab9-6b81351b77da"
          },
          {
            "name": "v_cel_c4_l10",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data3], 1) = 6, ",
              "    [data3] + 3, ",
              "    IF(",
              "        WEEKDAY([data3], 1) = 7, ",
              "        [data3] + 2, ",
              "        [data3] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2875\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "65f1b63b-1b15-4700-b893-e20378f76da4"
          },
          {
            "name": "v_cel_c4_l11",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data3], 1) = 6, ",
              "    [data3] + 3, ",
              "    IF(",
              "        WEEKDAY([data3], 1) = 7, ",
              "        [data3] + 2, ",
              "        [data3] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2894\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "643d89ae-5e73-449f-8ea0-37874abf4f17"
          },
          {
            "name": "v_cel_c4_l12",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data3], 1) = 6, ",
              "    [data3] + 3, ",
              "    IF(",
              "        WEEKDAY([data3], 1) = 7, ",
              "        [data3] + 2, ",
              "        [data3] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2895\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "247b4490-325b-493b-94ab-2a1fa949e5bb"
          },
          {
            "name": "v_cel_c4_l13",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data3], 1) = 6, ",
              "    [data3] + 3, ",
              "    IF(",
              "        WEEKDAY([data3], 1) = 7, ",
              "        [data3] + 2, ",
              "        [data3] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2896\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "b23fbb27-a08b-4a2e-aa26-913ccab5396a"
          },
          {
            "name": "v_cel_c4_l14",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data3], 1) = 6, ",
              "    [data3] + 3, ",
              "    IF(",
              "        WEEKDAY([data3], 1) = 7, ",
              "        [data3] + 2, ",
              "        [data3] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2922\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "8f59fbea-c024-408d-b951-c9884bd19504"
          },
          {
            "name": "v_cel_c4_l15",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data3], 1) = 6, ",
              "    [data3] + 3, ",
              "    IF(",
              "        WEEKDAY([data3], 1) = 7, ",
              "        [data3] + 2, ",
              "        [data3] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2923\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "9a7fe119-53b5-4a42-9c20-eb31768cf028"
          },
          {
            "name": "v_cel_c4_l16",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data3], 1) = 6, ",
              "    [data3] + 3, ",
              "    IF(",
              "        WEEKDAY([data3], 1) = 7, ",
              "        [data3] + 2, ",
              "        [data3] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2925\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "91e410d2-2e85-4e3e-a8c0-6bc0a467f80c"
          },
          {
            "name": "v_cel_c4_l17",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data3], 1) = 6, ",
              "    [data3] + 3, ",
              "    IF(",
              "        WEEKDAY([data3], 1) = 7, ",
              "        [data3] + 2, ",
              "        [data3] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2937\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "541aea26-ec5f-42e8-84fb-073d0a1f00fc"
          },
          {
            "name": "v_cel_c4_l18",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data3], 1) = 6, ",
              "    [data3] + 3, ",
              "    IF(",
              "        WEEKDAY([data3], 1) = 7, ",
              "        [data3] + 2, ",
              "        [data3] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2938\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "2a50cbe7-0cc7-416a-8371-f34a9ebc9617"
          },
          {
            "name": "v_cel_c5_l1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data4], 1) = 6, ",
              "    [data4] + 3, ",
              "    IF(",
              "        WEEKDAY([data4], 1) = 7, ",
              "        [data4] + 2, ",
              "        [data4] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP1989\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "908dfc4f-9f5d-478d-997d-08a388b0d3c2"
          },
          {
            "name": "v_cel_c5_l2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data4], 1) = 6, ",
              "    [data4] + 3, ",
              "    IF(",
              "        WEEKDAY([data4], 1) = 7, ",
              "        [data4] + 2, ",
              "        [data4] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2023\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "f20ccf46-dfbe-4c7d-9f39-8549514d2d1c"
          },
          {
            "name": "v_cel_c5_l3",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data4], 1) = 6, ",
              "    [data4] + 3, ",
              "    IF(",
              "        WEEKDAY([data4], 1) = 7, ",
              "        [data4] + 2, ",
              "        [data4] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2027\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "d0507d46-3c09-442d-9f84-9c8fea2e85c8"
          },
          {
            "name": "v_cel_c5_l4",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data4], 1) = 6, ",
              "    [data4] + 3, ",
              "    IF(",
              "        WEEKDAY([data4], 1) = 7, ",
              "        [data4] + 2, ",
              "        [data4] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2869\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "d290bcc7-9278-4d7c-bda4-be1be11e7dab"
          },
          {
            "name": "v_cel_c5_l5",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data4], 1) = 6, ",
              "    [data4] + 3, ",
              "    IF(",
              "        WEEKDAY([data4], 1) = 7, ",
              "        [data4] + 2, ",
              "        [data4] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2870\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "80d86c70-e7ba-4dd5-a65d-0b0bd3337a71"
          },
          {
            "name": "v_cel_c5_l6",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data4], 1) = 6, ",
              "    [data4] + 3, ",
              "    IF(",
              "        WEEKDAY([data4], 1) = 7, ",
              "        [data4] + 2, ",
              "        [data4] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2871\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "18b0541c-9854-4cda-8a67-82dc11db9683"
          },
          {
            "name": "v_cel_c5_l7",
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data4], 1) = 6, ",
              "    [data4] + 3, ",
              "    IF(",
              "        WEEKDAY([data4], 1) = 7, ",
              "        [data4] + 2, ",
              "        [data4] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2872\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "0",
            "lineageTag": "8a3e7e65-5d6c-46d9-9ba7-15528f6482cc"
          },
          {
            "name": "v_cel_c5_l8",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data4], 1) = 6, ",
              "    [data4] + 3, ",
              "    IF(",
              "        WEEKDAY([data4], 1) = 7, ",
              "        [data4] + 2, ",
              "        [data4] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2873\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "321ec027-d3e9-4e73-ae78-acac1712f46b"
          },
          {
            "name": "v_cel_c5_l9",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data4], 1) = 6, ",
              "    [data4] + 3, ",
              "    IF(",
              "        WEEKDAY([data4], 1) = 7, ",
              "        [data4] + 2, ",
              "        [data4] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2874\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "efac22fd-3b59-437a-a3f4-5fe634180003"
          },
          {
            "name": "v_cel_c5_l11",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data4], 1) = 6, ",
              "    [data4] + 3, ",
              "    IF(",
              "        WEEKDAY([data4], 1) = 7, ",
              "        [data4] + 2, ",
              "        [data4] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2894\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "4b3e297e-38c2-4e0b-8692-f3858be633d7"
          },
          {
            "name": "v_cel_c5_l12",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data4], 1) = 6, ",
              "    [data4] + 3, ",
              "    IF(",
              "        WEEKDAY([data4], 1) = 7, ",
              "        [data4] + 2, ",
              "        [data4] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2895\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "0d600421-c593-4164-a13a-490e7c4e07e8"
          },
          {
            "name": "v_cel_c5_l13",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data4], 1) = 6, ",
              "    [data4] + 3, ",
              "    IF(",
              "        WEEKDAY([data4], 1) = 7, ",
              "        [data4] + 2, ",
              "        [data4] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2896\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "16d0bfc2-76a0-4f82-b52e-5c3206e51139"
          },
          {
            "name": "v_cel_c5_l14",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data4], 1) = 6, ",
              "    [data4] + 3, ",
              "    IF(",
              "        WEEKDAY([data4], 1) = 7, ",
              "        [data4] + 2, ",
              "        [data4] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2922\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "05625417-0e0c-408e-b921-7104f1796af2"
          },
          {
            "name": "v_cel_c5_l15",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data4], 1) = 6, ",
              "    [data4] + 3, ",
              "    IF(",
              "        WEEKDAY([data4], 1) = 7, ",
              "        [data4] + 2, ",
              "        [data4] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2923\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "a095c90a-5b5a-4773-888c-93a1e2629df7"
          },
          {
            "name": "v_cel_c5_l16",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data4], 1) = 6, ",
              "    [data4] + 3, ",
              "    IF(",
              "        WEEKDAY([data4], 1) = 7, ",
              "        [data4] + 2, ",
              "        [data4] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2925\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "3c59cb30-47f9-42fc-8322-ee38ffc342c1"
          },
          {
            "name": "v_cel_c5_l17",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data4], 1) = 6, ",
              "    [data4] + 3, ",
              "    IF(",
              "        WEEKDAY([data4], 1) = 7, ",
              "        [data4] + 2, ",
              "        [data4] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2937\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "726c4407-0318-44c2-a65b-4203cb1fc0c4"
          },
          {
            "name": "v_cel_c5_l10",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data4], 1) = 6, ",
              "    [data4] + 3, ",
              "    IF(",
              "        WEEKDAY([data4], 1) = 7, ",
              "        [data4] + 2, ",
              "        [data4] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2875\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "744036f4-a6ae-4c38-92e0-df43eb57ad68"
          },
          {
            "name": "v_cel_c5_l18",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data4], 1) = 6, ",
              "    [data4] + 3, ",
              "    IF(",
              "        WEEKDAY([data4], 1) = 7, ",
              "        [data4] + 2, ",
              "        [data4] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2938\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "97313002-910e-45f9-8fe8-2708c3aab10e"
          },
          {
            "name": "v_cel_c6_l1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data5], 1) = 6, ",
              "    [data5] + 3, ",
              "    IF(",
              "        WEEKDAY([data5], 1) = 7, ",
              "        [data5] + 2, ",
              "        [data5] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP1989\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "4ad568d3-cdf9-4685-8ce2-f7928901e1fe"
          },
          {
            "name": "v_cel_c6_l2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data5], 1) = 6, ",
              "    [data5] + 3, ",
              "    IF(",
              "        WEEKDAY([data5], 1) = 7, ",
              "        [data5] + 2, ",
              "        [data5] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2023\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "e96b188a-981e-4ed1-9e9b-6fca87f30cff"
          },
          {
            "name": "v_cel_c6_l3",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data5], 1) = 6, ",
              "    [data5] + 3, ",
              "    IF(",
              "        WEEKDAY([data5], 1) = 7, ",
              "        [data5] + 2, ",
              "        [data5] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2027\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "7a8845bd-9317-45fe-9bae-718da43b8677"
          },
          {
            "name": "v_cel_c6_l4",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data5], 1) = 6, ",
              "    [data5] + 3, ",
              "    IF(",
              "        WEEKDAY([data5], 1) = 7, ",
              "        [data5] + 2, ",
              "        [data5] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2869\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "ae49f2ac-b317-4181-88cb-708980bff069"
          },
          {
            "name": "v_cel_c6_l5",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data5], 1) = 6, ",
              "    [data5] + 3, ",
              "    IF(",
              "        WEEKDAY([data5], 1) = 7, ",
              "        [data5] + 2, ",
              "        [data5] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2870\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "cf4e8d11-096d-4071-b7f6-db61540fad3d"
          },
          {
            "name": "v_cel_c6_l6",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data5], 1) = 6, ",
              "    [data5] + 3, ",
              "    IF(",
              "        WEEKDAY([data5], 1) = 7, ",
              "        [data5] + 2, ",
              "        [data5] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2871\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "249114af-f50c-4161-b635-e89202f0cdc6"
          },
          {
            "name": "v_cel_c6_l7",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data5], 1) = 6, ",
              "    [data5] + 3, ",
              "    IF(",
              "        WEEKDAY([data5], 1) = 7, ",
              "        [data5] + 2, ",
              "        [data5] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2872\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "52211f31-570a-410f-b5b9-cfb7d31ac4d2"
          },
          {
            "name": "v_cel_c6_l8",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data5], 1) = 6, ",
              "    [data5] + 3, ",
              "    IF(",
              "        WEEKDAY([data5], 1) = 7, ",
              "        [data5] + 2, ",
              "        [data5] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2873\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "1e4e3d81-cf43-4ae5-b24d-f5a8bdfd8d72"
          },
          {
            "name": "v_cel_c6_l9",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data5], 1) = 6, ",
              "    [data5] + 3, ",
              "    IF(",
              "        WEEKDAY([data5], 1) = 7, ",
              "        [data5] + 2, ",
              "        [data5] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2874\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "c772e9f7-ceca-4622-ab83-f693d403d440"
          },
          {
            "name": "v_cel_c6_l10",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data5], 1) = 6, ",
              "    [data5] + 3, ",
              "    IF(",
              "        WEEKDAY([data5], 1) = 7, ",
              "        [data5] + 2, ",
              "        [data5] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2875\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "0",
            "lineageTag": "c33bbbea-0bac-4425-ae9b-085a588ff3e9"
          },
          {
            "name": "v_cel_c6_l11",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data5], 1) = 6, ",
              "    [data5] + 3, ",
              "    IF(",
              "        WEEKDAY([data5], 1) = 7, ",
              "        [data5] + 2, ",
              "        [data5] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2894\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "lineageTag": "d6a25473-e623-4fc9-8b33-9917edb65156"
          },
          {
            "name": "v_cel_c6_l12",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data5], 1) = 6, ",
              "    [data5] + 3, ",
              "    IF(",
              "        WEEKDAY([data5], 1) = 7, ",
              "        [data5] + 2, ",
              "        [data5] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2895\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "lineageTag": "cfdc01f2-165d-4a00-a9e1-59cb47c89dc1"
          },
          {
            "name": "v_cel_c6_l13",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data5], 1) = 6, ",
              "    [data5] + 3, ",
              "    IF(",
              "        WEEKDAY([data5], 1) = 7, ",
              "        [data5] + 2, ",
              "        [data5] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2896\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "693b945d-dbbf-4071-9fc9-ece9f556535c"
          },
          {
            "name": "v_cel_c6_l14",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data5], 1) = 6, ",
              "    [data5] + 3, ",
              "    IF(",
              "        WEEKDAY([data5], 1) = 7, ",
              "        [data5] + 2, ",
              "        [data5] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2922\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "4a94e72e-7d1f-42fc-a8cb-3963042548d4"
          },
          {
            "name": "v_cel_c6_l15",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data5], 1) = 6, ",
              "    [data5] + 3, ",
              "    IF(",
              "        WEEKDAY([data5], 1) = 7, ",
              "        [data5] + 2, ",
              "        [data5] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2923\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "c470153d-5359-49a9-bddf-2aee5870b45c"
          },
          {
            "name": "v_cel_c6_l16",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data5], 1) = 6, ",
              "    [data5] + 3, ",
              "    IF(",
              "        WEEKDAY([data5], 1) = 7, ",
              "        [data5] + 2, ",
              "        [data5] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2925\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "599ec2eb-f1d4-4f2a-b81c-f80266193ed7"
          },
          {
            "name": "v_cel_c6_l17",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data5], 1) = 6, ",
              "    [data5] + 3, ",
              "    IF(",
              "        WEEKDAY([data5], 1) = 7, ",
              "        [data5] + 2, ",
              "        [data5] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2937\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "27011dfb-5b21-43e1-a179-d0515ff2fb97"
          },
          {
            "name": "v_cel_c6_l18",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data5], 1) = 6, ",
              "    [data5] + 3, ",
              "    IF(",
              "        WEEKDAY([data5], 1) = 7, ",
              "        [data5] + 2, ",
              "        [data5] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2938\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "dc9a56ad-88ce-439b-a5b7-1421be50b68d"
          },
          {
            "name": "v_cel_c7_l1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data6], 1) = 6, ",
              "    [data6] + 3, ",
              "    IF(",
              "        WEEKDAY([data6], 1) = 7, ",
              "        [data6] + 2, ",
              "        [data6] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP1989\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "342a88b0-200e-4bdd-866c-7b8b42c07789"
          },
          {
            "name": "v_cel_c7_l2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data6], 1) = 6, ",
              "    [data6] + 3, ",
              "    IF(",
              "        WEEKDAY([data6], 1) = 7, ",
              "        [data6] + 2, ",
              "        [data6] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2023\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "b87264e0-40aa-4f5a-9575-306c0eddf466"
          },
          {
            "name": "v_cel_c7_l3",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data6], 1) = 6, ",
              "    [data6] + 3, ",
              "    IF(",
              "        WEEKDAY([data6], 1) = 7, ",
              "        [data6] + 2, ",
              "        [data6] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2027\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "c75fb572-c078-4424-b5e8-49578d9d643b"
          },
          {
            "name": "v_cel_c7_l4",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data6], 1) = 6, ",
              "    [data6] + 3, ",
              "    IF(",
              "        WEEKDAY([data6], 1) = 7, ",
              "        [data6] + 2, ",
              "        [data6] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2869\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "145e43b7-f003-46f7-af04-6e6d60af9f0c"
          },
          {
            "name": "v_cel_c7_l5",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data6], 1) = 6, ",
              "    [data6] + 3, ",
              "    IF(",
              "        WEEKDAY([data6], 1) = 7, ",
              "        [data6] + 2, ",
              "        [data6] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2870\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "ea4857ed-6c03-4eca-986b-61f4b8c5693a"
          },
          {
            "name": "v_cel_c7_l6",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data6], 1) = 6, ",
              "    [data6] + 3, ",
              "    IF(",
              "        WEEKDAY([data6], 1) = 7, ",
              "        [data6] + 2, ",
              "        [data6] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2871\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "e781f44d-5379-4cd0-a4d7-a7da53be6d5c"
          },
          {
            "name": "v_cel_c7_l7",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data6], 1) = 6, ",
              "    [data6] + 3, ",
              "    IF(",
              "        WEEKDAY([data6], 1) = 7, ",
              "        [data6] + 2, ",
              "        [data6] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2872\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "ffb205a5-a194-4353-bfcb-44e83efc64e0"
          },
          {
            "name": "v_cel_c7_l8",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data6], 1) = 6, ",
              "    [data6] + 3, ",
              "    IF(",
              "        WEEKDAY([data6], 1) = 7, ",
              "        [data6] + 2, ",
              "        [data6] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2873\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "07725349-e068-41d6-be00-07882dd34217"
          },
          {
            "name": "v_cel_c7_l9",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data6], 1) = 6, ",
              "    [data6] + 3, ",
              "    IF(",
              "        WEEKDAY([data6], 1) = 7, ",
              "        [data6] + 2, ",
              "        [data6] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2874\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "4f3bd398-05da-4823-a6db-b72be8b36c37"
          },
          {
            "name": "v_cel_c7_l10",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data6], 1) = 6, ",
              "    [data6] + 3, ",
              "    IF(",
              "        WEEKDAY([data6], 1) = 7, ",
              "        [data6] + 2, ",
              "        [data6] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2875\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "65afc18f-3e6b-4b5e-9285-bd1766f27efa"
          },
          {
            "name": "v_cel_c7_l11",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data6], 1) = 6, ",
              "    [data6] + 3, ",
              "    IF(",
              "        WEEKDAY([data6], 1) = 7, ",
              "        [data6] + 2, ",
              "        [data6] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2894\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "28e49e8b-b41f-4e1a-af4b-47b3c7eaed2e"
          },
          {
            "name": "v_cel_c7_l12",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data6], 1) = 6, ",
              "    [data6] + 3, ",
              "    IF(",
              "        WEEKDAY([data6], 1) = 7, ",
              "        [data6] + 2, ",
              "        [data6] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2895\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "7c58674a-7bfb-4a3b-81f9-5c7ad0cb3cb5"
          },
          {
            "name": "v_cel_c7_l13",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data6], 1) = 6, ",
              "    [data6] + 3, ",
              "    IF(",
              "        WEEKDAY([data6], 1) = 7, ",
              "        [data6] + 2, ",
              "        [data6] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2896\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "4a0071d9-82f0-46b0-80e9-60cabb565069"
          },
          {
            "name": "v_cel_c7_l14",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data6], 1) = 6, ",
              "    [data6] + 3, ",
              "    IF(",
              "        WEEKDAY([data6], 1) = 7, ",
              "        [data6] + 2, ",
              "        [data6] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2922\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "6b119778-1c3a-4150-916b-dd5f2e21b601"
          },
          {
            "name": "v_cel_c7_l15",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data6], 1) = 6, ",
              "    [data6] + 3, ",
              "    IF(",
              "        WEEKDAY([data6], 1) = 7, ",
              "        [data6] + 2, ",
              "        [data6] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2923\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "269c0af4-7bec-42a2-821d-62594b42c16e"
          },
          {
            "name": "v_cel_c7_l16",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data6], 1) = 6, ",
              "    [data6] + 3, ",
              "    IF(",
              "        WEEKDAY([data6], 1) = 7, ",
              "        [data6] + 2, ",
              "        [data6] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2925\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "bf3bc9f5-3732-4494-bc78-fc5462949314"
          },
          {
            "name": "v_cel_c7_l17",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data6], 1) = 6, ",
              "    [data6] + 3, ",
              "    IF(",
              "        WEEKDAY([data6], 1) = 7, ",
              "        [data6] + 2, ",
              "        [data6] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2937\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "de78304a-e337-4119-8bfb-abd26b70302a"
          },
          {
            "name": "v_cel_c7_l18",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data6], 1) = 6, ",
              "    [data6] + 3, ",
              "    IF(",
              "        WEEKDAY([data6], 1) = 7, ",
              "        [data6] + 2, ",
              "        [data6] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2938\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "84f9af34-d90a-493d-9218-41e05e747069"
          },
          {
            "name": "v_cel_c8_l1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "    IF(",
              "        WEEKDAY([data7], 1) = 6, ",
              "        [data7] + 3, ",
              "        IF(",
              "            WEEKDAY([data7], 1) = 7, ",
              "            [data7] + 2, ",
              "            [data7] + 1",
              "        )",
              "    )",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP1989\",",
              "carteira[data limite2] >= data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "05c63ea9-5b1f-4c12-ad73-521322c3fc71"
          },
          {
            "name": "v_cel_c8_l2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "    IF(",
              "        WEEKDAY([data7], 1) = 6, ",
              "        [data7] + 3, ",
              "        IF(",
              "            WEEKDAY([data7], 1) = 7, ",
              "            [data7] + 2, ",
              "            [data7] + 1",
              "        )",
              "    )",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2023\",",
              "carteira[data limite2] >= data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "71ee6b60-2e4f-4799-ae38-3b86bdbe9fdc"
          },
          {
            "name": "v_cel_c8_l3",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "    IF(",
              "        WEEKDAY([data7], 1) = 6, ",
              "        [data7] + 3, ",
              "        IF(",
              "            WEEKDAY([data7], 1) = 7, ",
              "            [data7] + 2, ",
              "            [data7] + 1",
              "        )",
              "    )",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2027\",",
              "carteira[data limite2] >= data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "ed278e52-71dc-493c-88f0-a46ce7db3716"
          },
          {
            "name": "v_cel_c8_l4",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "    IF(",
              "        WEEKDAY([data7], 1) = 6, ",
              "        [data7] + 3, ",
              "        IF(",
              "            WEEKDAY([data7], 1) = 7, ",
              "            [data7] + 2, ",
              "            [data7] + 1",
              "        )",
              "    )",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2869\",",
              "carteira[data limite2] >= data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "e081a9a5-f266-4f5a-b3a5-871ed32bd689"
          },
          {
            "name": "v_cel_c8_l5",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "    IF(",
              "        WEEKDAY([data7], 1) = 6, ",
              "        [data7] + 3, ",
              "        IF(",
              "            WEEKDAY([data7], 1) = 7, ",
              "            [data7] + 2, ",
              "            [data7] + 1",
              "        )",
              "    )",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2870\",",
              "carteira[data limite2] >= data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "4f61845d-fbb6-4f8c-a15f-1df54ce6d64c"
          },
          {
            "name": "v_cel_c8_l6",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "    IF(",
              "        WEEKDAY([data7], 1) = 6, ",
              "        [data7] + 3, ",
              "        IF(",
              "            WEEKDAY([data7], 1) = 7, ",
              "            [data7] + 2, ",
              "            [data7] + 1",
              "        )",
              "    )",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2871\",",
              "carteira[data limite2] >= data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "ffd0ea55-5701-460b-b4a9-7629cc04e243"
          },
          {
            "name": "v_cel_c8_l7",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "    IF(",
              "        WEEKDAY([data7], 1) = 6, ",
              "        [data7] + 3, ",
              "        IF(",
              "            WEEKDAY([data7], 1) = 7, ",
              "            [data7] + 2, ",
              "            [data7] + 1",
              "        )",
              "    )",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2872\",",
              "carteira[data limite2] >= data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "5ae954ac-bf11-496c-b45a-53005fb2d533"
          },
          {
            "name": "v_cel_c8_l8",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "    IF(",
              "        WEEKDAY([data7], 1) = 6, ",
              "        [data7] + 3, ",
              "        IF(",
              "            WEEKDAY([data7], 1) = 7, ",
              "            [data7] + 2, ",
              "            [data7] + 1",
              "        )",
              "    )",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2873\",",
              "carteira[data limite2] >= data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "338a1bc1-fff6-4bac-82bf-ccf7aa2a3ea0"
          },
          {
            "name": "v_cel_c8_l9",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "    IF(",
              "        WEEKDAY([data7], 1) = 6, ",
              "        [data7] + 3, ",
              "        IF(",
              "            WEEKDAY([data7], 1) = 7, ",
              "            [data7] + 2, ",
              "            [data7] + 1",
              "        )",
              "    )",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2875\",",
              "carteira[data limite2] >= data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "123316af-6035-464d-b85e-c7ab62358cd6"
          },
          {
            "name": "v_cel_c8_l10",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "    IF(",
              "        WEEKDAY([data7], 1) = 6, ",
              "        [data7] + 3, ",
              "        IF(",
              "            WEEKDAY([data7], 1) = 7, ",
              "            [data7] + 2, ",
              "            [data7] + 1",
              "        )",
              "    )",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2894\",",
              "carteira[data limite2] >= data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "29018073-8d7a-478d-bd80-2560b48a158c"
          },
          {
            "name": "v_cel_c8_l11",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "    IF(",
              "        WEEKDAY([data7], 1) = 6, ",
              "        [data7] + 3, ",
              "        IF(",
              "            WEEKDAY([data7], 1) = 7, ",
              "            [data7] + 2, ",
              "            [data7] + 1",
              "        )",
              "    )",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2895\",",
              "carteira[data limite2] >= data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "ee196aed-6e25-41ec-9343-0880dadb81de"
          },
          {
            "name": "v_cel_c8_l12",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "    IF(",
              "        WEEKDAY([data7], 1) = 6, ",
              "        [data7] + 3, ",
              "        IF(",
              "            WEEKDAY([data7], 1) = 7, ",
              "            [data7] + 2, ",
              "            [data7] + 1",
              "        )",
              "    )",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2896\",",
              "carteira[data limite2] >= data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "3e5a480f-68fe-4012-bbec-c324933ebd7b"
          },
          {
            "name": "v_cel_c8_l13",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "    IF(",
              "        WEEKDAY([data7], 1) = 6, ",
              "        [data7] + 3, ",
              "        IF(",
              "            WEEKDAY([data7], 1) = 7, ",
              "            [data7] + 2, ",
              "            [data7] + 1",
              "        )",
              "    )",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2922\",",
              "carteira[data limite2] >= data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "b52eccc6-bec2-4380-b30e-d9390d82ad34"
          },
          {
            "name": "v_cel_c8_l14",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "    IF(",
              "        WEEKDAY([data7], 1) = 6, ",
              "        [data7] + 3, ",
              "        IF(",
              "            WEEKDAY([data7], 1) = 7, ",
              "            [data7] + 2, ",
              "            [data7] + 1",
              "        )",
              "    )",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2923\",",
              "carteira[data limite2] >= data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "e8512e79-de5a-48e2-a192-788746fee83a"
          },
          {
            "name": "v_cel_c8_l15",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "    IF(",
              "        WEEKDAY([data7], 1) = 6, ",
              "        [data7] + 3, ",
              "        IF(",
              "            WEEKDAY([data7], 1) = 7, ",
              "            [data7] + 2, ",
              "            [data7] + 1",
              "        )",
              "    )",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2925\",",
              "carteira[data limite2] >= data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "cc192fa5-65da-4162-bda3-216dc8ddd822"
          },
          {
            "name": "v_cel_c8_l16",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "    IF(",
              "        WEEKDAY([data7], 1) = 6, ",
              "        [data7] + 3, ",
              "        IF(",
              "            WEEKDAY([data7], 1) = 7, ",
              "            [data7] + 2, ",
              "            [data7] + 1",
              "        )",
              "    )",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2937\",",
              "carteira[data limite2] >= data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "b6fcdb90-a62e-410b-b17d-56b61bcf03b1"
          },
          {
            "name": "v_cel_c8_l17",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "    IF(",
              "        WEEKDAY([data7], 1) = 6, ",
              "        [data7] + 3, ",
              "        IF(",
              "            WEEKDAY([data7], 1) = 7, ",
              "            [data7] + 2, ",
              "            [data7] + 1",
              "        )",
              "    )",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2938\",",
              "carteira[data limite2] >= data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "7847b391-94cc-4dcd-8303-5dcbae076378"
          },
          {
            "name": "v_cel_c8_l18",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "    IF(",
              "        WEEKDAY([data7], 1) = 6, ",
              "        [data7] + 3, ",
              "        IF(",
              "            WEEKDAY([data7], 1) = 7, ",
              "            [data7] + 2, ",
              "            [data7] + 1",
              "        )",
              "    )",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2874\",",
              "carteira[data limite2] >= data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "23163a3a-a5a8-4f42-b5e5-1f901d1c33f7"
          },
          {
            "name": "v_cel_c9_l1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "[v_cel_c1_l1]+",
              "[v_cel_c2_l1]+",
              "[v_cel_c3_l1]+",
              "[v_cel_c4_l1]+",
              "[v_cel_c5_l1]+",
              "[v_cel_c6_l1]+",
              "[v_cel_c7_l1]+",
              "[v_cel_c8_l1]"
            ],
            "formatString": "#,0",
            "lineageTag": "e1a69ab2-1aa3-4c92-b8d9-fde44de87806"
          },
          {
            "name": "v_cel_c9_l2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "[v_cel_c1_l2]+",
              "[v_cel_c2_l2]+",
              "[v_cel_c3_l2]+",
              "[v_cel_c4_l2]+",
              "[v_cel_c5_l2]+",
              "[v_cel_c6_l2]+",
              "[v_cel_c7_l2]+",
              "[v_cel_c8_l2]"
            ],
            "formatString": "#,0",
            "lineageTag": "8f7a5192-6d7b-4449-8c58-867cbc629245"
          },
          {
            "name": "v_cel_c9_l3",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "[v_cel_c1_l3]+",
              "[v_cel_c2_l3]+",
              "[v_cel_c3_l3]+",
              "[v_cel_c4_l3]+",
              "[v_cel_c5_l3]+",
              "[v_cel_c6_l3]+",
              "[v_cel_c7_l3]+",
              "[v_cel_c8_l3]"
            ],
            "formatString": "#,0",
            "lineageTag": "22f16404-8dfe-45d5-ab7c-cfd31dc8cc2b"
          },
          {
            "name": "v_cel_c9_l4",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "[v_cel_c1_l4]+",
              "[v_cel_c2_l4]+",
              "[v_cel_c3_l4]+",
              "[v_cel_c4_l4]+",
              "[v_cel_c5_l4]+",
              "[v_cel_c6_l4]+",
              "[v_cel_c7_l4]+",
              "[v_cel_c8_l4]"
            ],
            "formatString": "#,0",
            "lineageTag": "0fc39fa2-3f28-4738-bc3f-c159ee7264b4"
          },
          {
            "name": "v_cel_c9_l5",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "[v_cel_c1_l5]+",
              "[v_cel_c2_l5]+",
              "[v_cel_c3_l5]+",
              "[v_cel_c4_l5]+",
              "[v_cel_c5_l5]+",
              "[v_cel_c6_l5]+",
              "[v_cel_c7_l5]+",
              "[v_cel_c8_l5]"
            ],
            "formatString": "#,0",
            "lineageTag": "8feb5afa-9163-48e0-9107-3dba3d4264b6"
          },
          {
            "name": "v_cel_c9_l6",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "[v_cel_c1_l6]+",
              "[v_cel_c2_l6]+",
              "[v_cel_c3_l6]+",
              "[v_cel_c4_l6]+",
              "[v_cel_c5_l6]+",
              "[v_cel_c6_l6]+",
              "[v_cel_c7_l6]+",
              "[v_cel_c8_l6]"
            ],
            "formatString": "#,0",
            "lineageTag": "f3a20648-a415-4730-9ed3-85385cf3c96b"
          },
          {
            "name": "v_cel_c9_l7",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "[v_cel_c1_l7]+",
              "[v_cel_c2_l7]+",
              "[v_cel_c3_l7]+",
              "[v_cel_c4_l7]+",
              "[v_cel_c5_l7]+",
              "[v_cel_c6_l7]+",
              "[v_cel_c7_l7]+",
              "[v_cel_c8_l7]"
            ],
            "formatString": "#,0",
            "lineageTag": "13d0b254-9ffb-4d58-9ab4-add79594a662"
          },
          {
            "name": "v_cel_c9_l8",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "[v_cel_c1_l8]+",
              "[v_cel_c2_l8]+",
              "[v_cel_c3_l8]+",
              "[v_cel_c4_l8]+",
              "[v_cel_c5_l8]+",
              "[v_cel_c6_l8]+",
              "[v_cel_c7_l8]+",
              "[v_cel_c8_l8]"
            ],
            "formatString": "#,0",
            "lineageTag": "51cf7206-0381-4621-b383-7972ce88aba1"
          },
          {
            "name": "v_cel_c9_l10",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "[v_cel_c1_l10]+",
              "[v_cel_c2_l10]+",
              "[v_cel_c3_l10]+",
              "[v_cel_c4_l10]+",
              "[v_cel_c5_l10]+",
              "[v_cel_c6_l10]+",
              "[v_cel_c7_l10]+",
              "[v_cel_c8_l10]"
            ],
            "formatString": "#,0",
            "lineageTag": "c42f77a2-9be0-4021-82ed-267e9caa78f7"
          },
          {
            "name": "v_cel_c9_l9",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "[v_cel_c1_l9]+",
              "[v_cel_c2_l9]+",
              "[v_cel_c3_l9]+",
              "[v_cel_c4_l9]+",
              "[v_cel_c5_l9]+",
              "[v_cel_c6_l9]+",
              "[v_cel_c7_l9]+",
              "[v_cel_c8_l9]"
            ],
            "formatString": "#,0",
            "lineageTag": "f382301d-b907-40b8-a16f-e61e1ba5d282"
          },
          {
            "name": "v_cel_c9_l11",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "[v_cel_c1_l11]+",
              "[v_cel_c2_l11]+",
              "[v_cel_c3_l11]+",
              "[v_cel_c4_l11]+",
              "[v_cel_c5_l11]+",
              "[v_cel_c6_l11]+",
              "[v_cel_c7_l11]+",
              "[v_cel_c8_l11]"
            ],
            "formatString": "#,0",
            "lineageTag": "f89227b0-f94c-4c76-b6a2-4882b72e7c88"
          },
          {
            "name": "v_cel_c9_l12",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "[v_cel_c1_l12]+",
              "[v_cel_c2_l12]+",
              "[v_cel_c3_l12]+",
              "[v_cel_c4_l12]+",
              "[v_cel_c5_l12]+",
              "[v_cel_c6_l12]+",
              "[v_cel_c7_l12]+",
              "[v_cel_c8_l12]"
            ],
            "formatString": "#,0",
            "lineageTag": "13cd4f59-97d8-4d69-a2d1-3120bab91f7a"
          },
          {
            "name": "v_cel_c9_l13",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "[v_cel_c1_l13]+",
              "[v_cel_c2_l13]+",
              "[v_cel_c3_l13]+",
              "[v_cel_c4_l13]+",
              "[v_cel_c5_l13]+",
              "[v_cel_c6_l13]+",
              "[v_cel_c7_l13]+",
              "[v_cel_c8_l13]"
            ],
            "formatString": "#,0",
            "lineageTag": "415a8dc6-19e9-47a6-af10-633dff2fa4fc"
          },
          {
            "name": "v_cel_c9_l14",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "[v_cel_c1_l14]+",
              "[v_cel_c2_l14]+",
              "[v_cel_c3_l14]+",
              "[v_cel_c4_l14]+",
              "[v_cel_c5_l14]+",
              "[v_cel_c6_l14]+",
              "[v_cel_c7_l14]+",
              "[v_cel_c8_l14]"
            ],
            "formatString": "#,0",
            "lineageTag": "38d5d91e-7e68-4b84-8864-8bfbf059d2c4"
          },
          {
            "name": "v_cel_c9_l15",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "[v_cel_c1_l15]+",
              "[v_cel_c2_l15]+",
              "[v_cel_c3_l15]+",
              "[v_cel_c4_l15]+",
              "[v_cel_c5_l15]+",
              "[v_cel_c6_l15]+",
              "[v_cel_c7_l15]+",
              "[v_cel_c8_l15]"
            ],
            "formatString": "#,0",
            "lineageTag": "c956770f-cbb6-45a5-8602-2990c48854e8"
          },
          {
            "name": "v_cel_c9_l16",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "[v_cel_c1_l16]+",
              "[v_cel_c2_l16]+",
              "[v_cel_c3_l16]+",
              "[v_cel_c4_l16]+",
              "[v_cel_c5_l16]+",
              "[v_cel_c6_l16]+",
              "[v_cel_c7_l16]+",
              "[v_cel_c8_l16]"
            ],
            "formatString": "#,0",
            "lineageTag": "c10c0fc2-c447-441d-b3b0-cb39334ef08d"
          },
          {
            "name": "v_cel_c9_l17",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "[v_cel_c1_l17]+",
              "[v_cel_c2_l17]+",
              "[v_cel_c3_l17]+",
              "[v_cel_c4_l17]+",
              "[v_cel_c5_l17]+",
              "[v_cel_c6_l17]+",
              "[v_cel_c7_l17]+",
              "[v_cel_c8_l17]"
            ],
            "formatString": "#,0",
            "lineageTag": "3455d14a-99a9-4e53-beb5-6a28eda884fb"
          },
          {
            "name": "v_cel_c9_l18",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Tabela Carteira",
            "expression": [
              "",
              "[v_cel_c1_l18]+",
              "[v_cel_c2_l18]+",
              "[v_cel_c3_l18]+",
              "[v_cel_c4_l18]+",
              "[v_cel_c5_l18]+",
              "[v_cel_c6_l18]+",
              "[v_cel_c7_l18]+",
              "[v_cel_c8_l18]"
            ],
            "formatString": "#,0",
            "lineageTag": "fe879269-695a-4bc8-beac-05a33ddcbf97"
          },
          {
            "name": "hora_data",
            "displayFolder": "Outros",
            "expression": "FORMAT(SELECTEDVALUE(tTempo[hora_atual]),\"hh:mm\")&\"  \"&SELECTEDVALUE(tTempo[data_atual])",
            "lineageTag": "aa604e09-aec3-4fec-b793-623b54cf91a2"
          },
          {
            "name": "contagem_back",
            "displayFolder": "Outros",
            "expression": "\"Black Friday!\"",
            "lineageTag": "16fde9a8-6e82-44b8-81dd-143f3cf8f9ae"
          },
          {
            "name": "username",
            "displayFolder": "Outros",
            "expression": [
              "",
              "VAR UsuarioCompleto = USERPRINCIPALNAME()",
              "VAR UsuarioSemDominio = LEFT(UsuarioCompleto, SEARCH(\"@\", UsuarioCompleto, 1) - 1)",
              "VAR UsuarioComEspacos = SUBSTITUTE(UsuarioSemDominio, \".\", \" \")",
              "",
              "VAR PalavrasSeparadas = SUBSTITUTE(UsuarioComEspacos, \" \", \"|\")",
              "VAR ListaPalavras = ",
              "    ADDCOLUMNS(",
              "        GENERATESERIES(1, PATHLENGTH(PalavrasSeparadas)),",
              "        \"Palavra\", PATHITEM(PalavrasSeparadas, [Value])",
              "    )",
              "VAR NomeCapitalizado = ",
              "    CONCATENATEX(",
              "        ListaPalavras,",
              "        UPPER(LEFT([Palavra], 1)) & LOWER(MID([Palavra], 2, LEN([Palavra]))),",
              "        \" \"",
              "    )",
              "RETURN \"👥 Usuário:\"&\" \"&NomeCapitalizado"
            ],
            "lineageTag": "b3fb0373-a235-4bb0-9753-32e2402e9716"
          },
          {
            "name": "c1_total",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Carteira - Total geral",
            "expression": [
              "",
              "[v_cel_c1_l1]+",
              "[v_cel_c1_l2]+",
              "[v_cel_c1_l3]+",
              "[v_cel_c1_l4]+",
              "[v_cel_c1_l5]+",
              "[v_cel_c1_l6]+",
              "[v_cel_c1_l7]+",
              "[v_cel_c1_l8]+",
              "[v_cel_c1_l9]+",
              "[v_cel_c1_l10]+",
              "[v_cel_c1_l11]+",
              "[v_cel_c1_l12]+",
              "[v_cel_c1_l13]+",
              "[v_cel_c1_l14]+",
              "[v_cel_c1_l15]+",
              "[v_cel_c1_l16]+",
              "[v_cel_c1_l17]+",
              "[v_cel_c1_l18]"
            ],
            "formatString": "#,0",
            "lineageTag": "9c991558-695a-4c39-941e-cadfd698c7ed"
          },
          {
            "name": "c2_total",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Carteira - Total geral",
            "expression": [
              "",
              "[v_cel_c2_l1]+",
              "[v_cel_c2_l2]+",
              "[v_cel_c2_l3]+",
              "[v_cel_c2_l4]+",
              "[v_cel_c2_l5]+",
              "[v_cel_c2_l6]+",
              "[v_cel_c2_l7]+",
              "[v_cel_c2_l8]+",
              "[v_cel_c2_l9]+",
              "[v_cel_c2_l10]+",
              "[v_cel_c2_l11]+",
              "[v_cel_c2_l12]+",
              "[v_cel_c2_l13]+",
              "[v_cel_c2_l14]+",
              "[v_cel_c2_l15]+",
              "[v_cel_c2_l16]+",
              "[v_cel_c2_l17]+",
              "[v_cel_c2_l18]"
            ],
            "formatString": "#,0",
            "lineageTag": "f8a1c9f5-e171-4628-b7e8-5f434af147ba"
          },
          {
            "name": "c3_total",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Carteira - Total geral",
            "expression": [
              "",
              "[v_cel_c3_l1]+",
              "[v_cel_c3_l2]+",
              "[v_cel_c3_l3]+",
              "[v_cel_c3_l4]+",
              "[v_cel_c3_l5]+",
              "[v_cel_c3_l6]+",
              "[v_cel_c3_l7]+",
              "[v_cel_c3_l8]+",
              "[v_cel_c3_l9]+",
              "[v_cel_c3_l10]+",
              "[v_cel_c3_l11]+",
              "[v_cel_c3_l12]+",
              "[v_cel_c3_l13]+",
              "[v_cel_c3_l14]+",
              "[v_cel_c3_l15]+",
              "[v_cel_c3_l16]+",
              "[v_cel_c3_l17]+",
              "[v_cel_c3_l18]"
            ],
            "formatString": "#,0",
            "lineageTag": "046aafb2-ede4-444f-b7c4-04479c31e9b7"
          },
          {
            "name": "c4_total",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Carteira - Total geral",
            "expression": [
              "",
              "[v_cel_c4_l1]+",
              "[v_cel_c4_l2]+",
              "[v_cel_c4_l3]+",
              "[v_cel_c4_l4]+",
              "[v_cel_c4_l5]+",
              "[v_cel_c4_l6]+",
              "[v_cel_c4_l7]+",
              "[v_cel_c4_l8]+",
              "[v_cel_c4_l9]+",
              "[v_cel_c4_l10]+",
              "[v_cel_c4_l11]+",
              "[v_cel_c4_l12]+",
              "[v_cel_c4_l13]+",
              "[v_cel_c4_l14]+",
              "[v_cel_c4_l15]+",
              "[v_cel_c4_l16]+",
              "[v_cel_c4_l17]+",
              "[v_cel_c4_l18]"
            ],
            "formatString": "#,0",
            "lineageTag": "433fc349-051b-41c5-9fb6-9e88282d26cb"
          },
          {
            "name": "c5_total",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Carteira - Total geral",
            "expression": [
              "",
              "[v_cel_c5_l1]+",
              "[v_cel_c5_l2]+",
              "[v_cel_c5_l3]+",
              "[v_cel_c5_l4]+",
              "[v_cel_c5_l5]+",
              "[v_cel_c5_l6]+",
              "[v_cel_c5_l7]+",
              "[v_cel_c5_l8]+",
              "[v_cel_c5_l9]+",
              "[v_cel_c5_l10]+",
              "[v_cel_c5_l11]+",
              "[v_cel_c5_l12]+",
              "[v_cel_c5_l13]+",
              "[v_cel_c5_l14]+",
              "[v_cel_c5_l15]+",
              "[v_cel_c5_l16]+",
              "[v_cel_c5_l17]+",
              "[v_cel_c5_l18]"
            ],
            "formatString": "#,0",
            "lineageTag": "323ef9c6-89c1-47f3-89f4-c56ee204d668"
          },
          {
            "name": "c6_total",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Carteira - Total geral",
            "expression": [
              "",
              "[v_cel_c6_l1]+",
              "[v_cel_c6_l2]+",
              "[v_cel_c6_l3]+",
              "[v_cel_c6_l4]+",
              "[v_cel_c6_l5]+",
              "[v_cel_c6_l6]+",
              "[v_cel_c6_l7]+",
              "[v_cel_c6_l8]+",
              "[v_cel_c6_l9]+",
              "[v_cel_c6_l10]+",
              "[v_cel_c6_l11]+",
              "[v_cel_c6_l12]+",
              "[v_cel_c6_l13]+",
              "[v_cel_c6_l14]+",
              "[v_cel_c6_l15]+",
              "[v_cel_c6_l16]+",
              "[v_cel_c6_l17]+",
              "[v_cel_c6_l18]"
            ],
            "formatString": "#,0",
            "lineageTag": "26276931-aca1-4548-8e56-4b2a2606a30d"
          },
          {
            "name": "c7_total",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Carteira - Total geral",
            "expression": [
              "",
              "[v_cel_c7_l1]+",
              "[v_cel_c7_l2]+",
              "[v_cel_c7_l3]+",
              "[v_cel_c7_l4]+",
              "[v_cel_c7_l5]+",
              "[v_cel_c7_l6]+",
              "[v_cel_c7_l7]+",
              "[v_cel_c7_l8]+",
              "[v_cel_c7_l9]+",
              "[v_cel_c7_l10]+",
              "[v_cel_c7_l11]+",
              "[v_cel_c7_l12]+",
              "[v_cel_c7_l13]+",
              "[v_cel_c7_l14]+",
              "[v_cel_c7_l15]+",
              "[v_cel_c7_l16]+",
              "[v_cel_c7_l17]+",
              "[v_cel_c7_l18]"
            ],
            "formatString": "#,0",
            "lineageTag": "bb6fda65-f745-4e79-b34d-2476f62557e0"
          },
          {
            "name": "c8_total",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Carteira - Total geral",
            "expression": [
              "",
              "[v_cel_c8_l1]+",
              "[v_cel_c8_l2]+",
              "[v_cel_c8_l3]+",
              "[v_cel_c8_l4]+",
              "[v_cel_c8_l5]+",
              "[v_cel_c8_l6]+",
              "[v_cel_c8_l7]+",
              "[v_cel_c8_l8]+",
              "[v_cel_c8_l9]+",
              "[v_cel_c8_l10]+",
              "[v_cel_c8_l11]+",
              "[v_cel_c8_l12]+",
              "[v_cel_c8_l13]+",
              "[v_cel_c8_l14]+",
              "[v_cel_c8_l15]+",
              "[v_cel_c8_l16]+",
              "[v_cel_c8_l17]+",
              "[v_cel_c8_l18]"
            ],
            "formatString": "#,0",
            "lineageTag": "99f757d9-07a6-4595-b001-26892b6f5a71"
          },
          {
            "name": "total_geral",
            "displayFolder": "Carteira - Total geral",
            "expression": [
              "",
              "[c1_total]+",
              "[c2_total]+",
              "[c3_total]+",
              "[c4_total]+",
              "[c5_total]+",
              "[c6_total]+",
              "[c7_total]+",
              "[c8_total]"
            ],
            "formatString": "#,0",
            "lineageTag": "7fe5679a-b3f6-464b-957d-bbffb20301a3"
          },
          {
            "name": "released_saldo_<>vvlog",
            "displayFolder": "Released",
            "expression": [
              "",
              "SUM(tDesmarcados[Total Fracionado])"
            ],
            "formatString": "0",
            "lineageTag": "8f730909-7c79-40e2-82d6-a2587bae2240"
          },
          {
            "name": "released_saldo_<>br",
            "displayFolder": "Released",
            "expression": [
              "",
              "SUM(tDesmarcados[Total VVLOG])"
            ],
            "formatString": "0",
            "lineageTag": "a451ba30-90d0-4977-b53c-2d648fbeb356"
          },
          {
            "name": "released_vencidos<>vvlog",
            "displayFolder": "Released",
            "expression": [
              "",
              "var a = ",
              "CALCULATE([released_saldo_<>vvlog],",
              "tDesmarcados[Column0] = \"Vencidos\")",
              "",
              "var b = ",
              "IF(ISBLANK(a),\"0\",a)",
              "",
              "RETURN b"
            ],
            "formatString": "0",
            "lineageTag": "c7d7e6d1-fa71-4605-9652-5604bb4d280c"
          },
          {
            "name": "released_vence_hoje<>vvlog",
            "displayFolder": "Released",
            "expression": [
              "",
              "",
              "var a =",
              "CALCULATE([released_saldo_<>vvlog],",
              "tDesmarcados[Column0] = \"Vence Hoje\")",
              "",
              "var b = IF(ISBLANK(a),\"0\",a)",
              "",
              "RETURN b"
            ],
            "formatString": "0",
            "lineageTag": "106d950c-515a-458d-ba8c-be29c40db7f6"
          },
          {
            "name": "released_d+1_<>vvlog",
            "displayFolder": "Released",
            "expression": [
              "",
              "var a = ",
              "CALCULATE([released_saldo_<>vvlog],",
              "tDesmarcados[Column0] = \"D+1\")",
              "",
              "var b = IF(ISBLANK(a),\"0\",a)",
              "",
              "RETURN b"
            ],
            "formatString": "0",
            "lineageTag": "6bc886b8-aeea-41ad-8584-edff90938bc8"
          },
          {
            "name": "released_d+2_<>vvlog",
            "displayFolder": "Released",
            "expression": [
              "",
              "",
              "var a = ",
              "CALCULATE([released_saldo_<>vvlog],",
              "tDesmarcados[Column0] = \"D+2\" || tDesmarcados[Column0] = \">D+2\")",
              "",
              "var b = IF(ISBLANK(a),\"0\",a)",
              "",
              "RETURN b"
            ],
            "formatString": "0",
            "lineageTag": "0574da31-96d2-4c8b-ad95-f9f66d67afb4"
          },
          {
            "name": "released_vencidos_<>br",
            "displayFolder": "Released",
            "expression": [
              "",
              "",
              "var a = ",
              "CALCULATE([released_saldo_<>br],",
              "tDesmarcados[Column0] = \"Vencidos\")",
              "",
              "var b = IF(ISBLANK(a),\"0\",a)",
              "",
              "RETURN b"
            ],
            "formatString": "0",
            "lineageTag": "2ee36b8d-625c-4367-9e2a-4e4e7c325c5e"
          },
          {
            "name": "released_vence_hoje_<>br",
            "displayFolder": "Released",
            "expression": [
              "",
              "",
              "var a = ",
              "CALCULATE([released_saldo_<>br],",
              "tDesmarcados[Column0] = \"Vence Hoje\")",
              "",
              "var b = IF(ISBLANK(a),\"0\",a)",
              "",
              "RETURN b"
            ],
            "formatString": "0",
            "lineageTag": "09741210-8536-4b35-bacf-5b4563b05c38"
          },
          {
            "name": "released_d+1_<>br",
            "displayFolder": "Released",
            "expression": [
              "",
              "",
              "var a = ",
              "CALCULATE([released_saldo_<>br],",
              "tDesmarcados[Column0] = \"D+1\")",
              "",
              "var b = IF(ISBLANK(a),\"0\",a)",
              "",
              "RETURN b"
            ],
            "formatString": "0",
            "lineageTag": "2b72a193-e994-426e-82be-75e805271e8d"
          },
          {
            "name": "released_d+2_<>br",
            "displayFolder": "Released",
            "expression": [
              "",
              "",
              "var a = ",
              "CALCULATE([released_saldo_<>br],",
              "tDesmarcados[Column0] = \"D+2\" || tDesmarcados[Column0] = \" >D+2\")",
              "var b = IF(ISBLANK(a),\"0\",a)",
              "",
              "RETURN b"
            ],
            "formatString": "0",
            "lineageTag": "7b6b2a95-d2b5-41d5-ac8d-26e8927c9ce5"
          },
          {
            "name": "acomp_dia",
            "displayFolder": "Outros",
            "expression": [
              "",
              "VAR DiaSemana = WEEKDAY(TODAY(), 2)",
              "RETURN ",
              "IF(",
              "    DiaSemana IN {6, 7},",
              "    \"Vence Segunda\",",
              "    \"Vence Hoje\"",
              ")",
              ""
            ],
            "lineageTag": "905655bf-ea80-44da-a220-4f3842681014"
          },
          {
            "name": "zero",
            "displayFolder": "Outros",
            "expression": "0",
            "formatString": "0",
            "lineageTag": "8216a667-dbc2-444a-9f37-a06d7d325ab7"
          },
          {
            "name": "fat_dia_tratado",
            "displayFolder": "Outros",
            "expression": [
              "",
              "",
              "VAR A = FORMAT(TODAY() - 7,\"ddd\")",
              "",
              "VAR B = UPPER(LEFT(A,1))&LOWER(MID(A,2,LEN(A)))",
              "",
              "RETURN \"Faturamento de Ped. \"&B"
            ],
            "lineageTag": "1abbee9b-fdf9-4e0c-afb6-2122d8205f7e"
          },
          {
            "name": "ent_dia_tratado",
            "displayFolder": "Outros",
            "expression": [
              "",
              "",
              "VAR A = FORMAT(TODAY() - 7,\"ddd\")",
              "",
              "VAR B = UPPER(LEFT(A,1))&LOWER(MID(A,2,LEN(A)))",
              "",
              "RETURN \"Entrada de Ped. \"&B"
            ],
            "lineageTag": "aeb9a735-dfd2-4e76-9c17-f3cb63aaa65f"
          },
          {
            "name": "p_cel_c1_l1",
            "displayFolder": "Tabela Carteira Fracionada",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "TODAY() - 1",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP1976\",",
              "carteira[status] = \"Vencidos\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "1db549eb-b04e-4723-9360-207bd39e5b92"
          },
          {
            "name": "p_cel_c1_l2",
            "displayFolder": "Tabela Carteira Fracionada",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "TODAY() - 1",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2041\",",
              "carteira[status] = \"Vencidos\",",
              "carteira[   TRANSPORTADOR                         .2] = \"BRASIL WEB TRANSPORTES E LOGIS\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "a5a23d37-3089-4894-9904-c3476618a7ba"
          },
          {
            "name": "p_cel_c1_l3",
            "displayFolder": "Tabela Carteira Fracionada",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "TODAY() - 1",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2042\",",
              "carteira[status] = \"Vencidos\",",
              "carteira[   TRANSPORTADOR                         .2] = \"FAVORITA TRANSPORTES LTDA\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "6f0435fb-a6ef-4642-aaeb-bc205d20be2b"
          },
          {
            "name": "p_cel_c1_l4",
            "displayFolder": "Tabela Carteira Fracionada",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "TODAY() - 1",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2043\",",
              "carteira[status] = \"Vencidos\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "6f522ca1-f29c-4ab4-9979-3e413c7b7c3e"
          },
          {
            "name": "p_cel_c1_l5",
            "displayFolder": "Tabela Carteira Fracionada",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "TODAY() - 1",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2044\",",
              "carteira[status] = \"Vencidos\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "950c86ee-a014-4e69-a26e-79322532b140"
          },
          {
            "name": "p_c1_total",
            "displayFolder": "Tabela Carteira Fracionada",
            "expression": [
              "",
              "[p_cel_c1_l1]+",
              "[p_cel_c1_l2]+",
              "[p_cel_c1_l3]+",
              "[p_cel_c1_l4]+",
              "[p_cel_c1_l5]+",
              "[p_cel_c1_l6]+",
              "[p_cel_c1_l7]"
            ],
            "formatString": "#,0",
            "lineageTag": "786d51db-b1c2-4d5f-96d0-0baa7a57b1e5"
          },
          {
            "name": "p_cel_c2_l1",
            "displayFolder": "Tabela Carteira Fracionada",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "TODAY()",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP1976\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "9625aa1b-1bfe-4328-9e77-fc2b5aab44f7"
          },
          {
            "name": "p_cel_c2_l2",
            "displayFolder": "Tabela Carteira Fracionada",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "TODAY()",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2041\",",
              "carteira[data limite2] = data1,",
              "carteira[   TRANSPORTADOR                         .2] = \"BRASIL WEB TRANSPORTES E LOGIS\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "d78cbf02-1ee2-43db-ae29-e41bf719b6aa"
          },
          {
            "name": "p_cel_c2_l3",
            "displayFolder": "Tabela Carteira Fracionada",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "TODAY()",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2042\",",
              "carteira[data limite2] = data1,",
              "carteira[   TRANSPORTADOR                         .2] = \"FAVORITA TRANSPORTES LTDA\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "1757b43e-0c85-409b-b64e-2ebc526a3f07"
          },
          {
            "name": "p_cel_c2_l4",
            "displayFolder": "Tabela Carteira Fracionada",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "TODAY()",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2043\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "df5e4a8d-cd50-4302-99f1-6928282e2114"
          },
          {
            "name": "p_cel_c2_l5",
            "displayFolder": "Tabela Carteira Fracionada",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "TODAY()",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2044\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "a41816d5-66f3-467c-b95a-9241ee10b3d3"
          },
          {
            "name": "p_c2_total",
            "displayFolder": "Tabela Carteira Fracionada",
            "expression": [
              "",
              "[p_cel_c2_l1]+",
              "[p_cel_c2_l2]+",
              "[p_cel_c2_l3]+",
              "[p_cel_c2_l4]+",
              "[p_cel_c2_l5]+",
              "[p_cel_c2_l6]+",
              "[p_cel_c2_l7]"
            ],
            "formatString": "#,0",
            "lineageTag": "fe949806-628d-47c6-8d7f-a52a85791ecc"
          },
          {
            "name": "P_cel_c3_l1",
            "displayFolder": "Tabela Carteira Fracionada",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY(TODAY(), 1) = 6, ",
              "    TODAY() + 3, ",
              "    IF(",
              "        WEEKDAY(TODAY(), 1) = 7, ",
              "        TODAY() + 2, ",
              "        TODAY() + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP1976\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "0",
            "lineageTag": "0b23e4d8-3731-45dd-b97d-6e5a91e9799b"
          },
          {
            "name": "P_cel_c3_l2",
            "displayFolder": "Tabela Carteira Fracionada",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY(TODAY(), 1) = 6, ",
              "    TODAY() + 3, ",
              "    IF(",
              "        WEEKDAY(TODAY(), 1) = 7, ",
              "        TODAY() + 2, ",
              "        TODAY() + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2041\",",
              "carteira[   TRANSPORTADOR                         .2] = \"BRASIL WEB TRANSPORTES E LOGIS\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "31df74ac-ec82-476c-9f79-3beaa4bca3b5"
          },
          {
            "name": "P_cel_c3_l3",
            "displayFolder": "Tabela Carteira Fracionada",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY(TODAY(), 1) = 6, ",
              "    TODAY() + 3, ",
              "    IF(",
              "        WEEKDAY(TODAY(), 1) = 7, ",
              "        TODAY() + 2, ",
              "        TODAY() + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2042\",",
              "carteira[   TRANSPORTADOR                         .2] = \"FAVORITA TRANSPORTES LTDA\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "9f81d058-06ea-4d6e-97f2-6891f0c64ab1"
          },
          {
            "name": "P_cel_c3_l4",
            "displayFolder": "Tabela Carteira Fracionada",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY(TODAY(), 1) = 6, ",
              "    TODAY() + 3, ",
              "    IF(",
              "        WEEKDAY(TODAY(), 1) = 7, ",
              "        TODAY() + 2, ",
              "        TODAY() + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2043\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "733512cb-bb8b-4c43-92d4-73a145869ed0"
          },
          {
            "name": "P_cel_c3_l5",
            "displayFolder": "Tabela Carteira Fracionada",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY(TODAY(), 1) = 6, ",
              "    TODAY() + 3, ",
              "    IF(",
              "        WEEKDAY(TODAY(), 1) = 7, ",
              "        TODAY() + 2, ",
              "        TODAY() + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2044\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "ae0135d8-3b8a-4dc8-b827-9b0ebbd3f6ac"
          },
          {
            "name": "p_c3_total",
            "displayFolder": "Tabela Carteira Fracionada",
            "expression": [
              "",
              "[p_cel_c3_l1]+",
              "[p_cel_c3_l2]+",
              "[p_cel_c3_l3]+",
              "[p_cel_c3_l4]+",
              "[p_cel_c3_l5]+",
              "[p_cel_c3_l6]+",
              "[p_cel_c3_l7]"
            ],
            "formatString": "#,0",
            "lineageTag": "1d79a2e3-e015-4fd0-b435-f3942f6818ea"
          },
          {
            "name": "p_cel_c4_l1",
            "displayFolder": "Tabela Carteira Fracionada",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data3], 1) = 6, ",
              "    [data3] + 3, ",
              "    IF(",
              "        WEEKDAY([data3], 1) = 7, ",
              "        [data3] + 2, ",
              "        [data3] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP1976\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "5287e573-f06e-47c1-a239-aadde4d4e1fd"
          },
          {
            "name": "p_cel_c4_l2",
            "displayFolder": "Tabela Carteira Fracionada",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data3], 1) = 6, ",
              "    [data3] + 3, ",
              "    IF(",
              "        WEEKDAY([data3], 1) = 7, ",
              "        [data3] + 2, ",
              "        [data3] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2041\",",
              "carteira[data limite2] = data1,",
              "carteira[   TRANSPORTADOR                         .2] = \"BRASIL WEB TRANSPORTES E LOGIS\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "6908922b-8e80-4448-9779-bb4b66bccd6a"
          },
          {
            "name": "p_cel_c4_l3",
            "displayFolder": "Tabela Carteira Fracionada",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data3], 1) = 6, ",
              "    [data3] + 3, ",
              "    IF(",
              "        WEEKDAY([data3], 1) = 7, ",
              "        [data3] + 2, ",
              "        [data3] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2042\",",
              "carteira[data limite2] = data1,",
              "carteira[   TRANSPORTADOR                         .2] = \"FAVORITA TRANSPORTES LTDA\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "00cc04b0-555e-4e8b-8ce8-4a2aa8b7504d"
          },
          {
            "name": "p_cel_c4_l4",
            "displayFolder": "Tabela Carteira Fracionada",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data3], 1) = 6, ",
              "    [data3] + 3, ",
              "    IF(",
              "        WEEKDAY([data3], 1) = 7, ",
              "        [data3] + 2, ",
              "        [data3] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2043\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "0d1f4de5-7c07-412d-bd96-f8487fabb42f"
          },
          {
            "name": "p_cel_c4_l5",
            "displayFolder": "Tabela Carteira Fracionada",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data3], 1) = 6, ",
              "    [data3] + 3, ",
              "    IF(",
              "        WEEKDAY([data3], 1) = 7, ",
              "        [data3] + 2, ",
              "        [data3] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2044\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "46e7df34-b4be-48f9-879b-921a78d391d0"
          },
          {
            "name": "p_c4_total",
            "displayFolder": "Tabela Carteira Fracionada",
            "expression": [
              "",
              "[p_cel_c4_l1]+",
              "[p_cel_c4_l2]+",
              "[p_cel_c4_l3]+",
              "[p_cel_c4_l4]+",
              "[p_cel_c4_l5]"
            ],
            "formatString": "#,0",
            "lineageTag": "e9f55668-f417-441e-b4cf-d4d11a33e076"
          },
          {
            "name": "P_cel_c5_l1",
            "displayFolder": "Tabela Carteira Fracionada",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data4], 1) = 6, ",
              "    [data4] + 3, ",
              "    IF(",
              "        WEEKDAY([data4], 1) = 7, ",
              "        [data4] + 2, ",
              "        [data4] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP1976\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "144d8bab-9167-42d1-9c10-792766817d60"
          },
          {
            "name": "P_cel_c5_l2",
            "displayFolder": "Tabela Carteira Fracionada",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data4], 1) = 6, ",
              "    [data4] + 3, ",
              "    IF(",
              "        WEEKDAY([data4], 1) = 7, ",
              "        [data4] + 2, ",
              "        [data4] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2041\",",
              "carteira[data limite2] = data1,",
              "carteira[   TRANSPORTADOR                         .2] = \"BRASIL WEB TRANSPORTES E LOGIS\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "9fe21205-4492-4fb1-a29a-edf7d8afd28c"
          },
          {
            "name": "P_cel_c5_l3",
            "displayFolder": "Tabela Carteira Fracionada",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data4], 1) = 6, ",
              "    [data4] + 3, ",
              "    IF(",
              "        WEEKDAY([data4], 1) = 7, ",
              "        [data4] + 2, ",
              "        [data4] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2042\",",
              "carteira[data limite2] = data1,",
              "carteira[   TRANSPORTADOR                         .2] = \"FAVORITA TRANSPORTES LTDA\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "4099d3f7-87bf-4b81-9e1c-a5b118d7a48c"
          },
          {
            "name": "P_cel_c5_l4",
            "displayFolder": "Tabela Carteira Fracionada",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data4], 1) = 6, ",
              "    [data4] + 3, ",
              "    IF(",
              "        WEEKDAY([data4], 1) = 7, ",
              "        [data4] + 2, ",
              "        [data4] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2043\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "8e7180a2-da43-4f01-93f8-ad13ab44900d"
          },
          {
            "name": "P_cel_c5_l5",
            "displayFolder": "Tabela Carteira Fracionada",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data4], 1) = 6, ",
              "    [data4] + 3, ",
              "    IF(",
              "        WEEKDAY([data4], 1) = 7, ",
              "        [data4] + 2, ",
              "        [data4] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2044\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "6789e9c2-a485-48bd-a6d0-f809460a7078"
          },
          {
            "name": "p_c5_total",
            "displayFolder": "Tabela Carteira Fracionada",
            "expression": [
              "",
              "[p_cel_c5_l1]+",
              "[p_cel_c5_l2]+",
              "[p_cel_c5_l3]+",
              "[p_cel_c5_l4]+",
              "[p_cel_c5_l5]"
            ],
            "formatString": "#,0",
            "lineageTag": "47bbee53-7186-4ece-8fab-5de64de1961a"
          },
          {
            "name": "P_cel_c6_l1",
            "displayFolder": "Tabela Carteira Fracionada",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data5], 1) = 6, ",
              "    [data5] + 3, ",
              "    IF(",
              "        WEEKDAY([data5], 1) = 7, ",
              "        [data5] + 2, ",
              "        [data5] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP1976\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "08e5afba-c28a-4e28-aa1e-664a54c745ae"
          },
          {
            "name": "P_cel_c6_l2",
            "displayFolder": "Tabela Carteira Fracionada",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data5], 1) = 6, ",
              "    [data5] + 3, ",
              "    IF(",
              "        WEEKDAY([data5], 1) = 7, ",
              "        [data5] + 2, ",
              "        [data5] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2041\",",
              "carteira[data limite2] = data1,",
              "carteira[   TRANSPORTADOR                         .2] = \"BRASIL WEB TRANSPORTES E LOGIS\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "e177251a-0b4a-4e8e-a8e9-1eadad3de0db"
          },
          {
            "name": "P_cel_c6_l3",
            "displayFolder": "Tabela Carteira Fracionada",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data5], 1) = 6, ",
              "    [data5] + 3, ",
              "    IF(",
              "        WEEKDAY([data5], 1) = 7, ",
              "        [data5] + 2, ",
              "        [data5] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2042\",",
              "carteira[data limite2] = data1,",
              "carteira[   TRANSPORTADOR                         .2] = \"FAVORITA TRANSPORTES LTDA\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "84cfc798-5421-417c-81cc-7f9f4fbadde3"
          },
          {
            "name": "P_cel_c6_l4",
            "displayFolder": "Tabela Carteira Fracionada",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data5], 1) = 6, ",
              "    [data5] + 3, ",
              "    IF(",
              "        WEEKDAY([data5], 1) = 7, ",
              "        [data5] + 2, ",
              "        [data5] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2043\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "93e30c58-210e-41dd-930f-9cbfd733d675"
          },
          {
            "name": "P_cel_c6_l5",
            "displayFolder": "Tabela Carteira Fracionada",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data5], 1) = 6, ",
              "    [data5] + 3, ",
              "    IF(",
              "        WEEKDAY([data5], 1) = 7, ",
              "        [data5] + 2, ",
              "        [data5] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2044\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "882e3f48-fa9d-4e53-a08c-efbb942a9ade"
          },
          {
            "name": "p_c6_total",
            "displayFolder": "Tabela Carteira Fracionada",
            "expression": [
              "",
              "[p_cel_c6_l1]+",
              "[p_cel_c6_l2]+",
              "[p_cel_c6_l3]+",
              "[p_cel_c6_l4]+",
              "[p_cel_c6_l5]+",
              "[p_cel_c6_l6]+",
              "[p_cel_c6_l7]"
            ],
            "formatString": "#,0",
            "lineageTag": "2c180435-1451-43c7-928c-3dd70316949e"
          },
          {
            "name": "P_cel_c7_l1",
            "displayFolder": "Tabela Carteira Fracionada",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data6], 1) = 6, ",
              "    [data6] + 3, ",
              "    IF(",
              "        WEEKDAY([data6], 1) = 7, ",
              "        [data6] + 2, ",
              "        [data6] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP1976\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "bde6df59-c5d0-4d81-a9ca-737489949cfa"
          },
          {
            "name": "P_cel_c7_l2",
            "displayFolder": "Tabela Carteira Fracionada",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data6], 1) = 6, ",
              "    [data6] + 3, ",
              "    IF(",
              "        WEEKDAY([data6], 1) = 7, ",
              "        [data6] + 2, ",
              "        [data6] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2041\",",
              "carteira[data limite2] = data1,",
              "carteira[   TRANSPORTADOR                         .2] = \"BRASIL WEB TRANSPORTES E LOGIS\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "a9bd6d24-f82e-41b6-95a0-a60d1b9fc992"
          },
          {
            "name": "P_cel_c7_l3",
            "displayFolder": "Tabela Carteira Fracionada",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data6], 1) = 6, ",
              "    [data6] + 3, ",
              "    IF(",
              "        WEEKDAY([data6], 1) = 7, ",
              "        [data6] + 2, ",
              "        [data6] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2042\",",
              "carteira[data limite2] = data1,",
              "carteira[   TRANSPORTADOR                         .2] = \"FAVORITA TRANSPORTES LTDA\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "f3288aff-2a97-4d83-9519-85d55ea0c5ea"
          },
          {
            "name": "P_cel_c7_l4",
            "displayFolder": "Tabela Carteira Fracionada",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data6], 1) = 6, ",
              "    [data6] + 3, ",
              "    IF(",
              "        WEEKDAY([data6], 1) = 7, ",
              "        [data6] + 2, ",
              "        [data6] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2043\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "892cc169-d16e-4ca3-aa12-33d0ea41dc4c"
          },
          {
            "name": "P_cel_c7_l5",
            "displayFolder": "Tabela Carteira Fracionada",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data6], 1) = 6, ",
              "    [data6] + 3, ",
              "    IF(",
              "        WEEKDAY([data6], 1) = 7, ",
              "        [data6] + 2, ",
              "        [data6] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2044\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "f9a8eb66-6f01-4616-b882-cad4d0192acf"
          },
          {
            "name": "p_c7_total",
            "displayFolder": "Tabela Carteira Fracionada",
            "expression": [
              "",
              "[p_cel_c7_l1]+",
              "[p_cel_c7_l2]+",
              "[p_cel_c7_l3]+",
              "[p_cel_c7_l4]+",
              "[p_cel_c7_l5]+",
              "[p_cel_c7_l6]+",
              "[p_cel_c7_l7]"
            ],
            "formatString": "0",
            "lineageTag": "d3e4237b-60f1-430c-a168-64e878b80e70"
          },
          {
            "name": "P_cel_c8_l1",
            "displayFolder": "Tabela Carteira Fracionada",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "    IF(",
              "        WEEKDAY([data7], 1) = 6, ",
              "        [data7] + 3, ",
              "        IF(",
              "            WEEKDAY([data7], 1) = 7, ",
              "            [data7] + 2, ",
              "            [data7] + 1",
              "        )",
              "    )",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP1976\",",
              "carteira[data limite2] >= data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "35a6e72a-98a1-446a-84ab-96526a065775"
          },
          {
            "name": "P_cel_c8_l2",
            "displayFolder": "Tabela Carteira Fracionada",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "    IF(",
              "        WEEKDAY([data7], 1) = 6, ",
              "        [data7] + 3, ",
              "        IF(",
              "            WEEKDAY([data7], 1) = 7, ",
              "            [data7] + 2, ",
              "            [data7] + 1",
              "        )",
              "    )",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2041\",",
              "carteira[data limite2] >= data1,",
              "carteira[   TRANSPORTADOR                         .2] = \"BRASIL WEB TRANSPORTES E LOGIS\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "7b6bc23b-10f2-4d28-9801-21cc11db7f77"
          },
          {
            "name": "P_cel_c8_l3",
            "displayFolder": "Tabela Carteira Fracionada",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "    IF(",
              "        WEEKDAY([data7], 1) = 6, ",
              "        [data7] + 3, ",
              "        IF(",
              "            WEEKDAY([data7], 1) = 7, ",
              "            [data7] + 2, ",
              "            [data7] + 1",
              "        )",
              "    )",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2042\",",
              "carteira[data limite2] >= data1,",
              "carteira[   TRANSPORTADOR                         .2] = \"FAVORITA TRANSPORTES LTDA\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "1bc75fee-907e-4eb8-8ff9-83f795f414f8"
          },
          {
            "name": "P_cel_c8_l4",
            "displayFolder": "Tabela Carteira Fracionada",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "    IF(",
              "        WEEKDAY([data7], 1) = 6, ",
              "        [data7] + 3, ",
              "        IF(",
              "            WEEKDAY([data7], 1) = 7, ",
              "            [data7] + 2, ",
              "            [data7] + 1",
              "        )",
              "    )",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2043\",",
              "carteira[data limite2] >= data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "dfed4c43-554f-4143-9e52-2c46f0f8f127"
          },
          {
            "name": "P_cel_c8_l5",
            "displayFolder": "Tabela Carteira Fracionada",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "    IF(",
              "        WEEKDAY([data7], 1) = 6, ",
              "        [data7] + 3, ",
              "        IF(",
              "            WEEKDAY([data7], 1) = 7, ",
              "            [data7] + 2, ",
              "            [data7] + 1",
              "        )",
              "    )",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2044\",",
              "carteira[data limite2] >= data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "#,0",
            "lineageTag": "ed7da0c2-6386-45e7-97e1-a185c48c10e3"
          },
          {
            "name": "p_c8_total",
            "displayFolder": "Tabela Carteira Fracionada",
            "expression": [
              "",
              "[p_cel_c8_l1]+",
              "[p_cel_c8_l2]+",
              "[p_cel_c8_l3]+",
              "[p_cel_c8_l4]+",
              "[p_cel_c8_l5]+",
              "[p_cel_c8_l6]+",
              "[p_cel_c8_l7]"
            ],
            "formatString": "#,0",
            "lineageTag": "8d8865ef-7c03-4382-80c4-a19988716422"
          },
          {
            "name": "p_cel_c9_l1",
            "displayFolder": "Tabela Carteira Fracionada",
            "expression": [
              "",
              "[p_cel_c1_l1]+",
              "[p_cel_c2_l1]+",
              "[p_cel_c3_l1]+",
              "[p_cel_c4_l1]+",
              "[p_cel_c5_l1]+",
              "[p_cel_c6_l1]+",
              "[p_cel_c7_l1]+",
              "[p_cel_c8_l1]",
              "",
              ""
            ],
            "formatString": "0",
            "lineageTag": "af6a522d-42e9-41be-a3fd-5403debfd2f2"
          },
          {
            "name": "p_cel_c9_l2",
            "displayFolder": "Tabela Carteira Fracionada",
            "expression": [
              "",
              "[p_cel_c1_l2]+",
              "[p_cel_c2_l2]+",
              "[p_cel_c3_l2]+",
              "[p_cel_c4_l2]+",
              "[p_cel_c5_l2]+",
              "[p_cel_c6_l2]+",
              "[p_cel_c7_l2]+",
              "[p_cel_c8_l2]",
              ""
            ],
            "formatString": "#,0",
            "lineageTag": "a6cf6159-b687-4464-9c8d-f5dffe7da71c"
          },
          {
            "name": "p_cel_c9_l3",
            "displayFolder": "Tabela Carteira Fracionada",
            "expression": [
              "",
              "[p_cel_c1_l3]+",
              "[p_cel_c2_l3]+",
              "[p_cel_c3_l3]+",
              "[p_cel_c4_l3]+",
              "[p_cel_c5_l3]+",
              "[p_cel_c6_l3]+",
              "[p_cel_c7_l3]+",
              "[p_cel_c8_l3]",
              ""
            ],
            "formatString": "#,0",
            "lineageTag": "0a2473a6-34f4-44b5-a46a-486c1ca1ae93"
          },
          {
            "name": "p_cel_c9_l4",
            "displayFolder": "Tabela Carteira Fracionada",
            "expression": [
              "",
              "[p_cel_c1_l4]+",
              "[p_cel_c2_l4]+",
              "[p_cel_c3_l4]+",
              "[p_cel_c4_l4]+",
              "[p_cel_c5_l4]+",
              "[p_cel_c6_l4]+",
              "[p_cel_c7_l4]+",
              "[p_cel_c8_l4]",
              ""
            ],
            "formatString": "0",
            "lineageTag": "5e43aa18-b384-40d7-9b6f-da9bc1174ee5"
          },
          {
            "name": "p_cel_c9_l5",
            "displayFolder": "Tabela Carteira Fracionada",
            "expression": [
              "",
              "[p_cel_c1_l5]+",
              "[p_cel_c2_l5]+",
              "[p_cel_c3_l5]+",
              "[p_cel_c4_l5]+",
              "[p_cel_c5_l5]+",
              "[p_cel_c6_l5]+",
              "[p_cel_c7_l5]+",
              "[p_cel_c8_l5]",
              ""
            ],
            "formatString": "#,0",
            "lineageTag": "9bbcbb56-1ec8-44f5-8e70-d5e8f4b986e1"
          },
          {
            "name": "totalgeral",
            "displayFolder": "Tabela Carteira Fracionada",
            "expression": [
              "",
              "[p_cel_c9_l1]+",
              "[p_cel_c9_l2]+",
              "[p_cel_c9_l3]+",
              "[p_cel_c9_l4]+",
              "[p_cel_c9_l5]+",
              "[p_cel_c9_l6]+",
              "[p_cel_c9_l7]"
            ],
            "formatString": "#,0",
            "lineageTag": "d6c5c869-e9bf-4205-895a-966338cf7e0a"
          },
          {
            "name": "p_cel_c1_l1_c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "TODAY() - 1",
              "",
              "VAR logica = ",
              "CALCULATE(SUM(carteira[CBG_PV   ]),",
              "carteira[ROTA] = \"SP1976\",",
              "carteira[status] = \"Vencidos\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "lineageTag": "67c7d4d8-0f6e-4083-ab9a-9569026f1b2f"
          },
          {
            "name": "p_cel_c1_l2_c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "TODAY() - 1",
              "",
              "VAR logica = ",
              "CALCULATE(SUM(carteira[CBG_PV   ]),",
              "carteira[ROTA] = \"SP2041\",",
              "carteira[status] = \"Vencidos\",",
              "carteira[   TRANSPORTADOR                         .2] = \"BRASIL WEB TRANSPORTES E LOGIS\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "lineageTag": "8656326c-b446-445e-ac9c-53b2adf67908"
          },
          {
            "name": "p_cel_c1_l3_C",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "TODAY() - 1",
              "",
              "VAR logica = ",
              "CALCULATE(SUM(carteira[CBG_PV   ]),",
              "carteira[ROTA] = \"SP2042\",",
              "carteira[status] = \"Vencidos\",",
              "carteira[   TRANSPORTADOR                         .2] = \"FAVORITA TRANSPORTES LTDA\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "lineageTag": "94610e48-d0ea-4a4f-986b-c3896889363c"
          },
          {
            "name": "p_cel_c1_l4_c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "TODAY() - 1",
              "",
              "VAR logica = ",
              "CALCULATE(SUM(carteira[CBG_PV   ]),",
              "carteira[ROTA] = \"SP2043\",",
              "carteira[status] = \"Vencidos\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "lineageTag": "10b117f0-24a4-4b00-a102-70011ffd50fd"
          },
          {
            "name": "p_cel_c1_l5_c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "TODAY() - 1",
              "",
              "VAR logica = ",
              "CALCULATE(SUM(carteira[CBG_PV   ]),",
              "carteira[ROTA] = \"SP2044\",",
              "carteira[status] = \"Vencidos\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "lineageTag": "8d72d4f9-54d4-4282-8efb-0db769566ca9"
          },
          {
            "name": "p_c1_total_c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "[p_cel_c1_l1_c]+",
              "[p_cel_c1_l2_c]+",
              "[p_cel_c1_l3_c]+",
              "[p_cel_c1_l4_c]+",
              "[p_cel_c1_l5_c]+",
              "[p_cel_c1_l6_c]+",
              "[p_cel_c1_l7_c]"
            ],
            "lineageTag": "73ee5d7f-3c92-45f4-a83d-1b681f9420bf"
          },
          {
            "name": "p_cel_c2_l1_c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "TODAY()",
              "",
              "VAR logica = ",
              "CALCULATE(SUM(carteira[CBG_PV   ]),",
              "carteira[ROTA] = \"SP1976\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "lineageTag": "63fcfe4f-98b5-4e23-8bd4-cbc8cbbe5ff3"
          },
          {
            "name": "p_cel_c2_l2_c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "TODAY()",
              "",
              "VAR logica = ",
              "CALCULATE(SUM(carteira[CBG_PV   ]),",
              "carteira[ROTA] = \"SP2041\",",
              "carteira[data limite2] = data1,",
              "carteira[   TRANSPORTADOR                         .2] = \"BRASIL WEB TRANSPORTES E LOGIS\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "lineageTag": "075a1c31-48f0-4409-9ba9-313817ce0b9a"
          },
          {
            "name": "p_cel_c2_l3_c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "TODAY()",
              "",
              "VAR logica = ",
              "CALCULATE(SUM(carteira[CBG_PV   ]),",
              "carteira[ROTA] = \"SP2042\",",
              "carteira[data limite2] = data1,",
              "carteira[   TRANSPORTADOR                         .2] = \"FAVORITA TRANSPORTES LTDA\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "lineageTag": "d25cdc5e-5786-4a0e-ae4b-28be74e48fd6"
          },
          {
            "name": "p_cel_c2_l4_c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "TODAY()",
              "",
              "VAR logica = ",
              "CALCULATE(SUM(carteira[CBG_PV   ]),",
              "carteira[ROTA] = \"SP2043\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "lineageTag": "3b7e0e75-516b-44cd-9c43-cab6b00bef7f"
          },
          {
            "name": "p_cel_c2_l5_c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "TODAY()",
              "",
              "VAR logica = ",
              "CALCULATE(SUM(carteira[CBG_PV   ]),",
              "carteira[ROTA] = \"SP2044\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "lineageTag": "9e8c324f-0af5-4760-81f7-d8e4afdef0bc"
          },
          {
            "name": "p_c2_total_c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "[p_cel_c2_l1_c]+",
              "[p_cel_c2_l2_c]+",
              "[p_cel_c2_l3_c]+",
              "[p_cel_c2_l4_c]+",
              "[p_cel_c2_l5_c]+",
              "[p_cel_c2_l6_c]+",
              "[p_cel_c2_l7_c]"
            ],
            "lineageTag": "75d0fbfa-d012-424b-8776-8b499651f355"
          },
          {
            "name": "P_cel_c3_l1_c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY(TODAY(), 1) = 6, ",
              "    TODAY() + 3, ",
              "    IF(",
              "        WEEKDAY(TODAY(), 1) = 7, ",
              "        TODAY() + 2, ",
              "        TODAY() + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE(SUM(carteira[CBG_PV   ]),",
              "carteira[ROTA] = \"SP1976\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "lineageTag": "cceb7ba9-681b-4ace-8f39-a1e28f8f2e28"
          },
          {
            "name": "P_cel_c3_l2_c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY(TODAY(), 1) = 6, ",
              "    TODAY() + 3, ",
              "    IF(",
              "        WEEKDAY(TODAY(), 1) = 7, ",
              "        TODAY() + 2, ",
              "        TODAY() + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE(SUM(carteira[CBG_PV   ]),",
              "carteira[ROTA] = \"SP2041\",",
              "carteira[   TRANSPORTADOR                         .2] = \"BRASIL WEB TRANSPORTES E LOGIS\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "lineageTag": "653c32a7-7496-45b3-890b-5c58a95e762d"
          },
          {
            "name": "P_cel_c3_l3_c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY(TODAY(), 1) = 6, ",
              "    TODAY() + 3, ",
              "    IF(",
              "        WEEKDAY(TODAY(), 1) = 7, ",
              "        TODAY() + 2, ",
              "        TODAY() + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE(SUM(carteira[CBG_PV   ]),",
              "carteira[ROTA] = \"SP2042\",",
              "carteira[   TRANSPORTADOR                         .2] = \"FAVORITA TRANSPORTES LTDA\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "lineageTag": "61f837ed-52e2-4b93-9ce6-8039ee4dc1e2"
          },
          {
            "name": "P_cel_c3_l4_c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY(TODAY(), 1) = 6, ",
              "    TODAY() + 3, ",
              "    IF(",
              "        WEEKDAY(TODAY(), 1) = 7, ",
              "        TODAY() + 2, ",
              "        TODAY() + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE(SUM(carteira[CBG_PV   ]),",
              "carteira[ROTA] = \"SP2043\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "lineageTag": "04b95685-f399-4030-a227-1d4125d9fa72"
          },
          {
            "name": "P_cel_c3_l5_c",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY(TODAY(), 1) = 6, ",
              "    TODAY() + 3, ",
              "    IF(",
              "        WEEKDAY(TODAY(), 1) = 7, ",
              "        TODAY() + 2, ",
              "        TODAY() + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE(SUM(carteira[CBG_PV   ]),",
              "carteira[ROTA] = \"SP2044\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "0",
            "lineageTag": "30bfa5d5-2072-4e4b-90ad-8fe6c821f210"
          },
          {
            "name": "p_c3_total_c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "[p_cel_c3_l1_c]+",
              "[p_cel_c3_l2_c]+",
              "[p_cel_c3_l3_c]+",
              "[p_cel_c3_l4_c]+",
              "[p_cel_c3_l5_c]+",
              "[P_cel_c3_l6_c]+",
              "[P_cel_c3_l7_c]"
            ],
            "lineageTag": "41023a55-5592-4812-bca5-1710596b16e2"
          },
          {
            "name": "p_cel_c4_l1_c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data3], 1) = 6, ",
              "    [data3] + 3, ",
              "    IF(",
              "        WEEKDAY([data3], 1) = 7, ",
              "        [data3] + 2, ",
              "        [data3] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE(SUM(carteira[CBG_PV   ]),",
              "carteira[ROTA] = \"SP1976\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "lineageTag": "bb3a1704-9c21-4b29-8d89-13bc6657f4f5"
          },
          {
            "name": "p_cel_c4_l2_c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data3], 1) = 6, ",
              "    [data3] + 3, ",
              "    IF(",
              "        WEEKDAY([data3], 1) = 7, ",
              "        [data3] + 2, ",
              "        [data3] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE(SUM(carteira[CBG_PV   ]),",
              "carteira[ROTA] = \"SP2041\",",
              "carteira[data limite2] = data1,",
              "carteira[   TRANSPORTADOR                         .2] = \"BRASIL WEB TRANSPORTES E LOGIS\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "lineageTag": "174efa85-9ac5-46ab-b4f0-fef851de4145"
          },
          {
            "name": "p_cel_c4_l3_c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data3], 1) = 6, ",
              "    [data3] + 3, ",
              "    IF(",
              "        WEEKDAY([data3], 1) = 7, ",
              "        [data3] + 2, ",
              "        [data3] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE(SUM(carteira[CBG_PV   ]),",
              "carteira[ROTA] = \"SP2042\",",
              "carteira[data limite2] = data1,",
              "carteira[   TRANSPORTADOR                         .2] = \"FAVORITA TRANSPORTES LTDA\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "lineageTag": "71b60ef4-ccc5-406e-945f-9fd6b59d641e"
          },
          {
            "name": "p_cel_c4_l4_c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data3], 1) = 6, ",
              "    [data3] + 3, ",
              "    IF(",
              "        WEEKDAY([data3], 1) = 7, ",
              "        [data3] + 2, ",
              "        [data3] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE(SUM(carteira[CBG_PV   ]),",
              "carteira[ROTA] = \"SP2043\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "lineageTag": "427d6c34-a8c2-4164-acd5-b998cd906ae8"
          },
          {
            "name": "p_cel_c4_l7",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data3], 1) = 6, ",
              "    [data3] + 3, ",
              "    IF(",
              "        WEEKDAY([data3], 1) = 7, ",
              "        [data3] + 2, ",
              "        [data3] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE(SUM(carteira[CBG_PV   ]),",
              "carteira[ROTA] = \"SP2044\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "lineageTag": "7bd4dfb4-c975-427b-afcf-64c600db1a01"
          },
          {
            "name": "p_c4_total_c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "[p_cel_c4_l1_c]+",
              "[p_cel_c4_l2_c]+",
              "[p_cel_c4_l3_c]+",
              "[p_cel_c4_l4_c]+",
              "[p_cel_c4_l7]+",
              "[p_cel_c4_l8]+",
              "[p_cel_c4_l9]"
            ],
            "lineageTag": "2e7899ab-ff27-459a-976a-040ee316a932"
          },
          {
            "name": "P_cel_c5_l1_c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data4], 1) = 6, ",
              "    [data4] + 3, ",
              "    IF(",
              "        WEEKDAY([data4], 1) = 7, ",
              "        [data4] + 2, ",
              "        [data4] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE(SUM(carteira[CBG_PV   ]),",
              "carteira[ROTA] = \"SP1976\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "lineageTag": "3f525692-6bae-4050-be9c-30174a525569"
          },
          {
            "name": "P_cel_c5_l2_c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data4], 1) = 6, ",
              "    [data4] + 3, ",
              "    IF(",
              "        WEEKDAY([data4], 1) = 7, ",
              "        [data4] + 2, ",
              "        [data4] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE(SUM(carteira[CBG_PV   ]),",
              "carteira[ROTA] = \"SP2041\",",
              "carteira[data limite2] = data1,",
              "carteira[   TRANSPORTADOR                         .2] = \"BRASIL WEB TRANSPORTES E LOGIS\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "lineageTag": "1384960d-5e21-4bde-99a6-3ddcac2a9dce"
          },
          {
            "name": "P_cel_c5_l3_c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data4], 1) = 6, ",
              "    [data4] + 3, ",
              "    IF(",
              "        WEEKDAY([data4], 1) = 7, ",
              "        [data4] + 2, ",
              "        [data4] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE(SUM(carteira[CBG_PV   ]),",
              "carteira[ROTA] = \"SP2042\",",
              "carteira[data limite2] = data1,",
              "carteira[   TRANSPORTADOR                         .2] = \"FAVORITA TRANSPORTES LTDA\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "lineageTag": "dde8323c-6b75-4ed0-ac00-743b70b6e619"
          },
          {
            "name": "P_cel_c5_l4_c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data4], 1) = 6, ",
              "    [data4] + 3, ",
              "    IF(",
              "        WEEKDAY([data4], 1) = 7, ",
              "        [data4] + 2, ",
              "        [data4] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE(SUM(carteira[CBG_PV   ]),",
              "carteira[ROTA] = \"SP2043\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "lineageTag": "0cd1281a-901f-4d8a-b860-0636f476de67"
          },
          {
            "name": "P_cel_c5_l5_c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data4], 1) = 6, ",
              "    [data4] + 3, ",
              "    IF(",
              "        WEEKDAY([data4], 1) = 7, ",
              "        [data4] + 2, ",
              "        [data4] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE(SUM(carteira[CBG_PV   ]),",
              "carteira[ROTA] = \"SP2044\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "lineageTag": "44aaf58a-edb4-4ba9-919e-f5ea181695c5"
          },
          {
            "name": "p_c5_total_c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "[p_cel_c5_l1_c]+",
              "[p_cel_c5_l2_c]+",
              "[p_cel_c5_l3_c]+",
              "[p_cel_c5_l4_c]+",
              "[p_cel_c5_l5_c]+",
              "[P_cel_c5_l6_c]+",
              "[P_cel_c5_l7_c]"
            ],
            "lineageTag": "988d4c0b-efe3-4f5e-b7aa-e454b447b27c"
          },
          {
            "name": "P_cel_c6_l1_c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data5], 1) = 6, ",
              "    [data5] + 3, ",
              "    IF(",
              "        WEEKDAY([data5], 1) = 7, ",
              "        [data5] + 2, ",
              "        [data5] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE(SUM(carteira[CBG_PV   ]),",
              "carteira[ROTA] = \"SP1976\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "lineageTag": "5e5a7144-ccd4-4996-bf49-4721c15e0b75"
          },
          {
            "name": "P_cel_c6_l2_c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data5], 1) = 6, ",
              "    [data5] + 3, ",
              "    IF(",
              "        WEEKDAY([data5], 1) = 7, ",
              "        [data5] + 2, ",
              "        [data5] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE(SUM(carteira[CBG_PV   ]),",
              "carteira[ROTA] = \"SP2041\",",
              "carteira[data limite2] = data1,",
              "carteira[   TRANSPORTADOR                         .2] = \"BRASIL WEB TRANSPORTES E LOGIS\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "lineageTag": "067d07a3-781c-4fa5-aab3-e7121e6a22b4"
          },
          {
            "name": "P_cel_c6_l3_c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data5], 1) = 6, ",
              "    [data5] + 3, ",
              "    IF(",
              "        WEEKDAY([data5], 1) = 7, ",
              "        [data5] + 2, ",
              "        [data5] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE(SUM(carteira[CBG_PV   ]),",
              "carteira[ROTA] = \"SP2042\",",
              "carteira[data limite2] = data1,",
              "carteira[   TRANSPORTADOR                         .2] = \"FAVORITA TRANSPORTES LTDA\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "lineageTag": "72ac489e-673a-48b2-99de-3739af31b498"
          },
          {
            "name": "P_cel_c6_l4_c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data5], 1) = 6, ",
              "    [data5] + 3, ",
              "    IF(",
              "        WEEKDAY([data5], 1) = 7, ",
              "        [data5] + 2, ",
              "        [data5] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE(SUM(carteira[CBG_PV   ]),",
              "carteira[ROTA] = \"SP2043\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "lineageTag": "c8af4e44-b78d-4340-afae-c02df31424e2"
          },
          {
            "name": "P_cel_c6_l5_c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data5], 1) = 6, ",
              "    [data5] + 3, ",
              "    IF(",
              "        WEEKDAY([data5], 1) = 7, ",
              "        [data5] + 2, ",
              "        [data5] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE(SUM(carteira[CBG_PV   ]),",
              "carteira[ROTA] = \"SP2044\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "lineageTag": "76d0bbc0-e9b3-46be-ba52-9e4d4e0702e2"
          },
          {
            "name": "p_c6_total_c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "[p_cel_c6_l1_c]+",
              "[p_cel_c6_l2_c]+",
              "[p_cel_c6_l3_c]+",
              "[p_cel_c6_l4_c]+",
              "[p_cel_c6_l5_c]+",
              "[P_cel_c6_l6_c]+",
              "[P_cel_c6_l7_c]"
            ],
            "lineageTag": "2ea049a2-5b34-4cd3-8493-0ee1164e20f4"
          },
          {
            "name": "P_cel_c7_l1_c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data6], 1) = 6, ",
              "    [data6] + 3, ",
              "    IF(",
              "        WEEKDAY([data6], 1) = 7, ",
              "        [data6] + 2, ",
              "        [data6] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE(SUM(carteira[CBG_PV   ]),",
              "carteira[ROTA] = \"SP1976\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "lineageTag": "9d424d56-cb10-402e-b1be-e74ccf8cb19d"
          },
          {
            "name": "P_cel_c7_l2_c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data6], 1) = 6, ",
              "    [data6] + 3, ",
              "    IF(",
              "        WEEKDAY([data6], 1) = 7, ",
              "        [data6] + 2, ",
              "        [data6] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE(SUM(carteira[CBG_PV   ]),",
              "carteira[ROTA] = \"SP2041\",",
              "carteira[data limite2] = data1,",
              "carteira[   TRANSPORTADOR                         .2] = \"BRASIL WEB TRANSPORTES E LOGIS\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "lineageTag": "3a480478-c8b9-47aa-87ff-0b6935c8c6fd"
          },
          {
            "name": "P_cel_c7_l3_c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data6], 1) = 6, ",
              "    [data6] + 3, ",
              "    IF(",
              "        WEEKDAY([data6], 1) = 7, ",
              "        [data6] + 2, ",
              "        [data6] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE(SUM(carteira[CBG_PV   ]),",
              "carteira[ROTA] = \"SP2042\",",
              "carteira[data limite2] = data1,",
              "carteira[   TRANSPORTADOR                         .2] = \"FAVORITA TRANSPORTES LTDA\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "lineageTag": "01acef7b-226c-4185-890c-6df1f799f7b9"
          },
          {
            "name": "P_cel_c7_l4_c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data6], 1) = 6, ",
              "    [data6] + 3, ",
              "    IF(",
              "        WEEKDAY([data6], 1) = 7, ",
              "        [data6] + 2, ",
              "        [data6] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE(SUM(carteira[CBG_PV   ]),",
              "carteira[ROTA] = \"SP2043\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "lineageTag": "53e87354-b7fc-4d47-b0d5-1274c3eaa59f"
          },
          {
            "name": "P_cel_c7_l5_c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data6], 1) = 6, ",
              "    [data6] + 3, ",
              "    IF(",
              "        WEEKDAY([data6], 1) = 7, ",
              "        [data6] + 2, ",
              "        [data6] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE(SUM(carteira[CBG_PV   ]),",
              "carteira[ROTA] = \"SP2044\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "lineageTag": "145e7971-83ae-44f4-8bd2-4f79b151f7ad"
          },
          {
            "name": "p_c7_total_c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "[p_cel_c7_l1_c]+",
              "[p_cel_c7_l2_c]+",
              "[p_cel_c7_l3_c]+",
              "[p_cel_c7_l4_c]+",
              "[p_cel_c7_l5_c]+",
              "[P_cel_c7_l6_c]+",
              "[P_cel_c7_l7_c]"
            ],
            "lineageTag": "a5c23f91-7df8-42ad-8c91-12fbf3748e45"
          },
          {
            "name": "P_cel_c8_l1_c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "    IF(",
              "        WEEKDAY([data7], 1) = 6, ",
              "        [data7] + 3, ",
              "        IF(",
              "            WEEKDAY([data7], 1) = 7, ",
              "            [data7] + 2, ",
              "            [data7] + 1",
              "        )",
              "    )",
              "VAR logica = ",
              "CALCULATE(SUM(carteira[CBG_PV   ]),",
              "carteira[ROTA] = \"SP1976\",",
              "carteira[data limite2] >= data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "lineageTag": "c1ecc2f0-d5b1-461e-a2ec-9c26c62e8d07"
          },
          {
            "name": "P_cel_c8_l2_c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "    IF(",
              "        WEEKDAY([data7], 1) = 6, ",
              "        [data7] + 3, ",
              "        IF(",
              "            WEEKDAY([data7], 1) = 7, ",
              "            [data7] + 2, ",
              "            [data7] + 1",
              "        )",
              "    )",
              "VAR logica = ",
              "CALCULATE(SUM(carteira[CBG_PV   ]),",
              "carteira[ROTA] = \"SP2041\",",
              "carteira[data limite2] >= data1,",
              "carteira[   TRANSPORTADOR                         .2] = \"BRASIL WEB TRANSPORTES E LOGIS\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "lineageTag": "42a87acb-996f-4da0-9870-d7c70ee79733"
          },
          {
            "name": "P_cel_c8_l3_c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "    IF(",
              "        WEEKDAY([data7], 1) = 6, ",
              "        [data7] + 3, ",
              "        IF(",
              "            WEEKDAY([data7], 1) = 7, ",
              "            [data7] + 2, ",
              "            [data7] + 1",
              "        )",
              "    )",
              "VAR logica = ",
              "CALCULATE(SUM(carteira[CBG_PV   ]),",
              "carteira[ROTA] = \"SP2042\",",
              "carteira[data limite2] >= data1,",
              "carteira[   TRANSPORTADOR                         .2] = \"FAVORITA TRANSPORTES LTDA\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "lineageTag": "5e5baf2e-b29b-475a-8187-eadaff9f3421"
          },
          {
            "name": "P_cel_c8_l4_c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "    IF(",
              "        WEEKDAY([data7], 1) = 6, ",
              "        [data7] + 3, ",
              "        IF(",
              "            WEEKDAY([data7], 1) = 7, ",
              "            [data7] + 2, ",
              "            [data7] + 1",
              "        )",
              "    )",
              "VAR logica = ",
              "CALCULATE(SUM(carteira[CBG_PV   ]),",
              "carteira[ROTA] = \"SP2043\",",
              "carteira[data limite2] >= data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "lineageTag": "a273dc40-27ff-4fb9-900b-30a6f0dfad78"
          },
          {
            "name": "P_cel_c8_l5_c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "    IF(",
              "        WEEKDAY([data7], 1) = 6, ",
              "        [data7] + 3, ",
              "        IF(",
              "            WEEKDAY([data7], 1) = 7, ",
              "            [data7] + 2, ",
              "            [data7] + 1",
              "        )",
              "    )",
              "VAR logica = ",
              "CALCULATE(SUM(carteira[CBG_PV   ]),",
              "carteira[ROTA] = \"SP2044\",",
              "carteira[data limite2] >= data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "lineageTag": "455ec5eb-2058-479b-a85b-330f46253ef8"
          },
          {
            "name": "p_c8_total_c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "[p_cel_c8_l1_c]+",
              "[p_cel_c8_l2_c]+",
              "[p_cel_c8_l3_c]+",
              "[p_cel_c8_l4_c]+",
              "[p_cel_c8_l5_c]+",
              "[P_cel_c8_l6_c]+",
              "[P_cel_c8_l7_c]"
            ],
            "lineageTag": "c4b0334d-d15a-4401-8638-cde9cd1842b9"
          },
          {
            "name": "p_cel_c9_l1_c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "[p_cel_c1_l1_c]+",
              "[p_cel_c2_l1_c]+",
              "[p_cel_c3_l1_c]+",
              "[p_cel_c4_l1_c]+",
              "[p_cel_c5_l1_c]+",
              "[p_cel_c6_l1_c]+",
              "[p_cel_c7_l1_c]+",
              "[p_cel_c8_l1_c]",
              "",
              ""
            ],
            "lineageTag": "73e11c33-58e3-4717-b30e-62cb83d37baf"
          },
          {
            "name": "p_cel_c9_l2_c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "[p_cel_c1_l2_c]+",
              "[p_cel_c2_l2_c]+",
              "[p_cel_c3_l2_c]+",
              "[p_cel_c4_l2_c]+",
              "[p_cel_c5_l2_c]+",
              "[p_cel_c6_l2_c]+",
              "[p_cel_c7_l2_c]+",
              "[p_cel_c8_l2_c]",
              ""
            ],
            "lineageTag": "e744e208-03f3-4e5d-8c26-c194a59ab6bf"
          },
          {
            "name": "p_cel_c9_l3_c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "[p_cel_c1_l3_c]+",
              "[p_cel_c2_l3_c]+",
              "[p_cel_c3_l3_c]+",
              "[p_cel_c4_l3_c]+",
              "[p_cel_c5_l3_c]+",
              "[p_cel_c6_l3_c]+",
              "[p_cel_c7_l3_c]+",
              "[p_cel_c8_l3_c]",
              ""
            ],
            "lineageTag": "7bb1b21f-d860-4bcb-8aad-13f4ad56e2ca"
          },
          {
            "name": "p_cel_c9_l4_c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "[p_cel_c1_l4_c]+",
              "[p_cel_c2_l4_c]+",
              "[p_cel_c3_l4_c]+",
              "[p_cel_c4_l4_c]+",
              "[p_cel_c5_l4_c]+",
              "[p_cel_c6_l4_c]+",
              "[p_cel_c7_l4_c]+",
              "[p_cel_c8_l4_c]",
              ""
            ],
            "lineageTag": "5d9d15cd-1120-4f73-a293-263882e21172"
          },
          {
            "name": "p_cel_c9_l5_c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "[p_cel_c1_l5_c]+",
              "[p_cel_c2_l5_c]+",
              "[p_cel_c3_l5_c]+",
              "[p_cel_c4_l7]+",
              "[p_cel_c5_l5_c]+",
              "[p_cel_c6_l5_c]+",
              "[p_cel_c7_l5_c]+",
              "[p_cel_c8_l5_c]",
              ""
            ],
            "lineageTag": "fac820e2-feb1-4f62-88f1-6c6d5b04e988"
          },
          {
            "name": "totalgeral_c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "[p_cel_c9_l1_c]+",
              "[p_cel_c9_l2_c]+",
              "[p_cel_c9_l3_c]+",
              "[p_cel_c9_l4_c]+",
              "[p_cel_c9_l5_c]+",
              "[p_cel_c9_l6_c]+",
              "[p_cel_c9_l7_c]"
            ],
            "lineageTag": "7c336ec2-d2fa-44a8-87ab-4ca8dba14a58"
          },
          {
            "name": "p_cel_c1_l6",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "TODAY() - 1",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2249\",",
              "carteira[status] = \"Vencidos\",",
              "carteira[   TRANSPORTADOR                         .2] = \"TRANSLAGUNA ARMAZENAGEM E TRAN\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "0",
            "lineageTag": "4a2851f6-a6a5-40ae-9f58-1f121bd0d073"
          },
          {
            "name": "p_cel_c2_l6",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "TODAY()",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2249\",",
              "carteira[data limite2] = data1,",
              "carteira[   TRANSPORTADOR                         .2] = \"TRANSLAGUNA ARMAZENAGEM E TRAN\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "0",
            "lineageTag": "7804fcb7-48bb-4b72-ad0d-d8708601c59e"
          },
          {
            "name": "P_cel_c3_l6",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY(TODAY(), 1) = 6, ",
              "    TODAY() + 3, ",
              "    IF(",
              "        WEEKDAY(TODAY(), 1) = 7, ",
              "        TODAY() + 2, ",
              "        TODAY() + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2249\",",
              "carteira[   TRANSPORTADOR                         .2] = \"TRANSLAGUNA ARMAZENAGEM E TRAN\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "0",
            "lineageTag": "87761f49-63b9-4e79-a495-391a0c5f174d"
          },
          {
            "name": "p_cel_c4_l6",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data3], 1) = 6, ",
              "    [data3] + 3, ",
              "    IF(",
              "        WEEKDAY([data3], 1) = 7, ",
              "        [data3] + 2, ",
              "        [data3] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2249\",",
              "carteira[data limite2] = data1,",
              "carteira[   TRANSPORTADOR                         .2] = \"LAGUNA - FRACIONADO PESADO\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "lineageTag": "1aa7c184-5864-4242-8832-8ecb0f22ec88"
          },
          {
            "name": "P_cel_c5_l6",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data4], 1) = 6, ",
              "    [data4] + 3, ",
              "    IF(",
              "        WEEKDAY([data4], 1) = 7, ",
              "        [data4] + 2, ",
              "        [data4] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2249\",",
              "carteira[data limite2] = data1,",
              "carteira[   TRANSPORTADOR                         .2] = \"TRANSLAGUNA ARMAZENAGEM E TRAN\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "lineageTag": "5e22509a-d8b3-4d08-9c45-5f1d231b44a6"
          },
          {
            "name": "P_cel_c6_l6",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data5], 1) = 6, ",
              "    [data5] + 3, ",
              "    IF(",
              "        WEEKDAY([data5], 1) = 7, ",
              "        [data5] + 2, ",
              "        [data5] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2249\",",
              "carteira[data limite2] = data1,",
              "carteira[   TRANSPORTADOR                         .2] = \"TRANSLAGUNA ARMAZENAGEM TRAN\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "lineageTag": "60bbad27-2535-47f5-b148-60ec30bb9282"
          },
          {
            "name": "P_cel_c7_l6",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data6], 1) = 6, ",
              "    [data6] + 3, ",
              "    IF(",
              "        WEEKDAY([data6], 1) = 7, ",
              "        [data6] + 2, ",
              "        [data6] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2249\",",
              "carteira[data limite2] = data1,",
              "carteira[   TRANSPORTADOR                         .2] = \"TRANSLAGUNA ARMAZENAGEM E TRAN\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "lineageTag": "26f56a9e-69fe-429b-a5a1-761ebc08d6d2"
          },
          {
            "name": "P_cel_c8_l6",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "    IF(",
              "        WEEKDAY([data7], 1) = 6, ",
              "        [data7] + 3, ",
              "        IF(",
              "            WEEKDAY([data7], 1) = 7, ",
              "            [data7] + 2, ",
              "            [data7] + 1",
              "        )",
              "    )",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2249\",",
              "carteira[data limite2] >= data1,",
              "carteira[   TRANSPORTADOR                         .2] = \"TRANSLAGUNA ARMAZENAGEM E TRAN\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "lineageTag": "cd414c90-61f6-41d6-b3f5-11558f886f78"
          },
          {
            "name": "p_cel_c9_l6",
            "expression": [
              "",
              "[p_cel_c1_l6]+",
              "[p_cel_c2_l6]+",
              "[p_cel_c3_l6]+",
              "[p_cel_c4_l6]+",
              "[p_cel_c5_l6]+",
              "[p_cel_c6_l6]+",
              "[p_cel_c7_l6]+",
              "[p_cel_c8_l6]"
            ],
            "formatString": "0",
            "lineageTag": "c5ceba16-39fa-43d3-89a0-0a3425416973"
          },
          {
            "name": "p_cel_c1_l7",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "TODAY() - 1",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2311\",",
              "carteira[status] = \"Vencidos\",",
              "carteira[   TRANSPORTADOR                         .2] = \"VENKON EXPRESS TRANSPORTES\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "0",
            "lineageTag": "27215b87-dc95-45d2-b90a-87b8a302f7eb"
          },
          {
            "name": "p_cel_c2_l7",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "TODAY()",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2311\",",
              "carteira[data limite2] = data1,",
              "carteira[   TRANSPORTADOR                         .2] = \"VENKON EXPRESS TRANSPORTES\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "0",
            "lineageTag": "ae010ddd-037d-435a-8296-f9dcfc9363d0"
          },
          {
            "name": "P_cel_c3_l7",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY(TODAY(), 1) = 6, ",
              "    TODAY() + 3, ",
              "    IF(",
              "        WEEKDAY(TODAY(), 1) = 7, ",
              "        TODAY() + 2, ",
              "        TODAY() + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2311\",",
              "carteira[   TRANSPORTADOR                         .2] = \"VENKON EXPRESS TRANSPORTES\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "0",
            "lineageTag": "1415f7d6-49d1-46db-b14e-140105682591"
          },
          {
            "name": "p_cel_c4_l7_c",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data3], 1) = 6, ",
              "    [data3] + 3, ",
              "    IF(",
              "        WEEKDAY([data3], 1) = 7, ",
              "        [data3] + 2, ",
              "        [data3] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2311\",",
              "carteira[   TRANSPORTADOR                         .2] = \"VENKON EXPRESS TRANSPORTES\",",
              "carteira[data limite2] = data1",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "0",
            "lineageTag": "abf7cc30-c6d9-44e4-9289-2afd4fd5d03b"
          },
          {
            "name": "P_cel_c5_l7",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data4], 1) = 6, ",
              "    [data4] + 3, ",
              "    IF(",
              "        WEEKDAY([data4], 1) = 7, ",
              "        [data4] + 2, ",
              "        [data4] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2311\",",
              "carteira[data limite2] = data1,",
              "carteira[   TRANSPORTADOR                         .2] = \"VENKON - FRACIONADO PESADO\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "lineageTag": "626b96df-e95f-442d-b744-f3bb73889887"
          },
          {
            "name": "P_cel_c6_l7",
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data5], 1) = 6, ",
              "    [data5] + 3, ",
              "    IF(",
              "        WEEKDAY([data5], 1) = 7, ",
              "        [data5] + 2, ",
              "        [data5] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2311\",",
              "carteira[data limite2] = data1,",
              "carteira[   TRANSPORTADOR                         .2] = \"VENKON EXPRESS TRANSPORTES\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "formatString": "0",
            "lineageTag": "909e5457-6dcc-4ac6-af48-07f96c1f6133"
          },
          {
            "name": "P_cel_c7_l7",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data6], 1) = 6, ",
              "    [data6] + 3, ",
              "    IF(",
              "        WEEKDAY([data6], 1) = 7, ",
              "        [data6] + 2, ",
              "        [data6] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2311\",",
              "carteira[data limite2] = data1,",
              "carteira[   TRANSPORTADOR                         .2] = \"VENKON EXPRESS TRANSPORTES\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "lineageTag": "df88867d-7ef2-4360-ac64-e35d29dc2b52"
          },
          {
            "name": "P_cel_c8_l7",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "    IF(",
              "        WEEKDAY([data7], 1) = 6, ",
              "        [data7] + 3, ",
              "        IF(",
              "            WEEKDAY([data7], 1) = 7, ",
              "            [data7] + 2, ",
              "            [data7] + 1",
              "        )",
              "    )",
              "VAR logica = ",
              "CALCULATE([qt_pedidos_carteira],",
              "carteira[ROTA] = \"SP2311\",",
              "carteira[data limite2] >= data1,",
              "carteira[   TRANSPORTADOR                         .2] = \"VENKON EXPRESS TRANSPORTES\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "lineageTag": "e159586b-36d7-47e2-ae55-a0eb7ceb4eca"
          },
          {
            "name": "p_cel_c9_l7",
            "expression": [
              "",
              "[p_cel_c1_l7]+",
              "[p_cel_c2_l7]+",
              "[p_cel_c3_l7]+",
              "[p_cel_c4_l7_c]+",
              "[p_cel_c5_l7]+",
              "[p_cel_c6_l7]+",
              "[p_cel_c7_l7]+",
              "[p_cel_c8_l7]"
            ],
            "formatString": "0",
            "lineageTag": "1fdbd867-ff22-4886-b6ea-2f4250dff43d"
          },
          {
            "name": "p_cel_c1_l6_c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "TODAY() - 1",
              "",
              "VAR logica = ",
              "CALCULATE(SUM(carteira[CBG_PV   ]),",
              "carteira[ROTA] = \"SP2249\",",
              "carteira[status] = \"Vencidos\",",
              "carteira[   TRANSPORTADOR                         .2] = \"TRANSLAGUNA ARMAZENAGEM E TRAN\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "lineageTag": "00a17ba5-a7eb-4afe-ac0d-e0cf2cf55a55"
          },
          {
            "name": "p_cel_c1_l7_c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "TODAY() - 1",
              "",
              "VAR logica = ",
              "CALCULATE(SUM(carteira[CBG_PV   ]),",
              "carteira[ROTA] = \"SP2311\",",
              "carteira[status] = \"Vencidos\",",
              "carteira[   TRANSPORTADOR                         .2] = \"VENKON EXPRESS TRANSPORTES\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "lineageTag": "d7dfed3c-4a91-45a3-8f42-55367b755088"
          },
          {
            "name": "p_cel_c2_l6_c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "TODAY()",
              "",
              "VAR logica = ",
              "CALCULATE(SUM(carteira[CBG_PV   ]),",
              "carteira[ROTA] = \"SP2249\",",
              "carteira[data limite2] = data1,",
              "carteira[   TRANSPORTADOR                         .2] = \"TRANSLAGUNA ARMAZENAGEM E TRAN\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "lineageTag": "221e2f07-1140-4004-af5e-bd6786168165"
          },
          {
            "name": "p_cel_c2_l7_c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "TODAY()",
              "",
              "VAR logica = ",
              "CALCULATE(SUM(carteira[CBG_PV   ]),",
              "carteira[ROTA] = \"SP2311\",",
              "carteira[data limite2] = data1,",
              "carteira[   TRANSPORTADOR                         .2] = \"VENKON EXPRESS TRANSPORTES\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "lineageTag": "eaf1bdc6-baa4-4925-a55c-bd4f2255bfad"
          },
          {
            "name": "P_cel_c3_l6_c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY(TODAY(), 1) = 6, ",
              "    TODAY() + 3, ",
              "    IF(",
              "        WEEKDAY(TODAY(), 1) = 7, ",
              "        TODAY() + 2, ",
              "        TODAY() + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE(SUM(carteira[CBG_PV   ]),",
              "carteira[ROTA] = \"SP2249\",",
              "carteira[data limite2] = data1,",
              "carteira[   TRANSPORTADOR                         .2] = \"TRANSLAGUNA ARMAZENAGEM E TRAN\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "lineageTag": "818fed6e-8872-4da5-a1ca-a4bf0feb4209"
          },
          {
            "name": "P_cel_c3_l7_c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY(TODAY(), 1) = 6, ",
              "    TODAY() + 3, ",
              "    IF(",
              "        WEEKDAY(TODAY(), 1) = 7, ",
              "        TODAY() + 2, ",
              "        TODAY() + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE(SUM(carteira[CBG_PV   ]),",
              "carteira[ROTA] = \"SP2311\",",
              "carteira[data limite2] = data1,",
              "carteira[   TRANSPORTADOR                         .2] = \"VENKON EXPRESS TRANSPORTES\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "lineageTag": "124a5cdc-89f0-4822-bf2b-18c64bc588af"
          },
          {
            "name": "p_cel_c4_l8",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data3], 1) = 6, ",
              "    [data3] + 3, ",
              "    IF(",
              "        WEEKDAY([data3], 1) = 7, ",
              "        [data3] + 2, ",
              "        [data3] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE(SUM(carteira[CBG_PV   ]),",
              "carteira[ROTA] = \"SP2249\",",
              "carteira[data limite2] = data1,",
              "carteira[   TRANSPORTADOR                         .2] = \"TRANSLAGUNA ARMAZENAGEM E TRAN\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "lineageTag": "e073a262-d585-4984-b0a2-add7f060e17c"
          },
          {
            "name": "p_cel_c4_l9",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data3], 1) = 6, ",
              "    [data3] + 3, ",
              "    IF(",
              "        WEEKDAY([data3], 1) = 7, ",
              "        [data3] + 2, ",
              "        [data3] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE(SUM(carteira[CBG_PV   ]),",
              "carteira[ROTA] = \"SP2311\",",
              "carteira[data limite2] = data1,",
              "carteira[   TRANSPORTADOR                         .2] = \"VENKON EXPRESS TRANSPORTES\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "lineageTag": "1c0df5d6-fb4d-432b-97d8-cea0891de2a9"
          },
          {
            "name": "P_cel_c5_l6_c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data4], 1) = 6, ",
              "    [data4] + 3, ",
              "    IF(",
              "        WEEKDAY([data4], 1) = 7, ",
              "        [data4] + 2, ",
              "        [data4] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE(SUM(carteira[CBG_PV   ]),",
              "carteira[ROTA] = \"SP2249\",",
              "carteira[data limite2] = data1,",
              "carteira[   TRANSPORTADOR                         .2] = \"TRANSLAGUNA ARMAZENAGEM E TRAN\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "lineageTag": "20d55ec2-e15f-44c7-bc29-2fd92712af20"
          },
          {
            "name": "P_cel_c5_l7_c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data4], 1) = 6, ",
              "    [data4] + 3, ",
              "    IF(",
              "        WEEKDAY([data4], 1) = 7, ",
              "        [data4] + 2, ",
              "        [data4] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE(SUM(carteira[CBG_PV   ]),",
              "carteira[ROTA] = \"SP2311\",",
              "carteira[data limite2] = data1,",
              "carteira[   TRANSPORTADOR                         .2] = \"VENKON EXPRESS TRANSPORTES\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "lineageTag": "4aa03a30-60a1-46d5-a57c-ba78937310b0"
          },
          {
            "name": "P_cel_c7_l7_c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data6], 1) = 6, ",
              "    [data6] + 3, ",
              "    IF(",
              "        WEEKDAY([data6], 1) = 7, ",
              "        [data6] + 2, ",
              "        [data6] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE(SUM(carteira[CBG_PV   ]),",
              "carteira[ROTA] = \"SP2311\",",
              "carteira[data limite2] = data1,",
              "carteira[   TRANSPORTADOR                         .2] = \"VENKON EXPRESS TRANSPORTES\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "lineageTag": "2117ebe3-2c92-4338-8283-a52532c8e269"
          },
          {
            "name": "P_cel_c6_l6_c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data5], 1) = 6, ",
              "    [data5] + 3, ",
              "    IF(",
              "        WEEKDAY([data5], 1) = 7, ",
              "        [data5] + 2, ",
              "        [data5] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE(SUM(carteira[CBG_PV   ]),",
              "carteira[ROTA] = \"SP2249\",",
              "carteira[data limite2] = data1,",
              "carteira[   TRANSPORTADOR                         .2] = \"TRANSLAGUNA ARMAZENAGEM E TRAN\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "lineageTag": "26854303-4630-463e-b712-b952b0c19ebc"
          },
          {
            "name": "P_cel_c6_l7_c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data5], 1) = 6, ",
              "    [data5] + 3, ",
              "    IF(",
              "        WEEKDAY([data5], 1) = 7, ",
              "        [data5] + 2, ",
              "        [data5] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE(SUM(carteira[CBG_PV   ]),",
              "carteira[ROTA] = \"SP2311\",",
              "carteira[data limite2] = data1,",
              "carteira[   TRANSPORTADOR                         .2] = \"VENKON EXPRESS TRANSPORTES\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "lineageTag": "a2f74497-2a57-47be-8ade-66ac15def66f"
          },
          {
            "name": "P_cel_c7_l6_c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "IF(",
              "    WEEKDAY([data6], 1) = 6, ",
              "    [data6] + 3, ",
              "    IF(",
              "        WEEKDAY([data6], 1) = 7, ",
              "        [data6] + 2, ",
              "        [data6] + 1",
              "    ))",
              "",
              "VAR logica = ",
              "CALCULATE(SUM(carteira[CBG_PV   ]),",
              "carteira[ROTA] = \"SP2249\",",
              "carteira[data limite2] = data1,",
              "carteira[   TRANSPORTADOR                         .2] = \"TRANSLAGUNA ARMAZENAGEM E TRAN\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "lineageTag": "bec49731-7d2a-4150-befa-2da76bbcd9de"
          },
          {
            "name": "P_cel_c8_l6_c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "    IF(",
              "        WEEKDAY([data7], 1) = 6, ",
              "        [data7] + 3, ",
              "        IF(",
              "            WEEKDAY([data7], 1) = 7, ",
              "            [data7] + 2, ",
              "            [data7] + 1",
              "        )",
              "    )",
              "VAR logica = ",
              "CALCULATE(SUM(carteira[CBG_PV   ]),",
              "carteira[ROTA] = \"SP2249\",",
              "carteira[data limite2] >= data1,",
              "carteira[   TRANSPORTADOR                         .2] = \"TRANSLAGUNA ARMAZENAGEM E TRAN\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "lineageTag": "f8266833-3fb2-45ca-8805-ad822bd0b55c"
          },
          {
            "name": "P_cel_c8_l7_c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR data1 = ",
              "    IF(",
              "        WEEKDAY([data7], 1) = 6, ",
              "        [data7] + 3, ",
              "        IF(",
              "            WEEKDAY([data7], 1) = 7, ",
              "            [data7] + 2, ",
              "            [data7] + 1",
              "        )",
              "    )",
              "VAR logica = ",
              "CALCULATE(SUM(carteira[CBG_PV   ]),",
              "carteira[ROTA] = \"SP2311\",",
              "carteira[data limite2] >= data1,",
              "carteira[   TRANSPORTADOR                         .2] = \"VENKON EXPRESS TRANSPORTES\"",
              ")",
              "",
              "RETURN ",
              "IF(ISBLANK(",
              "logica),\"0\",logica)"
            ],
            "lineageTag": "c45ff7ae-d6bc-4c19-9934-43086729cdb0"
          },
          {
            "name": "p_cel_c9_l6_c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "[p_cel_c1_l6_c]+",
              "[p_cel_c2_l6_c]+",
              "[P_cel_c3_l6_c]+",
              "[p_cel_c4_l8]+",
              "[P_cel_c5_l6_c]+",
              "[P_cel_c6_l6_c]+",
              "[P_cel_c7_l6_c]+",
              "[P_cel_c8_l6_c]"
            ],
            "lineageTag": "61ff5138-75f3-46d3-ba9c-6074760f82c8"
          },
          {
            "name": "p_cel_c9_l7_c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "[p_cel_c1_l7_c]+",
              "[p_cel_c2_l7_c]+",
              "[P_cel_c3_l7_c]+",
              "[p_cel_c4_l9]+",
              "[P_cel_c5_l7_c]+",
              "[P_cel_c6_l7_c]+",
              "[P_cel_c7_l7_c]+",
              "[P_cel_c8_l7_c]",
              ""
            ],
            "lineageTag": "f057e43b-7833-465e-bb0b-e9f76a94dcd8"
          }
        ],
        "partitions": [
          {
            "name": "Medidas",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Coluna 1\" = _t]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(Fonte,{{\"Coluna 1\", type text}})",
                "in",
                "    #\"Tipo Alterado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "entrada",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "columns": [
          {
            "name": "CODIGO DA EMPRESA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b28e5648-cdec-4cd5-9168-bb08bb7ba9af",
            "sourceColumn": "CODIGO DA EMPRESA",
            "summarizeBy": "sum"
          },
          {
            "name": "CODIGO DA FILIAL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "dc9d0c69-f2b0-438c-9f73-4012fd8ee370",
            "sourceColumn": "CODIGO DA FILIAL",
            "summarizeBy": "sum"
          },
          {
            "name": "DATA DE LIMITE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "83d5e5a6-d71d-4d6f-9568-1a97c21c85d2",
            "sourceColumn": "DATA DE LIMITE",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_dd0d8641-6c07-4ce1-a5cc-5c9d44d4aa0d"
                },
                "isDefault": true,
                "relationship": "97d3f873-4915-48ec-bb70-412e8fe10bb9"
              }
            ]
          },
          {
            "name": "DATA DA INTEGRACAO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "00f3634a-50a6-495f-9076-fc34aaf5fc66",
            "sourceColumn": "DATA DA INTEGRACAO",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_222bf26e-cc17-4215-bf94-0aa98a5433de"
                },
                "isDefault": true,
                "relationship": "64212890-231e-4166-a857-aa7872a394e9"
              }
            ]
          },
          {
            "name": "hora_da_integração",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "83832f53-db2c-4dd3-9083-e0a2e529fbc0",
            "sourceColumn": "hora_da_integração",
            "summarizeBy": "none"
          },
          {
            "name": "NUMERO DO PEDIDO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c7ab4567-8312-4ba7-85be-ec5cbad65109",
            "sourceColumn": "NUMERO DO PEDIDO",
            "summarizeBy": "sum"
          },
          {
            "name": "CODIGO DA MERCADORIA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2f8d309b-839c-471e-80d3-3201eb23bf72",
            "sourceColumn": "CODIGO DA MERCADORIA",
            "summarizeBy": "sum"
          },
          {
            "name": "DESCRICAO DA MERCADORIA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b5c0e6f2-52bb-4a1c-86f4-dee5e9b69347",
            "sourceColumn": "DESCRICAO DA MERCADORIA",
            "summarizeBy": "none"
          },
          {
            "name": "QUANTIDADE DA MERCADORIA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0c7edd55-c808-4930-9a45-b86dd525c1b3",
            "sourceColumn": "QUANTIDADE DA MERCADORIA",
            "summarizeBy": "sum"
          },
          {
            "name": "TIPO DE ENTREGA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "10569e64-4eb2-479f-b0ed-c37c1ace4587",
            "sourceColumn": "TIPO DE ENTREGA",
            "summarizeBy": "none"
          },
          {
            "name": "CODIGO DO SETOR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "59e17269-29a5-425f-b5bb-ff44b3e2465c",
            "sourceColumn": "CODIGO DO SETOR",
            "summarizeBy": "sum"
          },
          {
            "name": "DESCRICAO DO SETOR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "11804145-3944-45e7-a293-d2cbf3359b6e",
            "sourceColumn": "DESCRICAO DO SETOR",
            "summarizeBy": "none"
          },
          {
            "name": "CODIGO EXPEDICAO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c2a705dc-ca89-4e8e-a5ed-4558416a5980",
            "sourceColumn": "CODIGO EXPEDICAO",
            "summarizeBy": "none"
          },
          {
            "name": "TIPO DE EXPEDICAO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3ff90a45-740c-49b2-a7fa-a16ed5529150",
            "sourceColumn": "TIPO DE EXPEDICAO",
            "summarizeBy": "none"
          },
          {
            "name": "DATA DE ENTRADA CAIXA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ad46faa4-3f2c-4200-95f5-76b7b35a0257",
            "sourceColumn": "DATA DE ENTRADA CAIXA",
            "summarizeBy": "sum"
          },
          {
            "name": "ROTA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5aa818ae-2153-47fe-bd75-0bec381cfca5",
            "sourceColumn": "ROTA",
            "summarizeBy": "none"
          },
          {
            "name": "STATUS PEDIDO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4d82bd2e-d505-433f-b470-135c898f78ca",
            "sourceColumn": "STATUS PEDIDO",
            "summarizeBy": "none"
          },
          {
            "name": "TIPO PEDIDO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6b715c8b-a38e-46a0-a23b-2121f6625f85",
            "sourceColumn": "TIPO PEDIDO",
            "summarizeBy": "none"
          },
          {
            "name": "CARGA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "27b2312d-55d7-403d-9900-994aa030e196",
            "sourceColumn": "CARGA",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "142e175f-587a-4fbb-a5cd-6acb29705882",
        "partitions": [
          {
            "name": "entrada",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = SharePoint.Contents(\"https://viavarejo.sharepoint.com/sites/grupo_de_dados_wave\", [ApiVersion = 15]),",
                "    #\"Atualizaes de Relatrios Gerais\" = Fonte{[Name=\"Atualizaes de Relatrios Gerais\"]}[Content],",
                "    #\"Relatórios dinâmicos - ADMs - Vinicius & Almeida\" = #\"Atualizaes de Relatrios Gerais\"{[Name=\"Relatórios dinâmicos - ADMs - Vinicius & Almeida\"]}[Content],",
                "    #\"Relatórios rotativos\" = #\"Relatórios dinâmicos - ADMs - Vinicius & Almeida\"{[Name=\"Relatórios rotativos\"]}[Content],",
                "    #\"Painel Online - ADMs - Vinicius & Almeida\" = #\"Relatórios rotativos\"{[Name=\"Painel Online - ADMs - Vinicius & Almeida\"]}[Content],",
                "    #\"Entrada - ADMs - Vinicius & Almeida\" = #\"Painel Online - ADMs - Vinicius & Almeida\"{[Name=\"Entrada - ADMs - Vinicius & Almeida\"]}[Content],",
                "    #\"Arquivos Ocultos Filtrados1\" = Table.SelectRows(#\"Entrada - ADMs - Vinicius & Almeida\", each [Attributes]?[Hidden]? <> true),",
                "    #\"Invocar Função Personalizada1\" = Table.AddColumn(#\"Arquivos Ocultos Filtrados1\", \"Transformar Arquivo (3)\", each #\"Transformar Arquivo (3)\"([Content])),",
                "    #\"Colunas Renomeadas1\" = Table.RenameColumns(#\"Invocar Função Personalizada1\", {\"Name\", \"Nome da Origem\"}),",
                "    #\"Outras Colunas Removidas1\" = Table.SelectColumns(#\"Colunas Renomeadas1\", {\"Nome da Origem\", \"Transformar Arquivo (3)\"}),",
                "    #\"Coluna de Tabela Expandida1\" = Table.ExpandTableColumn(#\"Outras Colunas Removidas1\", \"Transformar Arquivo (3)\", Table.ColumnNames(#\"Transformar Arquivo (3)\"(#\"Arquivo de Amostra (3)\"))),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Coluna de Tabela Expandida1\",{{\"Nome da Origem\", type text}, {\"CODIGO DA EMPRESA\", Int64.Type}, {\"CODIGO DA FILIAL\", Int64.Type}, {\"HORA DA INTEGRACAO\", type time}, {\"NUMERO DO PEDIDO\", Int64.Type}, {\"CODIGO DA MERCADORIA\", Int64.Type}, {\"DESCRICAO DA MERCADORIA\", type text}, {\"QUANTIDADE DA MERCADORIA\", Int64.Type}, {\"TIPO DE ENTREGA\", type text}, {\"CODIGO DO SETOR\", Int64.Type}, {\"DESCRICAO DO SETOR\", type text}, {\"CODIGO EXPEDICAO\", type text}, {\"TIPO DE EXPEDICAO\", type text}, {\"DATA DE ENTRADA CAIXA\", Int64.Type}, {\"ROTA\", type text}, {\"STATUS PEDIDO\", type text}, {\"TIPO PEDIDO\", type text}, {\"CARGA\", Int64.Type}, {\"                                                                                                                                                                                    \", type any}}),",
                "    #\"Valor Substituído1\" = Table.ReplaceValue(#\"Tipo Alterado\",\".\",\"/\",Replacer.ReplaceText,{\"DATA DE LIMITE\", \"DATA DA INTEGRACAO\"}),",
                "    #\"Tipo Alterado1\" = Table.TransformColumnTypes(#\"Valor Substituído1\",{{\"DATA DE LIMITE\", type date}, {\"DATA DA INTEGRACAO\", type date}}),",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(#\"Tipo Alterado1\",{\"Nome da Origem\", \"                                                                                                                                                                                    \"}),",
                "    #\"Valor Substituído\" = Table.ReplaceValue(#\"Colunas Removidas\",\" \",\"\",Replacer.ReplaceText,{\"ROTA\"}),",
                "    #\"Linhas Filtradas\" = Table.SelectRows(#\"Valor Substituído\", each ([ROTA] = \"SP1989\" or [ROTA] = \"SP2023\"or [ROTA] = \"SP2027\" or [ROTA] = \"SP2856\" or [ROTA] = \"SP2869\" or [ROTA] = \"SP2870\" or [ROTA] = \"SP2871\" or [ROTA] = \"SP2872\" or [ROTA] = \"SP2873\" or [ROTA] = \"SP2874\" or [ROTA] = \"SP2875\" or [ROTA] = \"SP2894\" or [ROTA] = \"SP2895\" or [ROTA] = \"SP2896\" or [ROTA] = \"SP2911\" or [ROTA] = \"SP2937\" or [ROTA] = \"SP2914\" or [ROTA] = \"SP2938\" or [ROTA] = \"SP2916\" or [ROTA] = \"SP2921\" or [ROTA] = \"SP2922\" or [ROTA] = \"SP2923\" or [ROTA] = \"SP2924\")),",
                "    #\"Duplicatas Removidas\" = Table.Distinct(#\"Linhas Filtradas\"),",
                "    #\"Início da Hora Calculado\" = Table.TransformColumns(#\"Duplicatas Removidas\",{{\"HORA DA INTEGRACAO\", Time.StartOfHour, type time}}),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Início da Hora Calculado\",{{\"HORA DA INTEGRACAO\", \"hora_da_integração\"}}),",
                "    #\"Colunas Reordenadas\" = Table.ReorderColumns(#\"Colunas Renomeadas\",{\"CODIGO DA EMPRESA\", \"CODIGO DA FILIAL\", \"DATA DE LIMITE\", \"DATA DA INTEGRACAO\", \"NUMERO DO PEDIDO\", \"CODIGO DA MERCADORIA\", \"DESCRICAO DA MERCADORIA\", \"QUANTIDADE DA MERCADORIA\", \"TIPO DE ENTREGA\", \"CODIGO DO SETOR\", \"DESCRICAO DO SETOR\", \"CODIGO EXPEDICAO\", \"TIPO DE EXPEDICAO\", \"DATA DE ENTRADA CAIXA\", \"ROTA\", \"STATUS PEDIDO\", \"TIPO PEDIDO\", \"CARGA\", \"hora_da_integração\"})",
                "in",
                "    #\"Colunas Reordenadas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "carteira",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": " TIPO ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "67069efa-63be-4fb5-95d3-d641033e7479",
            "sourceColumn": " TIPO ",
            "summarizeBy": "none"
          },
          {
            "name": "  PEDIDOS   ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "aebf2d72-f7c3-487a-ab87-472abd62f41d",
            "sourceColumn": "  PEDIDOS   ",
            "summarizeBy": "sum"
          },
          {
            "name": " DESMEMB  ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "88b507ed-de53-4839-a448-fe94260c47f3",
            "sourceColumn": " DESMEMB  ",
            "summarizeBy": "sum"
          },
          {
            "name": " ORDEM_VENDA     ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "07d30e94-2a60-4be2-bdc5-b3c9afc8360a",
            "sourceColumn": " ORDEM_VENDA     ",
            "summarizeBy": "none"
          },
          {
            "name": " STATUS_PEDIDO       ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "61d2fc49-6d98-46cb-bce6-0472efca0f0e",
            "sourceColumn": " STATUS_PEDIDO       ",
            "summarizeBy": "none"
          },
          {
            "name": " QT_SKU ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2593adec-eaa8-4f6a-93fa-10494edbd6ab",
            "sourceColumn": " QT_SKU ",
            "summarizeBy": "sum"
          },
          {
            "name": " CD_SKU      ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4a1a9fc7-3756-4ace-a7b2-b44b31b1a4a1",
            "sourceColumn": " CD_SKU      ",
            "summarizeBy": "sum"
          },
          {
            "name": " DS_SKU                                           ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e2a86ac8-a5bb-4029-aa94-5bb02db3a84e",
            "sourceColumn": " DS_SKU                                           ",
            "summarizeBy": "none"
          },
          {
            "name": " DIRETORIA                      ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bbba8396-c46e-4d3c-8aef-58ffce29097f",
            "sourceColumn": " DIRETORIA                      ",
            "summarizeBy": "none"
          },
          {
            "name": " DT_EMI_CARGA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "dcb7df52-a0eb-437e-bae2-5814c7fefb1d",
            "sourceColumn": " DT_EMI_CARGA",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_c4d33cb2-a1aa-4080-9242-482afcb197a5"
                },
                "isDefault": true,
                "relationship": "de13782f-1128-47db-b698-cd1344f1c715"
              }
            ]
          },
          {
            "name": "DEST ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "fb3c6151-76fd-4b09-941c-40ee1cbe8363",
            "sourceColumn": "DEST ",
            "summarizeBy": "sum"
          },
          {
            "name": " FIL_DST",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0e0711cf-d5c9-4d19-95e2-8571cb5732d7",
            "sourceColumn": " FIL_DST",
            "summarizeBy": "sum"
          },
          {
            "name": "TAF",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7f19386e-abe5-45ae-916b-058e2860854c",
            "sourceColumn": "TAF",
            "summarizeBy": "none"
          },
          {
            "name": " RSR  ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3c05a19f-0ae4-448c-b241-71b7f3eb37a6",
            "sourceColumn": " RSR  ",
            "summarizeBy": "sum"
          },
          {
            "name": "FIL_RESER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c6f34171-d721-4696-b4b0-03834234e8f3",
            "sourceColumn": "FIL_RESER",
            "summarizeBy": "sum"
          },
          {
            "name": "TAF_1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2706c715-8e45-4bc0-a71c-543ae1f46880",
            "sourceColumn": "TAF_1",
            "summarizeBy": "none"
          },
          {
            "name": "   TRANSPORTADOR                         .1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "95dbbba0-f448-4fcc-807f-507824036455",
            "sourceColumn": "   TRANSPORTADOR                         .1",
            "summarizeBy": "sum"
          },
          {
            "name": "   TRANSPORTADOR                         .2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cab44444-6a66-46f6-86a9-297174448275",
            "sourceColumn": "   TRANSPORTADOR                         .2",
            "summarizeBy": "none"
          },
          {
            "name": " UF_DES  ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3f6c0560-3064-4476-90c2-306f23a534e3",
            "sourceColumn": " UF_DES  ",
            "summarizeBy": "none"
          },
          {
            "name": "DT_PREV_CARGA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "3a205978-0cb1-4265-ad5e-5e21df21ef03",
            "sourceColumn": "DT_PREV_CARGA",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_7d8dcf04-db06-423d-bd1c-964028d29b65"
                },
                "isDefault": true,
                "relationship": "ab608b55-4c93-47e8-bb38-042dbe21d708"
              }
            ]
          },
          {
            "name": "   CARGA   ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "645fff05-a85c-4f78-b043-8adde972bac0",
            "sourceColumn": "   CARGA   ",
            "summarizeBy": "sum"
          },
          {
            "name": "ST",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f0cb93e5-22e1-43a9-93e6-89c71bac2fa1",
            "sourceColumn": "ST",
            "summarizeBy": "none"
          },
          {
            "name": "MIC ZON ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cc51f8e5-5911-4ec1-853c-4475ff3c1410",
            "sourceColumn": "MIC ZON ",
            "summarizeBy": "none"
          },
          {
            "name": "RT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d40522ef-55e4-4e75-a018-c779f161601a",
            "sourceColumn": "RT",
            "summarizeBy": "none"
          },
          {
            "name": "CBG_PV   ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "07984700-192e-4c2e-a36f-06e2df3f24ba",
            "sourceColumn": "CBG_PV   ",
            "summarizeBy": "sum"
          },
          {
            "name": "DT_LIMITE  ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "86143bad-754e-42fb-8f28-0cc640c4b7f0",
            "sourceColumn": "DT_LIMITE  ",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_651663f4-1ba0-4bf3-af74-833f6eb94270"
                },
                "isDefault": true,
                "relationship": "9995fbdf-a891-46ac-91e7-69f7a9e6b26e"
              }
            ]
          },
          {
            "name": " VALOR_DO_ITEM    ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "fd6710bc-f001-4636-8890-ee30c2b5718e",
            "sourceColumn": " VALOR_DO_ITEM    ",
            "summarizeBy": "sum"
          },
          {
            "name": "TIPOETG",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0c8e1f33-abfb-4b93-906a-e234162c00f5",
            "sourceColumn": "TIPOETG",
            "summarizeBy": "none"
          },
          {
            "name": "DATA PVE/MIG ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "3dd16412-130c-43ed-ab45-4c48844cf440",
            "sourceColumn": "DATA PVE/MIG ",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_ed27a44c-4c3c-4b63-94ef-30d85b1de634"
                },
                "isDefault": true,
                "relationship": "018d1f04-ee4d-46ee-a38d-82184818cff9"
              }
            ]
          },
          {
            "name": " DATA_PROMETIDA ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "5124bb45-ce01-4d7d-b83f-35dbca539347",
            "sourceColumn": " DATA_PROMETIDA ",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_5d585d2d-fdca-4b22-ab1b-b15d208473a7"
                },
                "isDefault": true,
                "relationship": "ebdb5d42-94c2-443d-bf47-2f4cd8b9c0d9"
              }
            ]
          },
          {
            "name": "ROTA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d6995c35-a792-4ce4-9e85-a0df36ec157e",
            "sourceColumn": "ROTA",
            "summarizeBy": "none"
          },
          {
            "name": "DIAS_ROTA ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "992e31e6-d405-4273-8cf2-3eb6bc7119cd",
            "sourceColumn": "DIAS_ROTA ",
            "summarizeBy": "sum"
          },
          {
            "name": "REGIAO ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "4bfa3f39-734e-48aa-ab71-2a7f41e9811a",
            "sourceColumn": "REGIAO ",
            "summarizeBy": "sum"
          },
          {
            "name": " VENDA  ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c695affa-59b2-4539-84b5-7ae9ff8c9140",
            "sourceColumn": " VENDA  ",
            "summarizeBy": "none"
          },
          {
            "name": " TIPO_SKU",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d3b89493-a8c5-4064-af64-3f20add1409b",
            "sourceColumn": " TIPO_SKU",
            "summarizeBy": "none"
          },
          {
            "name": " HORA_VENDA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "07ad2852-92c6-4980-b45f-35a262c8b3f6",
            "sourceColumn": " HORA_VENDA",
            "summarizeBy": "none"
          },
          {
            "name": "SKU_PENDENTE ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6ffb37b3-32b5-4622-baec-073354cb3aab",
            "sourceColumn": "SKU_PENDENTE ",
            "summarizeBy": "none"
          },
          {
            "name": "PERIODO ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5c52f699-3fc2-488e-974f-8719477c7238",
            "sourceColumn": "PERIODO ",
            "summarizeBy": "none"
          },
          {
            "name": "DATA_MARCADA ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "81a242ae-c409-4817-8ba7-e4128e639118",
            "sourceColumn": "DATA_MARCADA ",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_a1e482f1-8307-44d3-9932-440eaad15ef6"
                },
                "isDefault": true,
                "relationship": "e6a7c465-86c8-4510-ad37-5e72bcd171c5"
              }
            ]
          },
          {
            "name": " CATEGORIA  ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "490360d3-97cf-4050-8383-231e711a6cbe",
            "sourceColumn": " CATEGORIA  ",
            "summarizeBy": "none"
          },
          {
            "name": " COD.MUNICIPIO ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2f7aeadd-c44c-4b30-8451-84f63621c8e4",
            "sourceColumn": " COD.MUNICIPIO ",
            "summarizeBy": "sum"
          },
          {
            "name": " DESC. MUNICIPIO ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b451f3b6-ec42-4203-8fa5-4ac2ddbaac21",
            "sourceColumn": " DESC. MUNICIPIO ",
            "summarizeBy": "none"
          },
          {
            "name": " LOGRADOURO                     ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cf075d81-8af6-406c-9161-e1100ff6653b",
            "sourceColumn": " LOGRADOURO                     ",
            "summarizeBy": "none"
          },
          {
            "name": " NUMERO     ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "67931485-9d86-4d17-82e7-e5674266d880",
            "sourceColumn": " NUMERO     ",
            "summarizeBy": "sum"
          },
          {
            "name": " BAIRRO          ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "db5d3b43-7025-4618-8879-aa36e8cd6e19",
            "sourceColumn": " BAIRRO          ",
            "summarizeBy": "none"
          },
          {
            "name": " CEP        ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1977665d-e650-407f-bd8b-6012d591b273",
            "sourceColumn": " CEP        ",
            "summarizeBy": "sum"
          },
          {
            "name": " FREQUENCIA DA MICROZONA        ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dcb3ae2a-84b8-4f66-96c6-c362a5f6cb88",
            "sourceColumn": " FREQUENCIA DA MICROZONA        ",
            "summarizeBy": "none"
          },
          {
            "name": " PEDIDO CRITICO(S/N) ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c7e4754d-cfe4-4321-9890-31bf531cef3b",
            "sourceColumn": " PEDIDO CRITICO(S/N) ",
            "summarizeBy": "none"
          },
          {
            "name": " CROSS DOCKING (S/N) ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9a29b3ef-0ca4-4fc5-894f-242189f3150b",
            "sourceColumn": " CROSS DOCKING (S/N) ",
            "summarizeBy": "none"
          },
          {
            "name": " UNIDADE DE NEGOCIO ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e4f815dc-d71c-4f49-9668-795095e10fe8",
            "sourceColumn": " UNIDADE DE NEGOCIO ",
            "summarizeBy": "none"
          },
          {
            "name": "ID - MEGA ROTA ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "68ed9a71-c829-4108-bc60-6689f4036881",
            "sourceColumn": "ID - MEGA ROTA ",
            "summarizeBy": "sum"
          },
          {
            "name": " DESCRICAO MEGA ROTA ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ecba60ec-91da-4e50-9a1a-2e7dc8c2b152",
            "sourceColumn": " DESCRICAO MEGA ROTA ",
            "summarizeBy": "none"
          },
          {
            "name": " EAD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0294798a-726a-41b5-94c6-89ae87da7d05",
            "sourceColumn": " EAD",
            "summarizeBy": "none"
          },
          {
            "name": "EAD FATURADO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "20f8d42c-e11e-4ea7-a85d-980868eea795",
            "sourceColumn": "EAD FATURADO",
            "summarizeBy": "none"
          },
          {
            "name": "TRANSIT POINT                                                                                                            ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "979dc727-6ffa-4723-ba7b-ac4f486c610e",
            "sourceColumn": "TRANSIT POINT                                                                                                            ",
            "summarizeBy": "none"
          },
          {
            "name": "TIPO DE ENTREGA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3fb17221-f27f-47ac-bdb6-098b331ed74d",
            "sourceColumn": "TIPO DE ENTREGA",
            "summarizeBy": "none"
          },
          {
            "name": "TRANSP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9bd39d39-3bf7-4bd3-9d68-9a97b30a4060",
            "sourceColumn": "TRANSP",
            "summarizeBy": "none"
          },
          {
            "name": "status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "91ed415a-a19a-4d47-a02e-3fcb7f68ea7a",
            "sourceColumn": "status",
            "summarizeBy": "none"
          },
          {
            "name": "data limite",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "2caedf91-ad11-4152-866b-3361c2ee2b0b",
            "sourceColumn": "data limite",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_a6bf9114-e982-44b9-a50c-2f6304f840bf"
                },
                "isDefault": true,
                "relationship": "baabe591-c8d7-4567-b3e0-9bccae454288"
              }
            ]
          },
          {
            "name": "data limite2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "99496585-239e-47e4-afc8-1615710f5233",
            "sourceColumn": "data limite2",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_3926822b-92bc-4a54-a29e-0e2ec41e514a"
                },
                "isDefault": true,
                "relationship": "24bdac68-10c2-47e6-b86f-fa978fe8f936"
              }
            ]
          }
        ],
        "lineageTag": "ad533f5d-5eff-4721-ac8c-84768f608d64",
        "partitions": [
          {
            "name": "carteira",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = SharePoint.Contents(\"https://viavarejo.sharepoint.com/sites/grupo_de_dados_wave\", [ApiVersion = 15]),",
                "    #\"Atualizaes de Relatrios Gerais\" = Fonte{[Name=\"Atualizaes de Relatrios Gerais\"]}[Content],",
                "    #\"Relatórios dinâmicos - ADMs - Vinicius & Almeida\" = #\"Atualizaes de Relatrios Gerais\"{[Name=\"Relatórios dinâmicos - ADMs - Vinicius & Almeida\"]}[Content],",
                "    #\"Relatórios rotativos\" = #\"Relatórios dinâmicos - ADMs - Vinicius & Almeida\"{[Name=\"Relatórios rotativos\"]}[Content],",
                "    #\"Painel Online - ADMs - Vinicius & Almeida\" = #\"Relatórios rotativos\"{[Name=\"Painel Online - ADMs - Vinicius & Almeida\"]}[Content],",
                "    #\"Carteira - ADMs - Vinicius & Almeida\" = #\"Painel Online - ADMs - Vinicius & Almeida\"{[Name=\"Carteira - ADMs - Vinicius & Almeida\"]}[Content],",
                "    #\"Arquivos Ocultos Filtrados1\" = Table.SelectRows(#\"Carteira - ADMs - Vinicius & Almeida\", each [Attributes]?[Hidden]? <> true),",
                "    #\"Arquivos Ocultos Filtrados2\" = Table.SelectRows(#\"Arquivos Ocultos Filtrados1\", each [Attributes]?[Hidden]? <> true),",
                "    #\"Invocar Função Personalizada1\" = Table.AddColumn(#\"Arquivos Ocultos Filtrados2\", \"Transformar Arquivo (6)\", each #\"Transformar Arquivo (6)\"([Content])),",
                "    #\"Colunas Renomeadas1\" = Table.RenameColumns(#\"Invocar Função Personalizada1\", {\"Name\", \"Nome da Origem\"}),",
                "    #\"Outras Colunas Removidas1\" = Table.SelectColumns(#\"Colunas Renomeadas1\", {\"Nome da Origem\", \"Transformar Arquivo (6)\"}),",
                "    #\"Coluna de Tabela Expandida1\" = Table.ExpandTableColumn(#\"Outras Colunas Removidas1\", \"Transformar Arquivo (6)\", Table.ColumnNames(#\"Transformar Arquivo (6)\"(#\"Arquivo de Amostra (6)\"))),",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(#\"Coluna de Tabela Expandida1\",{\"Nome da Origem\"}),",
                "    #\"Valor Substituído\" = Table.ReplaceValue(#\"Colunas Removidas\",\" \",\"\",Replacer.ReplaceText,{\" UF_ROTA\"}),",
                "    #\"Linhas Filtradas\" = Table.SelectRows(#\"Valor Substituído\", each [#\" UF_ROTA\"] = \"SP1989\" or [#\" UF_ROTA\"] = \"SP2023\" or [#\" UF_ROTA\"] = \"SP2027\" or [#\" UF_ROTA\"] = \"SP2856\" or [#\" UF_ROTA\"] = \"SP2869\" or [#\" UF_ROTA\"] = \"SP2870\" or [#\" UF_ROTA\"] = \"SP2871\" or [#\" UF_ROTA\"] = \"SP2872\" or [#\" UF_ROTA\"] = \"SP2873\" or [#\" UF_ROTA\"] = \"SP2874\" or [#\" UF_ROTA\"] = \"SP2875\" or [#\" UF_ROTA\"] = \"SP2894\" or [#\" UF_ROTA\"] = \"SP2895\" or [#\" UF_ROTA\"] = \"SP2896\" or [#\" UF_ROTA\"] = \"SP2911\" or [#\" UF_ROTA\"] = \"SP2912\" or [#\" UF_ROTA\"] = \"SP2914\" or [#\" UF_ROTA\"] = \"SP2915\" or [#\" UF_ROTA\"] = \"SP2916\" or [#\" UF_ROTA\"] = \"SP2921\" or [#\" UF_ROTA\"] = \"SP2922\" or [#\" UF_ROTA\"] = \"SP2923\" or [#\" UF_ROTA\"] = \"SP2924\" or [#\" UF_ROTA\"] = \"SP2925\" or [#\" UF_ROTA\"] = \"SP2937\" or [#\" UF_ROTA\"] = \"SP2938\" or [#\" UF_ROTA\"] = \"SP1976\" or [#\" UF_ROTA\"] = \"SP2041\" or [#\" UF_ROTA\"] = \"SP2042\" or [#\" UF_ROTA\"] = \"SP2043\" or [#\" UF_ROTA\"] = \"SP2044\" or [#\" UF_ROTA\"] = \"SP2249\" or [#\" UF_ROTA\"] = \"SP2311\"),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Linhas Filtradas\",{{\" TIPO \", type text}, {\"  PEDIDOS   \", Int64.Type}, {\" DESMEMB  \", Int64.Type}, {\" ORDEM_VENDA     \", type text}, {\" STATUS_PEDIDO       \", type text}, {\" QT_SKU \", Int64.Type}, {\" CD_SKU      \", Int64.Type}, {\" DS_SKU                                           \", type text}, {\" DIRETORIA                      \", type text}, {\" DT_EMI_CARGA\", type date}, {\"DEST \", Int64.Type}, {\" FIL_DST\", Int64.Type}, {\"TAF\", type text}, {\" RSR  \", Int64.Type}, {\"FIL_RESER\", Int64.Type}, {\"TAF_1\", type text}, {\"   TRANSPORTADOR                         \", type text}, {\" UF_DES  \", type text}, {\"DT_PREV_CARGA\", type date}, {\"   CARGA   \", Int64.Type}, {\"ST\", type text}, {\"MIC ZON \", type text}, {\"RT\", type text}, {\"CBG_PV   \", type number}, {\"DT_LIMITE  \", type date}, {\" VALOR_DO_ITEM    \", type number}, {\"TIPOETG\", type text}, {\"DATA PVE/MIG \", type date}, {\" DATA_PROMETIDA \", type date}, {\"DIAS_ROTA \", type number}, {\"REGIAO \", type number}, {\" VENDA  \", type text}, {\" TIPO_SKU\", type text}, {\" HORA_VENDA\", type time}, {\"DATA_MARCADA \", type date}, {\" CATEGORIA  \", type text}, {\" COD.MUNICIPIO \", Int64.Type}, {\" DESC. MUNICIPIO \", type text}, {\" LOGRADOURO                     \", type text}, {\" NUMERO     \", Int64.Type}, {\" BAIRRO          \", type text}, {\" FREQUENCIA DA MICROZONA        \", type text}, {\" CEP        \", Int64.Type}, {\" PEDIDO CRITICO(S/N) \", type text}, {\" CROSS DOCKING (S/N) \", type text}, {\" UNIDADE DE NEGOCIO \", type text}, {\"ID - MEGA ROTA \", Int64.Type}, {\" DESCRICAO MEGA ROTA \", type text}, {\" EAD\", type text}}),",
                "    #\"Linhas Filtradas2\" = Table.SelectRows(#\"Tipo Alterado\", each true),",
                "    #\"Dividir Coluna por Delimitador\" = Table.SplitColumn(#\"Linhas Filtradas2\", \"   TRANSPORTADOR                         \", Splitter.SplitTextByDelimiter(\"-\", QuoteStyle.Csv), {\"   TRANSPORTADOR                         .1\", \"   TRANSPORTADOR                         .2\"}),",
                "    #\"Tipo Alterado1\" = Table.TransformColumnTypes(#\"Dividir Coluna por Delimitador\",{{\"   TRANSPORTADOR                         .1\", Int64.Type}}),",
                "    #\"Personalização Adicionada\" = Table.AddColumn(#\"Tipo Alterado1\", \"TIPO DE ENTREGA\", each if [#\" UF_ROTA\"] = \"SP1989\" then \"Normal\" ",
                "else if [#\" UF_ROTA\"] = \"SP2023\" then \"Correios\"",
                "else if [#\" UF_ROTA\"] = \"SP2027\" then \"Expressa\" ",
                "else if [#\" UF_ROTA\"] = \"SP2869\" then \"Mega Rota JDI x RP\"",
                "else if [#\" UF_ROTA\"] = \"SP2870\" then \"Mega Rota JDI x BA\" ",
                "else if [#\" UF_ROTA\"] = \"SP2871\" then \"Mega Rota JDI x RJ\" ",
                "else if [#\" UF_ROTA\"] = \"SP2872\" then \"Mega Rota JDI x RS\" ",
                "else if [#\" UF_ROTA\"] = \"SP2873\" then \"Mega Rota JDI x PR\" ",
                "else if [#\" UF_ROTA\"] = \"SP2874\" then \"Mega Rota JDI x SBC\" ",
                "else if [#\" UF_ROTA\"] = \"SP2875\" then \"Mega Rota JDI x MG\" ",
                "else if [#\" UF_ROTA\"] = \"SP2894\" then \"Mega Rota 1200 DIALOGO\" ",
                "else if [#\" UF_ROTA\"] = \"SP2895\" then \"Mega Rota 1200 SAME DAY\" ",
                "else if [#\" UF_ROTA\"] = \"SP2896\" then \"Mega Rota 1200 DIRETA\" ",
                "else if [#\" UF_ROTA\"] = \"SP2922\" then \"Mega Rota JDI x PE\" ",
                "else if [#\" UF_ROTA\"] = \"SP2923\" then \"Mega Rota JDI x FBX\" ",
                "else if [#\" UF_ROTA\"] = \"SP2856\" then \"TP\" ",
                "else if [#\" UF_ROTA\"] = \"SP2921\" then \"TP-EAD\" ",
                "else \"TP-EAD\"),",
                "    #\"Tipo Alterado2\" = Table.TransformColumnTypes(#\"Personalização Adicionada\",{{\"TIPO DE ENTREGA\", type text}}),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Tipo Alterado2\",{{\" UF_ROTA\", \"ROTA\"}}),",
                "    #\"Linhas Filtradas1\" = Table.SelectRows(#\"Colunas Renomeadas\", each ([ST] <> \"T \")),",
                "    #\"Personalização Adicionada1\" = Table.AddColumn(#\"Linhas Filtradas1\", \"TRANSP\", each if [#\"   TRANSPORTADOR                         .1\"] = ",
                "85186 then \"VVLOG\" else \"BR\"),",
                "    #\"Tipo Alterado4\" = Table.TransformColumnTypes(#\"Personalização Adicionada1\",{{\"DT_LIMITE  \", type datetime}}),",
                "    #\"Personalização Adicionada3\" = Table.AddColumn(#\"Tipo Alterado4\", \"data limite\", each if [TRANSP] = \"BR\" then ",
                "[#\"DT_LIMITE  \"] + #duration(0, 23, 59,59)",
                "else ",
                "[#\"DT_LIMITE  \"] + #duration(0, 23, 59,59)),",
                "    #\"Tipo Alterado5\" = Table.TransformColumnTypes(#\"Personalização Adicionada3\",{{\"data limite\", type datetime}}),",
                "    #\"Personalização Adicionada2\" = Table.AddColumn(#\"Tipo Alterado5\", \"status\", each // trat. sexta",
                "if Date.DayOfWeek(DateTime.LocalNow()) = 5 and (Duration.Days(DateTime.From([data limite]) - DateTime.LocalNow()) = 3) then \"D+1\"",
                "else if Date.DayOfWeek(DateTime.LocalNow()) = 5 and (Duration.Days(DateTime.From([data limite]) - DateTime.LocalNow()) = 4) then \"D+2\"",
                "else if Date.DayOfWeek(DateTime.LocalNow()) = 5 and (Duration.Days(DateTime.From([data limite]) - DateTime.LocalNow()) > 4) then \" >D+2\"",
                "",
                "// trat. sábado",
                "else if Date.DayOfWeek(DateTime.LocalNow()) = 6 and (Duration.Days(DateTime.From([data limite]) - DateTime.LocalNow()) = 2) then \"Vence Segunda\"",
                "else if Date.DayOfWeek(DateTime.LocalNow()) = 6 and (Duration.Days(DateTime.From([data limite]) - DateTime.LocalNow()) = 3 ) then \"D+1\"",
                "else if Date.DayOfWeek(DateTime.LocalNow()) = 6 and (Duration.Days(DateTime.From([data limite]) - DateTime.LocalNow()) = 4) then \"D+2\"",
                "else if Date.DayOfWeek(DateTime.LocalNow()) = 6 and (Duration.Days(DateTime.From([data limite]) - DateTime.LocalNow()) > 4) then \" >D+2\"",
                "",
                "// trat. domingo",
                "else if Date.DayOfWeek(DateTime.LocalNow()) = 0 and (Duration.Days(DateTime.From([data limite]) - DateTime.LocalNow()) = 1) then \"Vence Segunda\"",
                "else if Date.DayOfWeek(DateTime.LocalNow()) = 0 and (Duration.Days(DateTime.From([data limite]) - DateTime.LocalNow()) = 2 ) then \"D+1\"",
                "else if Date.DayOfWeek(DateTime.LocalNow()) = 0 and (Duration.Days(DateTime.From([data limite]) - DateTime.LocalNow()) = 3) then \"D+2\"",
                "else if Date.DayOfWeek(DateTime.LocalNow()) = 0 and (Duration.Days(DateTime.From([data limite]) - DateTime.LocalNow()) > 3) then \" >D+2\"",
                "",
                "",
                "// trat. semana ",
                "else if DateTime.From([data limite]) < DateTime.LocalNow() then \"Vencidos\"",
                "else if Duration.Days(DateTime.From([data limite]) - DateTime.LocalNow()) = 0 then \"Vence Hoje\"",
                "else if Duration.Days(DateTime.From([data limite]) - DateTime.LocalNow()) = 1 then \"D+1\"",
                "else if Duration.Days(DateTime.From([data limite]) - DateTime.LocalNow()) = 2 then \"D+2\"",
                "else if Duration.Days(DateTime.From([data limite]) - DateTime.LocalNow()) > 2 then \" >D+2\"",
                "",
                "// trat. sobra",
                "else \"tratar sobra\"),",
                "    #\"Tipo Alterado3\" = Table.TransformColumnTypes(#\"Personalização Adicionada2\",{{\"status\", type text}}),",
                "    #\"Coluna Duplicada\" = Table.DuplicateColumn(#\"Tipo Alterado3\", \"data limite\", \"data limite - Copiar\"),",
                "    #\"Tipo Alterado6\" = Table.TransformColumnTypes(#\"Coluna Duplicada\",{{\"data limite - Copiar\", type date}}),",
                "    #\"Colunas Renomeadas2\" = Table.RenameColumns(#\"Tipo Alterado6\",{{\"data limite - Copiar\", \"data limite2\"}})",
                "in",
                "    #\"Colunas Renomeadas2\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_c4d33cb2-a1aa-4080-9242-482afcb197a5",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "e8bbd09a-d284-4f05-bcb9-731ce8f6696e",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "973d547a-8943-43df-9bf5-4ff5c2e39333",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "50511a65-8c6f-4f6e-a5b6-174424328e6a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "1457e108-1daa-4fd2-8883-27e165755f40",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "2287a8fd-6190-49ca-a26b-d723c84992d8",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "2397dcc4-626e-42af-bce1-83c8980a5a41",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "9c9092c3-a7c5-4901-b4a3-1fbbdf7d931c",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "6dae5c05-944e-4af0-99e5-7ad8907ced78",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "c8a3a711-e2a6-4975-9015-43945591c254",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "33e2a371-c5fd-4835-a68e-1fe96cc4b523",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "0630f8d1-33ba-480c-a219-8cc2e49400a1",
                "ordinal": 3
              }
            ],
            "lineageTag": "02551cd0-f97b-471b-b8d5-99dc2f7c0355"
          }
        ],
        "isHidden": true,
        "lineageTag": "12287d41-9040-4038-ae12-7bd537c2b2a2",
        "partitions": [
          {
            "name": "LocalDateTable_c4d33cb2-a1aa-4080-9242-482afcb197a5",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('carteira'[ DT_EMI_CARGA])), 1, 1), Date(Year(MAX('carteira'[ DT_EMI_CARGA])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_7d8dcf04-db06-423d-bd1c-964028d29b65",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "96e7d4a3-1132-4825-831b-315fcc704f0e",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "30c607fc-b6db-46ec-9401-98dcbe2bdc7e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "0444606a-2ff4-49ce-97c1-012d0d333990",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "743d49da-fa16-4b1a-bfea-c31861b79715",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "9ed2a4b3-3ff8-44eb-aec5-caf0d0073c7a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "270b3857-04d4-4ebc-a508-5b6370b98590",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "af98deff-2a77-43a5-b7fe-cc5c13723c60",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "8ee39194-ba20-41b3-a3fb-e2b395692a97",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "09167a82-a845-4aa1-863a-fbabeb547233",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "760867ee-e6de-458d-a633-687912984d61",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "e0859d29-412f-407e-9c84-dc1449d54fe2",
                "ordinal": 3
              }
            ],
            "lineageTag": "e4c18a84-3fe2-4e0f-84bd-c2296e63e83c"
          }
        ],
        "isHidden": true,
        "lineageTag": "fa415f43-1fbf-4a6a-8b6c-b21899c78db3",
        "partitions": [
          {
            "name": "LocalDateTable_7d8dcf04-db06-423d-bd1c-964028d29b65",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('carteira'[DT_PREV_CARGA])), 1, 1), Date(Year(MAX('carteira'[DT_PREV_CARGA])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_651663f4-1ba0-4bf3-af74-833f6eb94270",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "e96236c6-7c14-49cd-93c7-b4ce6bd4fbd5",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "7a34c52c-ac44-4655-9af2-2127cec3543e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "f42f5763-ae03-4fbe-b589-49bc7a31c210",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "034e3ff5-3c53-48e5-8f1f-1b149209af5a",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "7ea6486f-dbc3-466c-b1b8-cfc4e23c289f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "a3f8f9d1-7bda-4528-9320-ea0e5756aa83",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "d818f949-87bc-4507-922a-168a8bd3f963",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "a85828db-0655-4962-bf41-b2950e158a65",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "ba2c7e6f-96ef-44a0-bbe2-9b972b0168ca",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "d7315a1e-2c8d-4a22-b1fa-ab6b35434e3e",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "a483dfb6-d12e-4be8-a64e-88fe143fa504",
                "ordinal": 3
              }
            ],
            "lineageTag": "63f0ddcb-1077-4799-840d-80c5b923f6a8"
          }
        ],
        "isHidden": true,
        "lineageTag": "9bca0ca6-f2b4-49b1-b231-6448b9bc6145",
        "partitions": [
          {
            "name": "LocalDateTable_651663f4-1ba0-4bf3-af74-833f6eb94270",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('carteira'[DT_LIMITE  ])), 1, 1), Date(Year(MAX('carteira'[DT_LIMITE  ])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_ed27a44c-4c3c-4b63-94ef-30d85b1de634",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "01a87f83-fe3a-4fa7-b423-f8ffdf03475c",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "387f08c4-b6b1-4b99-a43e-555a536a2eed",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "097f95db-59e7-400f-98fd-ca6783115e83",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "7a253090-191c-46eb-9e3c-6b09d47d1d48",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "d269d961-8f5a-4ca9-9624-88438198b26f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "30749652-b54d-4e82-bc90-ac2eadc0d5ec",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "db8c880a-777e-47c1-9fb6-eb6040790f5d",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "153b1dd3-c887-482e-bf42-0a06a0c099ee",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "078e7dc4-a4dd-48c6-957c-d2aeb3b21fe8",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "b588dc14-2a4e-4d7f-92b5-10eb97646fb5",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "e5c884cf-f01b-4cd0-a34e-5ef6432c21fb",
                "ordinal": 3
              }
            ],
            "lineageTag": "d2328519-18f8-4c1a-8049-6ef8c6683a47"
          }
        ],
        "isHidden": true,
        "lineageTag": "380e212b-2bb8-46a2-9f69-a3b267dae9da",
        "partitions": [
          {
            "name": "LocalDateTable_ed27a44c-4c3c-4b63-94ef-30d85b1de634",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('carteira'[DATA PVE/MIG ])), 1, 1), Date(Year(MAX('carteira'[DATA PVE/MIG ])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_5d585d2d-fdca-4b22-ab1b-b15d208473a7",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "e7b1f9a2-0ed1-4f42-9af7-90750dd90411",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "b7b55f3e-fe9f-464b-90a3-1b49f934601d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "c6e53fdc-b98f-4f0b-9ade-20560271db41",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "5ee0ed63-f9da-4432-82b9-61b648975249",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "3abb7b01-ac79-4090-8105-8dfd748e5141",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "2d756032-7511-4ee1-ae86-bca6a393201d",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "9f86852f-b18a-49b5-99a7-2198f43f866b",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "5d67d2c2-6d90-4c9f-b9ea-d9cb64fcb965",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "4e1628aa-10bf-43d9-bd7e-3c6454bcbafc",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "f9eb15fc-b18f-48da-9d61-3f4a4f4b2d02",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "75ee949f-1778-47d4-8fd2-91bca50b89d8",
                "ordinal": 3
              }
            ],
            "lineageTag": "4ee6694b-aa0b-4167-87f7-78924e7b5e56"
          }
        ],
        "isHidden": true,
        "lineageTag": "8641f318-7992-4d2f-9804-6992b083f454",
        "partitions": [
          {
            "name": "LocalDateTable_5d585d2d-fdca-4b22-ab1b-b15d208473a7",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('carteira'[ DATA_PROMETIDA ])), 1, 1), Date(Year(MAX('carteira'[ DATA_PROMETIDA ])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_a1e482f1-8307-44d3-9932-440eaad15ef6",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "3822d201-1d87-4982-8191-f185463750dd",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "ac1efa98-a59c-467b-a587-b762b2076205",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "34932f64-ba0c-40cd-a423-e29b364b9eae",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "6f34660a-c22d-4f79-a7d2-6d16893f4472",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "9156be38-29ef-4497-8e81-d446be115a3a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "fa4931b0-3b5f-44cd-8ad7-9e7c72b6cdf1",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "f0619b18-1dde-486a-b968-039b5e5c27be",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "3e1505d7-71f4-4396-ac96-f8e15ba40fae",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "06958fdc-4497-4f9e-87b3-53791e66e615",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "63c1becb-19cb-4541-ab07-210252b02df6",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "3af7ff36-3a3c-4ed8-b181-474c3ff0c0de",
                "ordinal": 3
              }
            ],
            "lineageTag": "0c7597c1-e78c-406b-bca7-e848159ac0d3"
          }
        ],
        "isHidden": true,
        "lineageTag": "a4da7409-e4c2-4742-8f2c-e338aa5ce895",
        "partitions": [
          {
            "name": "LocalDateTable_a1e482f1-8307-44d3-9932-440eaad15ef6",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('carteira'[DATA_MARCADA ])), 1, 1), Date(Year(MAX('carteira'[DATA_MARCADA ])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "status oLPN",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "Filial",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "32875656-b1dc-4040-944a-c3e4243e00d8",
            "sourceColumn": "Filial",
            "summarizeBy": "sum"
          },
          {
            "name": "Data do Pedido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "40ee835e-be12-4924-8b7e-8a715a4f44c9",
            "sourceColumn": "Data do Pedido",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_d1bb81b4-3c99-41ee-abbe-7fc1bfedfb22"
                },
                "isDefault": true,
                "relationship": "d2213630-53aa-4edc-861e-59b571fe29c2"
              }
            ]
          },
          {
            "name": "Tipo de pedido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "65a9dfb7-b177-4d94-b861-c554787addfe",
            "sourceColumn": "Tipo de pedido",
            "summarizeBy": "none"
          },
          {
            "name": "Wave",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4ac65014-cdf9-4a70-b036-e119b755154e",
            "sourceColumn": "Wave",
            "summarizeBy": "none"
          },
          {
            "name": "Data locação pedido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "3dca81e4-11f0-417a-a278-90dd47d66013",
            "sourceColumn": "Data locação pedido",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_c63d3909-04ff-4e99-855a-2f8fa1504e6f"
                },
                "isDefault": true,
                "relationship": "03547ef9-133e-4075-ad78-af121ac65606"
              }
            ]
          },
          {
            "name": "Shipment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6145b2d8-8c3d-492f-85b5-5c51a18e3dff",
            "sourceColumn": "Shipment",
            "summarizeBy": "sum"
          },
          {
            "name": "Filial Destino",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "20c9494a-6429-4eb1-a534-3e0e18a84d92",
            "sourceColumn": "Filial Destino",
            "summarizeBy": "sum"
          },
          {
            "name": "Pedido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "60046242-0b1d-40f3-8315-7c70379f64ed",
            "sourceColumn": "Pedido",
            "summarizeBy": "sum"
          },
          {
            "name": "Status Pedido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "02602ce8-a2d1-498c-8774-064d558d1784",
            "sourceColumn": "Status Pedido",
            "summarizeBy": "none"
          },
          {
            "name": "Pedido de Venda",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e612f1c3-a5e3-4922-81cc-3cc365c6fa75",
            "sourceColumn": "Pedido de Venda",
            "summarizeBy": "sum"
          },
          {
            "name": "oLPN",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "15f740db-60a3-4b60-8d91-9df09cba304f",
            "sourceColumn": "oLPN",
            "summarizeBy": "sum"
          },
          {
            "name": "Último Update oLPN",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "d347fd42-7e8e-4c71-91d9-30a586ae51a9",
            "sourceColumn": "Último Update oLPN",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_26ede0fe-5b25-41aa-a9c9-3632ca32ab7e"
                },
                "isDefault": true,
                "relationship": "d36c33b1-04e0-4f25-8514-0c12b2e7b7ed"
              }
            ]
          },
          {
            "name": "TOTE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3c284e9a-19e9-402c-9081-1fa8b0ebe524",
            "sourceColumn": "TOTE",
            "summarizeBy": "none"
          },
          {
            "name": "Tarefa",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "99ff54c6-ba26-47d7-b461-578d3ff811dc",
            "sourceColumn": "Tarefa",
            "summarizeBy": "none"
          },
          {
            "name": "Tarefa Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0eef4328-c8b8-4a79-8707-f6d14176303e",
            "sourceColumn": "Tarefa Status",
            "summarizeBy": "none"
          },
          {
            "name": "Grupo de Tarefa",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "34b44fa4-5daa-4ddb-a105-9628c3e30287",
            "sourceColumn": "Grupo de Tarefa",
            "summarizeBy": "none"
          },
          {
            "name": "Item",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "76d67501-7d61-42ce-b64e-9ce0ca383138",
            "sourceColumn": "Item",
            "summarizeBy": "sum"
          },
          {
            "name": "Descrição",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "56905b27-e390-41c4-8485-ee1f99285cb4",
            "sourceColumn": "Descrição",
            "summarizeBy": "none"
          },
          {
            "name": "Local de Picking",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a328007e-b638-474b-8b49-4b39ad2c32df",
            "sourceColumn": "Local de Picking",
            "summarizeBy": "none"
          },
          {
            "name": "Qtde. Peças Item",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c1e0b445-4f65-4d37-8d16-a4c2a6f2331d",
            "sourceColumn": "Qtde. Peças Item",
            "summarizeBy": "sum"
          },
          {
            "name": "Volume",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8aafdcd2-8719-499e-a719-b218c8c22ff9",
            "sourceColumn": "Volume",
            "summarizeBy": "sum"
          },
          {
            "name": "Status oLPN",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dbddb3b6-902b-4bd6-bd54-2c40fb35b0b0",
            "sourceColumn": "Status oLPN",
            "summarizeBy": "none"
          },
          {
            "name": "Numero da Gaiola",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1adaff0a-b3c1-4ded-970d-f13510330807",
            "sourceColumn": "Numero da Gaiola",
            "summarizeBy": "sum"
          },
          {
            "name": "BOX",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "08d0a744-794e-4423-9878-88557a7bb0d0",
            "sourceColumn": "BOX",
            "summarizeBy": "sum"
          },
          {
            "name": "Marcação de EAD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5e610003-1f54-415b-9117-12693981782e",
            "sourceColumn": "Marcação de EAD",
            "summarizeBy": "none"
          },
          {
            "name": "Data Prevista Entrega",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "02ec7e10-f2a4-440e-afe0-6658664076d9",
            "sourceColumn": "Data Prevista Entrega",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_7cccec5d-27f3-406a-8bc5-57140bba9558"
                },
                "isDefault": true,
                "relationship": "b794c020-44b5-4fcd-bd82-5654f0d17fb3"
              }
            ]
          },
          {
            "name": "Inventory Type ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4bcbc22d-76b2-40a7-80a5-3264b8515546",
            "sourceColumn": "Inventory Type ID",
            "summarizeBy": "count"
          },
          {
            "name": "Cod Setor Item",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "21f66fe1-59fe-4c27-ac85-43cc3096eea2",
            "sourceColumn": "Cod Setor Item",
            "summarizeBy": "sum"
          },
          {
            "name": "Desc Setor Item",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5983bd63-4454-4290-9a5d-d09e1a5a73df",
            "sourceColumn": "Desc Setor Item",
            "summarizeBy": "none"
          },
          {
            "name": "Audit Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "535b9900-ffd9-4623-bd67-e80887fe8153",
            "sourceColumn": "Audit Status",
            "summarizeBy": "none"
          },
          {
            "name": "Etapa",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dfd2b2ac-b93d-4fce-a2c6-d7d3361609f8",
            "sourceColumn": "Etapa",
            "summarizeBy": "none"
          },
          {
            "name": "status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "afce452f-4fd3-456e-8898-c3075b3edcd6",
            "sourceColumn": "status",
            "summarizeBy": "none"
          },
          {
            "name": "Data",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8a40df58-558c-4794-9151-3c4b178aaa5a",
            "sourceColumn": "Data",
            "summarizeBy": "none"
          },
          {
            "name": "Rota",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "97b8d092-8c75-4399-a82f-6e6424e524ca",
            "sourceColumn": "Rota",
            "summarizeBy": "none"
          },
          {
            "name": "Setor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8a6760eb-313c-4f08-ba03-6281dfc1b048",
            "sourceColumn": "Setor",
            "summarizeBy": "none"
          },
          {
            "name": "area",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0e534493-6cb7-4c47-adf5-bb5aacd92d6e",
            "sourceColumn": "area",
            "summarizeBy": "none"
          },
          {
            "name": "Atraso",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2190ca24-30d2-4fe8-8d97-37478ec1145e",
            "sourceColumn": "Atraso",
            "summarizeBy": "none"
          },
          {
            "name": "descricao_atividade",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5d3a6a70-d0c4-4bbd-b90d-6d2d1cc8c029",
            "sourceColumn": "descricao_atividade",
            "summarizeBy": "none"
          },
          {
            "name": "Data Limite Expedição",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "e9eb1e26-ed06-41b9-b587-cd3717a9879f",
            "sourceColumn": "Data Limite Expedição",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_ac232e2a-83b0-4b47-81e3-e9456bc653d8"
                },
                "isDefault": true,
                "relationship": "00bd9f8f-72d6-4cc0-b530-4032899845f3"
              }
            ]
          },
          {
            "name": "data para a data",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "c6474510-6b82-4a38-8f76-58ba13029c44",
            "sourceColumn": "data para a data",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_70ce231e-4aa2-4a70-9ace-ea66fc5068c6"
                },
                "isDefault": true,
                "relationship": "71752ec7-72a9-4414-82f3-c0f161ceee34"
              }
            ]
          }
        ],
        "lineageTag": "3c4b09b5-1f59-4601-b6d1-ccffea4e39a5",
        "partitions": [
          {
            "name": "status oLPN",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = SharePoint.Contents(\"https://viavarejo.sharepoint.com/sites/grupo_de_dados_wave\", [ApiVersion = 15]),",
                "    #\"Atualizaes de Relatrios Gerais\" = Fonte{[Name=\"Atualizaes de Relatrios Gerais\"]}[Content],",
                "    #\"Relatórios dinâmicos - ADMs - Vinicius & Almeida\" = #\"Atualizaes de Relatrios Gerais\"{[Name=\"Relatórios dinâmicos - ADMs - Vinicius & Almeida\"]}[Content],",
                "    #\"Relatórios rotativos\" = #\"Relatórios dinâmicos - ADMs - Vinicius & Almeida\"{[Name=\"Relatórios rotativos\"]}[Content],",
                "    #\"Painel Online - ADMs - Vinicius & Almeida\" = #\"Relatórios rotativos\"{[Name=\"Painel Online - ADMs - Vinicius & Almeida\"]}[Content],",
                "    #\"Status oLPN - ADMs - Vinicius & Almeida\" = #\"Painel Online - ADMs - Vinicius & Almeida\"{[Name=\"Status oLPN - ADMs - Vinicius & Almeida\"]}[Content],",
                "    #\"Arquivos Ocultos Filtrados1\" = Table.SelectRows(#\"Status oLPN - ADMs - Vinicius & Almeida\", each [Attributes]?[Hidden]? <> true),",
                "    #\"Invocar Função Personalizada1\" = Table.AddColumn(#\"Arquivos Ocultos Filtrados1\", \"Transformar Arquivo (8)\", each #\"Transformar Arquivo (8)\"([Content])),",
                "    #\"Colunas Renomeadas1\" = Table.RenameColumns(#\"Invocar Função Personalizada1\", {\"Name\", \"Nome da Origem\"}),",
                "    #\"Outras Colunas Removidas1\" = Table.SelectColumns(#\"Colunas Renomeadas1\", {\"Nome da Origem\", \"Transformar Arquivo (8)\"}),",
                "    #\"Coluna de Tabela Expandida1\" = Table.ExpandTableColumn(#\"Outras Colunas Removidas1\", \"Transformar Arquivo (8)\", Table.ColumnNames(#\"Transformar Arquivo (8)\"(#\"Arquivo de Amostra (8)\"))),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Coluna de Tabela Expandida1\",{{\"Nome da Origem\", type text}, {\"Filial\", Int64.Type}, {\"Data do Pedido\", type datetime}, {\"Tipo de pedido\", type text}, {\"Wave\", type text}, {\"Data locação pedido\", type datetime}, {\"Shipment\", Int64.Type}, {\"Filial Destino\", Int64.Type}, {\"Pedido\", Int64.Type}, {\"Status Pedido\", type text}, {\"Pedido de Venda\", Int64.Type}, {\"oLPN\", Int64.Type}, {\"Último Update oLPN\", type datetime}, {\"TOTE\", type text}, {\"Tarefa\", type text}, {\"Tarefa Status\", type text}, {\"Grupo de Tarefa\", type text}, {\"Item\", Int64.Type}, {\"Descrição\", type text}, {\"Local de Picking\", type text}, {\"Qtde. Peças Item\", Int64.Type}, {\"Volume\", type number}, {\"Status oLPN\", type text}, {\"Numero da Gaiola\", Int64.Type}, {\"BOX\", Int64.Type}, {\"Marcação de EAD\", type any}, {\"Data Prevista Entrega\", type date}, {\"Data Limite Expedição\", type date}, {\"Inventory Type ID\", Int64.Type}, {\"Cod Setor Item\", Int64.Type}, {\"Desc Setor Item\", type text}, {\"Audit Status\", type text}}),",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(#\"Tipo Alterado\",{\"Nome da Origem\"}),",
                "    #\"Data Extraída\" = Table.TransformColumns(#\"Colunas Removidas\",{{\"Data do Pedido\", DateTime.Date, type date}}),",
                "    #\"Linhas Filtradas\" = Table.SelectRows(#\"Data Extraída\", each ([Status oLPN] <> \"Cancelled\")),",
                "    #\"Tipo Alterado9\" = Table.TransformColumnTypes(#\"Linhas Filtradas\",{{\"Data do Pedido\", type datetime}, {\"Data Prevista Entrega\", type datetime}, {\"Data Limite Expedição\", type datetime}}),",
                "    #\"Personalização Adicionada\" = Table.AddColumn(#\"Tipo Alterado9\", \"Etapa\", each if [Status oLPN] = \"Created\" then \"Created - Em Separação\"",
                "else if [Status oLPN] = \"In Progress\" then \"Created - Em Separação\"",
                "else if [Status oLPN] = \"Packing\" then \"Packed S. Gaiola - Em Faturamento\"",
                "else if [Status oLPN] = \"Packed\" and [Numero da Gaiola] = null then \"Packed S. Gaiola - Em Faturamento\"",
                "else if [Status oLPN] = \"Packed\" then \"Packed C. Gaiola - Em Expedição\"",
                "else if [Status oLPN] = \"Shipped\" then \"Shipped - Expedido\"",
                "else \"Cancelled - Cancelado\"),",
                "    #\"Tipo Alterado1\" = Table.TransformColumnTypes(#\"Personalização Adicionada\",{{\"Etapa\", type text}, {\"Data Limite Expedição\", type datetime}}),",
                "    #\"Personalização Adicionada1\" = Table.AddColumn(#\"Tipo Alterado1\", \"data\", each [Data Limite Expedição]),",
                "    #\"Colunas Removidas1\" = Table.RemoveColumns(#\"Personalização Adicionada1\",{\"Data Limite Expedição\"}),",
                "    #\"Tipo Alterado11\" = Table.TransformColumnTypes(#\"Colunas Removidas1\",{{\"data\", type date}}),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Tipo Alterado11\",{{\"data\", \"Data Limite Expedição\"}}),",
                "    status = Table.AddColumn(#\"Colunas Renomeadas\", \"status\", each // trat. simples",
                "if [Etapa] = \"Shipped - Expedido\" then \"Expedido\"",
                "else if [Etapa] = \"Cancelled - Cancelado\" then \"Cancelado\"",
                "",
                "// trat. sexta",
                "",
                "else if Date.DayOfWeek(Date.From(DateTime.LocalNow() - #duration(0, 3, 0, 0))) = 5 and (Duration.Days(Date.From([Data Limite Expedição] ) - Date.From(DateTime.LocalNow() - #duration(0, 3, 0, 0))) = 3) then \"D+1\"",
                "else if Date.DayOfWeek(Date.From(DateTime.LocalNow()- #duration(0, 3, 0, 0))) = 5 and (Duration.Days(Date.From([Data Limite Expedição] ) - Date.From(DateTime.LocalNow() - #duration(0, 3, 0, 0))) = 4) then \"D+2\"",
                "else if Date.DayOfWeek(Date.From(DateTime.LocalNow() - #duration(0, 3, 0, 0))) = 5 and (Duration.Days(Date.From([Data Limite Expedição] ) - Date.From(DateTime.LocalNow() - #duration(0, 3, 0, 0))) > 4) then \" >D+2\"",
                "",
                "// trat. sábado",
                "",
                "else if Date.DayOfWeek(Date.From(DateTime.LocalNow() - #duration(0, 3, 0, 0))) = 6 and (Duration.Days(Date.From([Data Limite Expedição] ) - Date.From(DateTime.LocalNow() - #duration(0, 3, 0, 0))) = 2) then \"Vence Segunda\"",
                "else if Date.DayOfWeek(Date.From(DateTime.LocalNow() - #duration(0, 3, 0, 0))) = 6 and (Duration.Days(Date.From([Data Limite Expedição] ) - Date.From(DateTime.LocalNow() - #duration(0, 3, 0, 0))) = 3 ) then \"D+1\"",
                "else if Date.DayOfWeek(Date.From(DateTime.LocalNow() - #duration(0, 3, 0, 0))) = 6 and (Duration.Days(Date.From([Data Limite Expedição] ) - Date.From(DateTime.LocalNow() - #duration(0, 3, 0, 0))) = 4) then \"D+2\"",
                "else if Date.DayOfWeek(Date.From(DateTime.LocalNow() - #duration(0, 3, 0, 0))) = 6 and (Duration.Days(Date.From([Data Limite Expedição] ) - Date.From(DateTime.LocalNow() - #duration(0, 3, 0, 0))) > 4) then \" >D+2\"",
                "",
                "// trat. domingo",
                "",
                "else if Date.DayOfWeek(Date.From(DateTime.LocalNow() - #duration(0, 3, 0, 0))) = 0 and (Duration.Days(Date.From([Data Limite Expedição] ) - Date.From(DateTime.LocalNow() - #duration(0, 3, 0, 0))) = 1) then \"Vence Segunda\"",
                "else if Date.DayOfWeek(Date.From(DateTime.LocalNow() - #duration(0, 3, 0, 0))) = 0 and (Duration.Days(Date.From([Data Limite Expedição] ) - Date.From(DateTime.LocalNow() - #duration(0, 3, 0, 0))) = 2 ) then \"D+1\"",
                "else if Date.DayOfWeek(Date.From(DateTime.LocalNow() - #duration(0, 3, 0, 0))) = 0 and (Duration.Days(Date.From([Data Limite Expedição] ) - Date.From(DateTime.LocalNow() - #duration(0, 3, 0, 0))) = 3) then \"D+2\"",
                "else if Date.DayOfWeek(Date.From(DateTime.LocalNow() - #duration(0, 3, 0, 0))) = 0 and (Duration.Days(Date.From([Data Limite Expedição] ) - Date.From(DateTime.LocalNow() - #duration(0, 3, 0, 0))) > 3) then \" >D+2\"",
                "",
                "",
                "// trat. semana ",
                "",
                "else if Date.From([Data Limite Expedição]) < DateTime.Date(DateTime.LocalNow()) then \"Vencidos\"",
                "else if Duration.Days(Date.From([Data Limite Expedição]) - Date.From(DateTime.LocalNow() - #duration(0, 3, 0, 0))) = 0 then \"Vence Hoje\"",
                "else if Duration.Days(Date.From([Data Limite Expedição]) - Date.From(DateTime.LocalNow() - #duration(0, 3, 0, 0))) = 1 then \"D+1\"",
                "else if Duration.Days(Date.From([Data Limite Expedição]) - Date.From(DateTime.LocalNow() - #duration(0, 3, 0, 0))) = 2 then \"D+2\"",
                "else if Duration.Days(Date.From([Data Limite Expedição]) - Date.From(DateTime.LocalNow() - #duration(0, 3, 0, 0))) > 2 then \" >D+2\"",
                "",
                "// trat. sobra",
                "",
                "else \"tratar sobra\"),",
                "    #\"Tipo Alterado2\" = Table.TransformColumnTypes(status,{{\"status\", type text}}),",
                "    #\"Coluna Duplicada\" = Table.DuplicateColumn(#\"Tipo Alterado2\", \"Data Limite Expedição\", \"Data Limite Expedição - Copiar\"),",
                "    #\"Colunas Renomeadas2\" = Table.RenameColumns(#\"Coluna Duplicada\",{{\"Data Limite Expedição - Copiar\", \"data para a data\"}}),",
                "    #\"Tipo Alterado10\" = Table.TransformColumnTypes(#\"Colunas Renomeadas2\",{{\"data para a data\", type date}}),",
                "    #\"Personalização Adicionada2\" = Table.AddColumn(#\"Tipo Alterado10\", \"Data\", each if DateTime.From([data para a data]) <= Date.AddDays(DateTime.From(DateTime.LocalNow()), -1) then ",
                "    \"<=\" & Date.ToText(Date.AddDays(Date.From(DateTime.LocalNow()), -1), \"dd/MM\")",
                "else if DateTime.From([data para a data]) >= Date.AddDays(DateTime.From(DateTime.LocalNow()), 6) then ",
                "    \">=\" & Date.ToText(Date.AddDays(Date.From(DateTime.LocalNow()), 6), \"dd/MM\")",
                "else ",
                "    [data para a data]),",
                "    #\"Tipo Alterado3\" = Table.TransformColumnTypes(#\"Personalização Adicionada2\",{{\"Data\", type text}}),",
                "    #\"Personalização Adicionada3\" = Table.AddColumn(#\"Tipo Alterado3\", \"Rota\", each if [BOX] <> 870 and [BOX] <> 872 and [BOX] <> 770 then \"BR\" else \"VVLOG\"),",
                "    #\"Tipo Alterado4\" = Table.TransformColumnTypes(#\"Personalização Adicionada3\",{{\"Rota\", type text}}),",
                "    #\"Personalização Adicionada4\" = Table.AddColumn(#\"Tipo Alterado4\", \"Setor\", each if [Status oLPN] = \"Created\" then \"01_Picking\"",
                "else if [Status oLPN] = \"In Progress\" then \"01_Picking\"",
                "else if [Status oLPN] = \"Packing\" then \"02_Packing\"",
                "else if [Status oLPN] = \"Packed\" and [Numero da Gaiola] = \"\" then \"02_Packing\"",
                "else if [Status oLPN] = \"Packed\" then \"03_Expedição\"",
                "else if [Status oLPN] = \"Shipped\" then \"Expedido\"",
                "else \"Cancelado\"),",
                "    #\"Tipo Alterado5\" = Table.TransformColumnTypes(#\"Personalização Adicionada4\",{{\"Setor\", type text}}),",
                "    #\"Personalização Adicionada5\" = Table.AddColumn(#\"Tipo Alterado5\", \"area\", each if Text.Start([Local de Picking], 2) = \"C0\" or ",
                "   Text.Start([Local de Picking], 2) = \"P0\" or ",
                "   Text.Start([Local de Picking], 2) = \"R0\" or ",
                "   Text.Middle([Local de Picking], 4, 3) = \"PAR\" then ",
                "    \"P.A.R.\" ",
                "else ",
                "    \"SALÃO\"),",
                "    #\"Tipo Alterado6\" = Table.TransformColumnTypes(#\"Personalização Adicionada5\",{{\"area\", type text}, {\"Data do Pedido\", type datetime}}),",
                "    #\"Personalização Adicionada6\" = Table.AddColumn(#\"Tipo Alterado6\", \"Atraso\", each if ",
                "    [Data Limite Expedição] <> null and DateTime.From([Data Limite Expedição]) < DateTime.LocalNow() and ",
                "    [status] <> \"Expedido\" and ",
                "    [status] <> \"Cancelado\" then ",
                "    if [Data do Pedido] <> null and DateTime.From([Data do Pedido]) > DateTime.From([Data Limite Expedição]) then ",
                "        \"INTEGRADO EM ATRASO\" ",
                "    else ",
                "        \"ATRASO\" ",
                "else ",
                "    \"-\"),",
                "    #\"Tipo Alterado7\" = Table.TransformColumnTypes(#\"Personalização Adicionada6\",{{\"Atraso\", type text}}),",
                "    #\"Personalização Adicionada7\" = Table.AddColumn(#\"Tipo Alterado7\", \"descricao_atividade\", each if [Status oLPN] = \"Shipped\" then \"09_Expedido\"",
                "else if [Status oLPN] = \"Created\" and [Tarefa Status] = null then \"01_Sem Tarefa\"",
                "else if [Status oLPN] = \"Created\" and [Tarefa Status] = \"Held\" then \"02_Held\"",
                "else if [Status oLPN] = \"Created\" and [Tarefa Status] = \"Ready For Assignment\" then \"03_Picking Liberado\"",
                "else if [Status oLPN] = \"Created\" and [Tarefa Status] = \"Assigned\" then \"04_Início de Picking\"",
                "else if [Status oLPN] = \"Created\" and ([Tarefa Status] = \"In Progress\" or [Tarefa Status] = \"Pending Complete\") then \"05_Em Separação\"",
                "else if [Status oLPN] = \"Created\" and [Tarefa Status] = \"Completed\" then \"06_Fim de Separação\"",
                "else if [Status oLPN] = \"Packed\" and [Numero da Gaiola] = null then \"07_Em Faturamento\"",
                "else if [Status oLPN] = \"Packed\" and [Numero da Gaiola] <> null then \"08_Em Expedição\"",
                "else if [Status oLPN] = \"Cancelled\" then \"10_Cancelado\"",
                "else null),",
                "    #\"Tipo Alterado8\" = Table.TransformColumnTypes(#\"Personalização Adicionada7\",{{\"descricao_atividade\", type text}}),",
                "    #\"Linhas Filtradas1\" = Table.SelectRows(#\"Tipo Alterado8\", each true)",
                "in",
                "    #\"Linhas Filtradas1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_d1bb81b4-3c99-41ee-abbe-7fc1bfedfb22",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "98e0feeb-6199-4e53-b5cb-b7ed075aaa96",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "0a2bc53c-9788-4aef-9c30-086ae7dbec65",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "f083f33d-6347-43cb-8fdb-93a155a1db9e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "d5248517-eeb1-435c-a51a-564439fc8e3b",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "a9758ca5-1a25-439d-a585-5ba41a7ab144",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "2dbc17e2-604e-47e7-9ffe-05b577e23165",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "9cef2410-9326-49b1-8118-1264c055543b",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "da8d4b3b-8dab-41d0-8264-21d2b22f4d4a",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "1bee9db6-0bf6-4d0b-8381-c7d119a5b033",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "69dcd835-aea4-452c-a266-641cbe79d43a",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "f7d384ea-22bf-447c-8c0d-371f38650c61",
                "ordinal": 3
              }
            ],
            "lineageTag": "7345f07a-608c-471f-a6e3-03b153478998"
          }
        ],
        "isHidden": true,
        "lineageTag": "fd316d2c-cf04-499c-bd57-8c52a7f5fd7d",
        "partitions": [
          {
            "name": "LocalDateTable_d1bb81b4-3c99-41ee-abbe-7fc1bfedfb22",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('status oLPN'[Data do Pedido])), 1, 1), Date(Year(MAX('status oLPN'[Data do Pedido])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_c63d3909-04ff-4e99-855a-2f8fa1504e6f",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "a25674ac-a425-4f22-b4ad-eb75b8df090f",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "5225911b-7799-4a6f-8af1-e1428a402186",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "70b2b52e-a487-4747-a987-4e8e127f91fb",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "cec8ae60-fbac-4431-8a26-c13a3ad04183",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "01860384-68ba-4831-820c-2cfe198294df",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "91352547-91b3-422f-b768-918fed37b343",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "c133dfc7-47fd-4474-ba75-61330b84789d",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "61215a94-71c3-462c-b8f8-06a5b833542b",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "d30e2984-eb9b-4691-aad4-7350128ad876",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "c23804bd-7476-465e-ab7d-a50950bd8e49",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "72f08345-4263-4e15-a54b-2a223b848489",
                "ordinal": 3
              }
            ],
            "lineageTag": "198026b8-4b4e-4c82-b36d-6905ee8654f8"
          }
        ],
        "isHidden": true,
        "lineageTag": "7507be74-9606-404e-bc20-609b2f779691",
        "partitions": [
          {
            "name": "LocalDateTable_c63d3909-04ff-4e99-855a-2f8fa1504e6f",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('status oLPN'[Data locação pedido])), 1, 1), Date(Year(MAX('status oLPN'[Data locação pedido])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_26ede0fe-5b25-41aa-a9c9-3632ca32ab7e",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "b1ab45d5-64ef-488b-81a6-e760456e9aa4",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "008e6112-5e8a-4a20-809e-b64ba6bc5e8f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "06cd3b7d-2152-42a1-90ac-0b4232de6052",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "b21861b0-322f-4fbb-a33a-0018f433e268",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "f5a318d8-98d6-42a3-8a0e-9a38d333f20f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "6bf09813-2322-409c-ae9c-60881a32eba1",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "3a06b7db-943d-40e7-aaea-2b69bc7b1a9d",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "d029223a-e8f1-4c19-9715-a3df90acd929",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "796d77fc-ae5a-46a9-8470-b3286ea6ddc3",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "590b757b-0761-4eb9-ad56-5560797a5c4b",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "28014f7e-2ef6-4260-ae05-a23e63f11b31",
                "ordinal": 3
              }
            ],
            "lineageTag": "c334c159-08ea-49d8-b761-5325f1122cf5"
          }
        ],
        "isHidden": true,
        "lineageTag": "1ff9a808-a343-4b99-8e20-b2598dee3b29",
        "partitions": [
          {
            "name": "LocalDateTable_26ede0fe-5b25-41aa-a9c9-3632ca32ab7e",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('status oLPN'[Último Update oLPN])), 1, 1), Date(Year(MAX('status oLPN'[Último Update oLPN])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_7cccec5d-27f3-406a-8bc5-57140bba9558",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "0d2b19b0-211d-42f3-bf0b-c2e3a60ed38d",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "89ee2122-b929-4754-8a94-3e5ba84a60c5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "fda064e0-8ca4-47cb-b1cc-fbfeb9fb6cd9",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "c77642f0-0779-4a3d-b958-4f9919fe7776",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "1b1d7fba-4e7d-4787-9adc-9a0502d7f51e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "ded0006a-c555-4887-b8db-8c14260e983b",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "ac19837b-4360-43c5-854f-d8d96020a9b9",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "c0aed0c3-8a3f-4d0d-9e2c-5c86f5b33c11",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "a4b19b65-b184-4f6d-9e5d-8d91af0185d1",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "68f25a10-584a-4b5c-aacf-83639a7ff44d",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "3f4636ad-7689-463b-bc03-a35b75142016",
                "ordinal": 3
              }
            ],
            "lineageTag": "7ea645c9-1d0a-493d-882c-c685f9da4c39"
          }
        ],
        "isHidden": true,
        "lineageTag": "be3fc6ab-d7ec-4fea-af7a-490807e9ea17",
        "partitions": [
          {
            "name": "LocalDateTable_7cccec5d-27f3-406a-8bc5-57140bba9558",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('status oLPN'[Data Prevista Entrega])), 1, 1), Date(Year(MAX('status oLPN'[Data Prevista Entrega])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "dHora",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "columns": [
          {
            "name": "Hora",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "e4aa3406-3aac-4a6d-8bde-4cd40e91ef0a",
            "sourceColumn": "Hora",
            "summarizeBy": "none"
          },
          {
            "name": "Hora Num",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d244a732-3efb-4970-b307-f84ffa165369",
            "sourceColumn": "Hora Num",
            "summarizeBy": "sum"
          },
          {
            "name": "AMPM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "578c49af-957d-4ffa-9dd1-1de930bc4b04",
            "sourceColumn": "AMPM",
            "summarizeBy": "none"
          },
          {
            "name": "Hora AMPM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "46ae565a-be9d-4390-8357-cbdc247a409b",
            "sourceColumn": "Hora AMPM",
            "summarizeBy": "none"
          },
          {
            "name": "Periodo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "89ed4939-d0e9-4802-9b51-f8bc929f4c8c",
            "sourceColumn": "Periodo",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "cd46b015-e069-4c00-aac6-134ce44bcc76",
        "partitions": [
          {
            "name": "dHora",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Lista = {0..86399},",
                "    ConverteParaTabela = Table.FromList(Lista, Splitter.SplitByNothing(), null, null, ExtraValues.Error),",
                "    AlteraTipo = Table.TransformColumnTypes(ConverteParaTabela,{{\"Column1\", Int64.Type}}),",
                "    AlteraNomeCol = Table.RenameColumns(AlteraTipo,{{\"Column1\",\"Segundo\"}}),",
                "    ColDuracao = Table.AddColumn(AlteraNomeCol,\"Duração\", each #duration(0,0,0,[Segundo]), type duration),",
                "    ColHora = Table.AddColumn(ColDuracao,\"Hora\", each #time(Duration.Hours([Duração]), Duration.Minutes([Duração]), Duration.Seconds([Duração]))),",
                "    RemoveCols = Table.RemoveColumns(ColHora,{\"Duração\",\"Segundo\"}),",
                "    CollHoraNum = Table.AddColumn(RemoveCols, \"Hora Num\", each Time.Hour([Hora])),",
                "    ColAMPM = Table.AddColumn(CollHoraNum, \"AMPM\", each if [Hora Num] < 12 then \"AM\" else \"PM\", type text),",
                "    ColHoraAMPM = Table.AddColumn(ColAMPM,\"Hora AMPM\", each",
                "        if [Hora Num] = 0 then \"12 AM\"",
                "        else if [Hora Num] >= 1 and [Hora Num] <= 11 then Number.ToText([Hora Num]) & \" AM\"",
                "        else if [Hora Num] = 12 then \"12 PM\"",
                "        else if [Hora Num] >= 13 then Number.ToText([Hora Num] - 12) & \" PM\"",
                "        else \"Unknown\", type text),",
                "    ColPeriodo = Table.AddColumn(ColHoraAMPM,\"Periodo\", each",
                "        if [Hora Num] >= 0 and [Hora Num] <= 5 then \"12AM to 6AM\"",
                "        else if [Hora Num] >= 6 and [Hora Num] <= 11 then \"6AM to 12PM\" ",
                "        else if [Hora Num] >= 12 and [Hora Num] <= 17 then \"12PM to 6PM\"",
                "        else if [Hora Num] >= 18 and [Hora Num] <= 23 then \"6PM to 12AM\"",
                "        else \"Unknown\", type text),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(ColPeriodo,{{\"Hora\", type time}, {\"Hora Num\", Int64.Type}})",
                "in",
                "    #\"Tipo Alterado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_dd0d8641-6c07-4ce1-a5cc-5c9d44d4aa0d",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "781e1da1-0916-4dc8-9a14-4b3054bc4526",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "adb5fefb-6ed0-4a06-8af1-8e977d17b8eb",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "db795ee6-bfd5-47d4-9dc4-eb504a06403e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "24b05958-901f-40b1-bf95-43e4b71f1ca2",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "0d0af7e1-2e72-454b-b594-bdfca3a9abe9",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "eb6b959a-326c-4cc7-9712-d16648f63e9c",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "5fb246b9-c367-42c1-aff4-cc827a7d3f9a",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "ab631fc5-3d29-4539-9a9e-5da5dc6fde6f",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "b091e805-16da-40cf-985a-1a088e35ad26",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "0417a839-bc61-411b-a0d4-b33e751908cc",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "1d8275c2-bf72-465f-be56-23276bd98cb6",
                "ordinal": 3
              }
            ],
            "lineageTag": "649e5970-238a-4f8d-82ef-2eee1114cf48"
          }
        ],
        "isHidden": true,
        "lineageTag": "ef81c3d2-603c-40a5-8327-48968d3b3e6c",
        "partitions": [
          {
            "name": "LocalDateTable_dd0d8641-6c07-4ce1-a5cc-5c9d44d4aa0d",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('entrada'[DATA DE LIMITE])), 1, 1), Date(Year(MAX('entrada'[DATA DE LIMITE])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_222bf26e-cc17-4215-bf94-0aa98a5433de",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "642694aa-56b2-4212-a153-7b5722059901",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "db848a91-e34f-4b64-a59d-4aa5f51cb384",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "69b017b8-014c-4c2c-a337-8a0085c0a5eb",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "7737ffb0-0c0c-4a12-9c3a-b7ca32fe3ee5",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "fa77d0c4-5c6f-4bed-a566-0c1f806119f5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "5c573078-3abb-4fc7-ad11-30c16c12e41f",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "f67bf61c-b12c-471c-bdf1-4af73e2718f1",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "e9aa83dd-8800-4067-9563-c867112b9fd8",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "59c38429-11f1-434f-87b1-be287fbd6e8e",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "e0d8e87c-e03b-4dca-be67-79bb5bebe0e5",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "e9cfb7d5-8d29-49f3-9921-5dd95df9d4c5",
                "ordinal": 3
              }
            ],
            "lineageTag": "42fcd2b5-e788-4e1b-9125-2dc02f025db9"
          }
        ],
        "isHidden": true,
        "lineageTag": "d1b992ae-a1fe-467e-ab3c-2a97e6aeef83",
        "partitions": [
          {
            "name": "LocalDateTable_222bf26e-cc17-4215-bf94-0aa98a5433de",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('entrada'[DATA DA INTEGRACAO])), 1, 1), Date(Year(MAX('entrada'[DATA DA INTEGRACAO])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "tTempo",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "hora_atual",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "484d8087-59b6-4852-a6bc-d577c2f526a1",
            "sourceColumn": "hora_atual",
            "summarizeBy": "none"
          },
          {
            "name": "data_atual",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "69f7ec90-5b6d-44da-8fe4-7b1085de6631",
            "sourceColumn": "data_atual",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_bb704698-fda9-40bc-afa2-c582658f15c5"
                },
                "isDefault": true,
                "relationship": "09dc630a-cb70-476f-a50e-d668e9aca4be"
              }
            ]
          }
        ],
        "lineageTag": "3d9a607e-477f-4e6f-b93a-937da8719779",
        "partitions": [
          {
            "name": "tTempo",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WMlSKjQUA\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [hora = _t]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(Fonte,{{\"hora\", Int64.Type}}),",
                "    #\"Personalização Adicionada\" = Table.AddColumn(#\"Tipo Alterado\", \"hora_atual\", each Time.From(DateTime.LocalNow() - #duration(0,3,0,0))),",
                "    #\"Tipo Alterado1\" = Table.TransformColumnTypes(#\"Personalização Adicionada\",{{\"hora_atual\", type time}}),",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(#\"Tipo Alterado1\",{\"hora\"}),",
                "    #\"Personalização Adicionada1\" = Table.AddColumn(#\"Colunas Removidas\", \"data_atual\", each Date.From(DateTime.LocalNow() - #duration(0,3,0,0))),",
                "    #\"Tipo Alterado2\" = Table.TransformColumnTypes(#\"Personalização Adicionada1\",{{\"data_atual\", type date}})",
                "in",
                "    #\"Tipo Alterado2\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_bb704698-fda9-40bc-afa2-c582658f15c5",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "5f253f51-b257-40b9-84b1-5625721ea9b0",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "4dfdeed9-aaaf-4ecf-9980-8fc87fb43f98",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "249c97cb-228e-4073-a5fc-7e59307e484b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "713cdb4a-612c-4a04-aafa-9b9c21af7f41",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "d88e2204-a8ee-4751-8536-38cb26433d1f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "d7c86dce-03fb-4b43-bc04-1d7ba797af0a",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "25db7286-ec53-4ca5-ba7f-3b2163caf89e",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "e09b7e2e-03c7-4037-9822-39d7660b9162",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "0539cccc-cb58-4597-920f-421010891e1c",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "df386b88-9109-45be-9824-5e481e5b6ecf",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "21fc003d-3185-47da-848c-08afbc388940",
                "ordinal": 3
              }
            ],
            "lineageTag": "88e7a2d0-d1ae-4efa-9b22-55d7ec69ba65"
          }
        ],
        "isHidden": true,
        "lineageTag": "8e8abd51-e31e-4441-a62c-844ac77242a9",
        "partitions": [
          {
            "name": "LocalDateTable_bb704698-fda9-40bc-afa2-c582658f15c5",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('tTempo'[data_atual])), 1, 1), Date(Year(MAX('tTempo'[data_atual])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "dTabela",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Status Fracionado",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "74bea61c-58a1-44db-ac13-a7009d0213dc",
            "sourceColumn": "Status Fracionado",
            "summarizeBy": "none"
          },
          {
            "name": "Status VVLOG",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e0336696-e95b-46d7-87ad-6f33c4ee24de",
            "sourceColumn": "Status VVLOG",
            "summarizeBy": "none"
          },
          {
            "name": "seq",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "877315e4-07b0-422b-aaf5-ed5dc7aa6336",
            "sourceColumn": "seq",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "68d57423-b0cb-42d2-8dfc-a999f7280d14",
        "partitions": [
          {
            "name": "dTabela",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45Wck4sKknNLEpU0kEwY3WilYJSc1ITi1NTFHQVXHMVAopSCxKLEg8vP7w4H6gSjyRIr3NRamIJTDYYRSdOKVR9bpm5CimpOPVikQbpD0hMzgbKB+spuCdm5uckQmxxSywpLUrMTc0rARlCWA2SSc6oqlwrClJTMmHOIawmNhYA\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Status Fracionado\" = _t, #\"Status VVLOG\" = _t]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(Fonte,{{\"Status Fracionado\", type text}, {\"Status VVLOG\", type text}}),",
                "    #\"Personalização Adicionada\" = Table.AddColumn(#\"Tipo Alterado\", \"seq\", each if [Status Fracionado] = \"Carteira\" then 1 else if [Status Fracionado] = \"Released - Em Preparação\" then 2 else if [Status Fracionado] = \"Created - Em Separação\" then 3 else if [Status Fracionado] = \"Created - Fim de Separação\" then 4 else if [Status Fracionado] = \"Packed S. Gaiola - Em Faturamento\" then 5 else if [Status Fracionado] = \"Packed C. Gaiola - Em Expedição\" then 6 else null),",
                "    #\"Tipo Alterado1\" = Table.TransformColumnTypes(#\"Personalização Adicionada\",{{\"seq\", Int64.Type}})",
                "in",
                "    #\"Tipo Alterado1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_a6bf9114-e982-44b9-a50c-2f6304f840bf",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "292a81f4-192e-4246-a885-23fa8e04d982",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "094b9e65-8ef5-49cb-8ea6-c775ca48aa13",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "a554868c-3117-4e40-bfe4-8af0dfa59a71",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "769b95fe-52b7-4164-8b90-890e357c546c",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "33ca68f5-19e5-4de8-9264-c473f356eecd",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "96f91c50-74c7-4dc3-bc29-b10a5b137e8e",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "42d61ea0-9e43-42f2-8038-c233473c897b",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "d44a615d-d71f-40a6-9370-7a51772d8426",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "d6b25d3e-a8d1-49e5-a3d4-bd6e05624445",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "6fb96f3c-3819-4906-8172-2e7b2739763b",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "bf639b84-919e-4053-9780-bca3c6751c0d",
                "ordinal": 3
              }
            ],
            "lineageTag": "95d5e07e-235d-4f43-8247-2a16a720f844"
          }
        ],
        "isHidden": true,
        "lineageTag": "1006e819-d8de-4be8-81df-2423d8462f2d",
        "partitions": [
          {
            "name": "LocalDateTable_a6bf9114-e982-44b9-a50c-2f6304f840bf",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('carteira'[data limite])), 1, 1), Date(Year(MAX('carteira'[data limite])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "tDin_carteira",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "CÓDIGO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ce2e4414-8ea6-4dc5-8daf-cbb61103517e",
            "sourceColumn": "CÓDIGO",
            "summarizeBy": "none"
          },
          {
            "name": "ROTA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0c855d31-9ad2-4e6b-a2f2-dcd868cfb825",
            "sourceColumn": "ROTA",
            "summarizeBy": "none"
          },
          {
            "name": "TIPO DE ENTREGA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "690328f9-36ce-4523-980b-bcca4da68fa7",
            "sourceColumn": "TIPO DE ENTREGA",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "696bfad4-3fd6-44a5-8c5e-7ac021784827",
        "partitions": [
          {
            "name": "tDin_carteira",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"hdO9boQwDADgV7GYWykk/I4GcogrJCih12tPN9xQdezSoY/fAHELukidsORPju2EyyUqBY8eIjvGZVHOgRxgkC2C0RNCdH24RDHjbCGcceGCWhsjO219UhSUzF0gz6OR1uKS5IVI12SRzcX/Ch+bDr7BjMQyz3IWYNVvtZxYHKp2JFYQ4yFmiZXERICNxrOEEUsCzFY1uZjcPPPw/nED8/l1825oPcu4Z+W+XMwZg6bDXreaqCCa3lOLg4QGX8kmZLNQWSMnv8SS+wbW4G5sSUwQC23nUJ3JpeTSgKNZSrq6Ndgw1ThW06l0dWugtBmwh8qsD5H5h5pn/qFaPUjjFrbJcrbcQ2XQdj28yAomg8qO2kzSggSnO7v38xoOeNKmc/1sdT81uKfzKo7YuCLwCAeDdacVNtptzbrP3i4X4hv8T/NkfovL2T22zwoB3eRvUmHrxpRLV1sv4nnIk1RPWoH/5batR9frDw==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [CÓDIGO = _t, ROTA = _t, #\"TIPO DE ENTREGA\" = _t]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(Fonte,{{\"CÓDIGO\", Int64.Type}, {\"ROTA\", type text}, {\"TIPO DE ENTREGA\", type text}})",
                "in",
                "    #\"Tipo Alterado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_3926822b-92bc-4a54-a29e-0e2ec41e514a",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "1777232e-5fd7-447b-ae64-a80c747c77cc",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "b22203ea-905b-4dd2-8df3-7db02438b3d8",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "c8677f52-e328-4088-ba75-20ad6a9f3e82",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "24d435ea-e1d8-4384-a938-63957601771a",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "8f2b3d9a-e3bd-4cb8-85c0-bae6d06f74fd",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "bf2fdd29-35fd-4700-9147-bf166baf8ee2",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "9bbd543d-cc03-470b-8e1e-982d74533812",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "3a00b421-14a4-4e7f-86fd-de118d5fda15",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "58a6f21b-6377-4dbc-a983-1e1c3e329789",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "e4602b20-14e9-442f-bdc9-813d3897d0b5",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "460a0f89-2358-4839-99de-ffca47be466e",
                "ordinal": 3
              }
            ],
            "lineageTag": "b5c4236b-6fd2-4da3-a1ec-849718f8faac"
          }
        ],
        "isHidden": true,
        "lineageTag": "042ecb01-2701-4e24-b3e6-e740f8328c25",
        "partitions": [
          {
            "name": "LocalDateTable_3926822b-92bc-4a54-a29e-0e2ec41e514a",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('carteira'[data limite2])), 1, 1), Date(Year(MAX('carteira'[data limite2])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_70ce231e-4aa2-4a70-9ace-ea66fc5068c6",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "9b44c25f-75da-416e-8145-d9a7023b0422",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "fce2e8ce-0d29-4b43-a480-b0566d91f5df",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "fc023f99-8b84-4c10-b5b5-48212648e798",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "f7022ef5-b84e-47ec-af94-52b28082ec5a",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "26e09450-eb35-417d-9a75-08de66d1fc6a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "62bc4105-418f-4c8c-8274-3af6adf9d25a",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "48c071cf-7360-4419-8a84-0bf56ade8fe4",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "44c1cc5e-737f-4087-954b-2b8aab98e0f1",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "494cb1ea-1f2e-4c99-b3cd-12c08dba2d3c",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "5ce3e662-edd0-4588-87ec-ee185f985d95",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "704fac3e-94d0-480c-8c57-db993038e3cc",
                "ordinal": 3
              }
            ],
            "lineageTag": "ace719d9-5b5f-4e2f-ad54-d20e2a3fc84f"
          }
        ],
        "isHidden": true,
        "lineageTag": "79f63033-d094-4d7c-acba-5f84696cfb40",
        "partitions": [
          {
            "name": "LocalDateTable_70ce231e-4aa2-4a70-9ace-ea66fc5068c6",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('status oLPN'[data para a data])), 1, 1), Date(Year(MAX('status oLPN'[data para a data])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "tDesmarcados",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Column0",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "98778182-ecb7-478f-afdc-71c96aa0d247",
            "sourceColumn": "Column0",
            "summarizeBy": "none"
          },
          {
            "name": "Total VVLOG",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a37315fc-5317-497f-91c5-980d13f8e981",
            "sourceColumn": "Total VVLOG",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Fracionado",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "75901757-1ed5-4f44-8eee-f807df887f6d",
            "sourceColumn": "Total Fracionado",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "33c5d81b-7615-45f1-a17a-3e5951603f69",
        "partitions": [
          {
            "name": "tDesmarcados",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = SharePoint.Contents(\"https://viavarejo.sharepoint.com/sites/grupo_de_dados_wave\", [ApiVersion = 15]),",
                "    #\"Atualizaes de Relatrios Gerais\" = Fonte{[Name=\"Atualizaes de Relatrios Gerais\"]}[Content],",
                "    #\"Relatórios dinâmicos - ADMs - Vinicius & Almeida\" = #\"Atualizaes de Relatrios Gerais\"{[Name=\"Relatórios dinâmicos - ADMs - Vinicius & Almeida\"]}[Content],",
                "    #\"Relatórios rotativos\" = #\"Relatórios dinâmicos - ADMs - Vinicius & Almeida\"{[Name=\"Relatórios rotativos\"]}[Content],",
                "    #\"Painel Online - ADMs - Vinicius & Almeida\" = #\"Relatórios rotativos\"{[Name=\"Painel Online - ADMs - Vinicius & Almeida\"]}[Content],",
                "    #\"Qtd Pedidos - Desmarcados\" = #\"Painel Online - ADMs - Vinicius & Almeida\"{[Name=\"Qtd Pedidos - Desmarcados\"]}[Content],",
                "    #\"Desmarcados - ADMs - Vinícius xlsx\" = #\"Qtd Pedidos - Desmarcados\"{[Name=\"Desmarcados - ADMs - Vinícius.xlsx\"]}[Content],",
                "    #\"Pasta de Trabalho Importada do Excel\" = Excel.Workbook(#\"Desmarcados - ADMs - Vinícius xlsx\"),",
                "    Preencher_Sheet = #\"Pasta de Trabalho Importada do Excel\"{[Item=\"Preencher\",Kind=\"Sheet\"]}[Data],",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Preencher_Sheet, [PromoteAllScalars=true]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"Column0\", type text}, {\"Total VVLOG\", Int64.Type}, {\"Total Fracionado\", Int64.Type}})",
                "in",
                "    #\"Tipo Alterado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "documentacao_measures",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "aa9962cc46c74052861de0598ec44edd"
          }
        ],
        "columns": [
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "8af0837b-54b2-4f5d-a122-493888885b48",
            "sourceColumn": "[ID]",
            "summarizeBy": "count",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "909a37b9-68f7-46b9-af3e-23d2dde93cf5",
            "sourceColumn": "[Name]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Table",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "1fe98c69-1ab5-4de6-9023-3660db06d8b0",
            "sourceColumn": "[Table]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "fcfd81dc-7c8d-493d-9ab9-e996985428e0",
            "sourceColumn": "[Description]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "DataType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "e2e4a48a-1aac-427b-b201-f947ba732ade",
            "sourceColumn": "[DataType]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Expression",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "461f18f6-ea10-4150-85c0-5be56e5abe49",
            "sourceColumn": "[Expression]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "FormatString",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "5befa41a-d666-44b2-a65d-c2b07225d082",
            "sourceColumn": "[FormatString]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "IsHidden",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "e1af42ce-9f79-44c2-b9b3-5ea78fd721ab",
            "sourceColumn": "[IsHidden]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "State",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "3b0552a9-89d9-4d89-9a7b-b3d147161d9a",
            "sourceColumn": "[State]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "KPIID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "71c88122-f41c-460c-a286-312626955079",
            "sourceColumn": "[KPIID]",
            "summarizeBy": "count",
            "type": "calculatedTableColumn"
          },
          {
            "name": "IsSimpleMeasure",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "d56536be-3e10-4a02-86d0-028bd87c8cbd",
            "sourceColumn": "[IsSimpleMeasure]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "DisplayFolder",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "67de8b97-c832-4bcf-88ee-6d9ffc8dd203",
            "sourceColumn": "[DisplayFolder]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "DetailRowsDefinition",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "cf3ed8f7-b5f5-4bee-985b-9669c0ab9b03",
            "sourceColumn": "[DetailRowsDefinition]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "DataCategory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "f7d926ca-299c-403f-a33f-427d0bc72e23",
            "sourceColumn": "[DataCategory]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "FormatStringDefinition",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "87b4ac08-b136-43bf-bac7-1d2e22b0675c",
            "sourceColumn": "[FormatStringDefinition]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "LineageTag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "c73a889c-4cba-42ea-ac06-faf4f9ae76db",
            "sourceColumn": "[LineageTag]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "c4ba9ac1-ecaa-4f2e-b558-8d8596626e6d",
        "partitions": [
          {
            "name": "documentacao_measures",
            "mode": "import",
            "source": {
              "expression": "INFO.VIEW.MEASURES()",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "documentacao_tables",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "572a8fecdffd4243b3227454ee12047c"
          }
        ],
        "columns": [
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "f067b2c0-34c4-4a74-a29d-e7bf5a0c78b4",
            "sourceColumn": "[ID]",
            "summarizeBy": "count",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "194f39b4-85a5-4c16-a1d9-21d2ee92e44e",
            "sourceColumn": "[Name]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Model",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "3cf6e671-5113-48ad-80cd-c2e3e6b16c9e",
            "sourceColumn": "[Model]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "DataCategory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "b01b2ac6-2962-4c7d-a385-82b06ecca7ea",
            "sourceColumn": "[DataCategory]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "916078cb-15d6-4dd9-94eb-207f131ab8d7",
            "sourceColumn": "[Description]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "IsHidden",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "25614b1a-d153-4406-b958-f1461e1157ed",
            "sourceColumn": "[IsHidden]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "StorageMode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "ceadaec5-272b-46b2-b261-97e57e359c8e",
            "sourceColumn": "[StorageMode]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "TableStorage",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "aa97bad9-71f7-4503-a2ff-de26f0f76375",
            "sourceColumn": "[TableStorage]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Expression",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "ba306baa-84df-4a01-935e-76f799c8ba25",
            "sourceColumn": "[Expression]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "ShowAsVariationOnly",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "b81ee210-554d-4e12-bf4c-221b6f272dee",
            "sourceColumn": "[ShowAsVariationOnly]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "IsPrivate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "7af7581b-9f15-4876-8c25-802fa3dd540e",
            "sourceColumn": "[IsPrivate]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "CalculationGroupPrecedence",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "87196008-176f-49c1-bf87-ece70fc9907d",
            "sourceColumn": "[CalculationGroupPrecedence]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "LineageTag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "d764e15b-e4f8-483a-90fa-c0f0b9284bc4",
            "sourceColumn": "[LineageTag]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "c250abe4-ba1d-4d35-bc1f-47b46dc67e1f",
        "partitions": [
          {
            "name": "documentacao_tables",
            "mode": "import",
            "source": {
              "expression": "INFO.VIEW.TABLES()",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "documentacao_relationships",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "54c5cec8d92047e48841fc40918ca652"
          }
        ],
        "columns": [
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "ee3a74d9-8c1d-4e91-a245-7841665d32f4",
            "sourceColumn": "[ID]",
            "summarizeBy": "count",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "3901d72d-d283-4e05-9fed-2a91c2d905ce",
            "sourceColumn": "[Name]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Relationship",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "4e9bbdd3-b8e2-44e8-8948-8f0877fcc23a",
            "sourceColumn": "[Relationship]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Model",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "ca615bf1-b151-4463-9607-c52c281cc1d4",
            "sourceColumn": "[Model]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "IsActive",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "2c3249a8-aeb8-422b-a6c4-f784e6d7b672",
            "sourceColumn": "[IsActive]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "CrossFilteringBehavior",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "dac6e330-83f7-43fc-a20d-7d387e08c164",
            "sourceColumn": "[CrossFilteringBehavior]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "RelyOnReferentialIntegrity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "a4c6b315-dc83-408a-ad3b-ae7cdfb5b093",
            "sourceColumn": "[RelyOnReferentialIntegrity]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "FromTable",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "855c865c-59ab-4749-bb7b-655f584b4179",
            "sourceColumn": "[FromTable]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "FromColumn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "495471dd-6ff2-4c82-863e-84eaee18d913",
            "sourceColumn": "[FromColumn]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "FromCardinality",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "5f8ceb82-51d2-4eb3-90c7-773599ccb15d",
            "sourceColumn": "[FromCardinality]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "ToTable",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "ff893bc0-bdb8-43f3-b979-dc5409c9fcbc",
            "sourceColumn": "[ToTable]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "ToColumn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "a50a0030-8794-4cf8-9b7c-6b98adec7e8b",
            "sourceColumn": "[ToColumn]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "ToCardinality",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "54f50b94-dfc2-4786-85b3-5f555cdb447d",
            "sourceColumn": "[ToCardinality]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "State",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "f4d09d06-6b01-477e-a1d0-34df4a0d0800",
            "sourceColumn": "[State]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "SecurityFilteringBehavior",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "a32b11ba-a6c8-4daa-91fc-4987a70f3c94",
            "sourceColumn": "[SecurityFilteringBehavior]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "6a2a8aea-f74b-4ba3-aeac-9f4c61c17a5c",
        "partitions": [
          {
            "name": "documentacao_relationships",
            "mode": "import",
            "source": {
              "expression": "INFO.VIEW.RELATIONSHIPS()",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "documentacao_columns",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "547379b089e64cafab157d6c80beb533"
          }
        ],
        "columns": [
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "052dfa7c-bd9c-40ed-94d8-696ef6b5bb0d",
            "sourceColumn": "[ID]",
            "summarizeBy": "count",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "252169ff-e16f-4f43-af44-4558d458f231",
            "sourceColumn": "[Name]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Table",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "945c3d53-4742-458f-a356-e331a4644ce0",
            "sourceColumn": "[Table]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "DataType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "f148f8fe-8203-4d0c-a767-1f4fe6669d0c",
            "sourceColumn": "[DataType]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "DataCategory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "96e1c45d-b95d-437c-a472-38fb2ae768cb",
            "sourceColumn": "[DataCategory]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "d0286b05-e70a-477a-955b-73a5dc1c0fa1",
            "sourceColumn": "[Description]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "IsHidden",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "194a826e-bc37-400f-a044-e5f648e0ab85",
            "sourceColumn": "[IsHidden]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "IsUnique",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "1e039f1e-2c36-4777-9793-556805e8eec7",
            "sourceColumn": "[IsUnique]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "IsKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "bcaa6f0a-9196-46e6-95b0-69b872ba62ff",
            "sourceColumn": "[IsKey]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "IsNullable",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "09eb4a7e-af80-49ac-a3a8-fed7576662bd",
            "sourceColumn": "[IsNullable]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Alignment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "930306e7-9c7c-49af-9250-712ba8866e2d",
            "sourceColumn": "[Alignment]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "SummarizeBy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "69aa340c-fea6-473b-815e-df4d0552270b",
            "sourceColumn": "[SummarizeBy]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "ColumnStorage",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "c0a91516-7fd4-4d2a-8be9-cc9434348bcc",
            "sourceColumn": "[ColumnStorage]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "c42ce6a8-6d50-4fa5-a579-c2586c3f5d6a",
            "sourceColumn": "[Type]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "SourceColumn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "42b97a5f-8d33-42dc-97c3-1f7429934a73",
            "sourceColumn": "[SourceColumn]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Expression",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "c0df78f0-3966-4434-aa45-ec9ffd7407ad",
            "sourceColumn": "[Expression]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "FormatString",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "3f0efa05-05c8-4d29-8735-77eefde7a4b3",
            "sourceColumn": "[FormatString]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "IsAvailableInMDX",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "ccf43492-57ec-4286-a4f4-1c0ab507ffff",
            "sourceColumn": "[IsAvailableInMDX]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "SortByColumn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "8e7a8367-78a5-4f2f-b8bb-d99f3654c72b",
            "sourceColumn": "[SortByColumn]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "GroupingBehavior",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "2fab7597-76c0-4076-9f3c-21265a4fe77f",
            "sourceColumn": "[GroupingBehavior]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "SourceProviderType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "5c3c97d4-d8da-4d41-9bfe-f4f6424e171d",
            "sourceColumn": "[SourceProviderType]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "DisplayFolder",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "9d27ccbe-5011-41c9-9bd5-4a781a26402e",
            "sourceColumn": "[DisplayFolder]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "AlternateOf",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "ac603e61-ff49-4358-9776-905145e59623",
            "sourceColumn": "[AlternateOf]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "LineageTag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "c9dc7b62-32e4-4455-a3bb-cadddb256cd2",
            "sourceColumn": "[LineageTag]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "975ccf8d-4b0b-4711-9036-ef5f8c33efcc",
        "partitions": [
          {
            "name": "documentacao_columns",
            "mode": "import",
            "source": {
              "expression": "INFO.VIEW.COLUMNS()",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_ac232e2a-83b0-4b47-81e3-e9456bc653d8",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "1fc21b6b-c425-4c50-ad58-5028c6bcf206",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "d9aaa250-c452-4ee7-81be-3493f06e969d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "08087f06-4d13-48db-acd4-120679430d44",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "21af483e-568a-4f29-baae-236200a29f20",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "88d91ee2-74f9-4639-99e4-64004cef2df0",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "dffe4991-bce0-4124-9d8a-a89893c8a9c8",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "7b9033b4-616c-4dea-956c-08b6c4ce4180",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "8623abd2-d80b-4e1a-a23a-aa219db3988f",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "4980eae7-5e08-4def-8890-d1199a5bb91a",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "67936225-ac79-473e-8722-b3d176bf3225",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "eb6934f6-a428-490a-b72e-8e0293dd6ac6",
                "ordinal": 3
              }
            ],
            "lineageTag": "cb66b4bc-6fea-41af-bdd1-179f3f97ea30"
          }
        ],
        "isHidden": true,
        "lineageTag": "4d89cd5c-6736-439f-98d1-399c171c2eaf",
        "partitions": [
          {
            "name": "LocalDateTable_ac232e2a-83b0-4b47-81e3-e9456bc653d8",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('status oLPN'[Data Limite Expedição])), 1, 1), Date(Year(MAX('status oLPN'[Data Limite Expedição])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}